// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cable_routes.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCableRoute = `-- name: CreateCableRoute :one

INSERT INTO cable_routes (
    tenant_id, from_node_id, to_node_id, route_type,
    coordinates, distance_meters, core_count, description
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, tenant_id, from_node_id, to_node_id, route_type,
    coordinates, distance_meters, core_count, description,
    deleted_at, created_at, updated_at
`

type CreateCableRouteParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	FromNodeID     pgtype.UUID `json:"from_node_id"`
	ToNodeID       pgtype.UUID `json:"to_node_id"`
	RouteType      string      `json:"route_type"`
	Coordinates    []byte      `json:"coordinates"`
	DistanceMeters float64     `json:"distance_meters"`
	CoreCount      pgtype.Int4 `json:"core_count"`
	Description    pgtype.Text `json:"description"`
}

// Query SQL untuk operasi CRUD tabel cable_routes.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel cable_routes dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Semua query menyertakan WHERE deleted_at IS NULL untuk mengecualikan soft-deleted.
func (q *Queries) CreateCableRoute(ctx context.Context, arg CreateCableRouteParams) (CableRoute, error) {
	row := q.db.QueryRow(ctx, createCableRoute,
		arg.TenantID,
		arg.FromNodeID,
		arg.ToNodeID,
		arg.RouteType,
		arg.Coordinates,
		arg.DistanceMeters,
		arg.CoreCount,
		arg.Description,
	)
	var i CableRoute
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FromNodeID,
		&i.ToNodeID,
		&i.RouteType,
		&i.Coordinates,
		&i.DistanceMeters,
		&i.CoreCount,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCableRouteByID = `-- name: GetCableRouteByID :one
SELECT id, tenant_id, from_node_id, to_node_id, route_type,
    coordinates, distance_meters, core_count, description,
    deleted_at, created_at, updated_at
FROM cable_routes
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCableRouteByID(ctx context.Context, id pgtype.UUID) (CableRoute, error) {
	row := q.db.QueryRow(ctx, getCableRouteByID, id)
	var i CableRoute
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FromNodeID,
		&i.ToNodeID,
		&i.RouteType,
		&i.Coordinates,
		&i.DistanceMeters,
		&i.CoreCount,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCableRoutesByBounds = `-- name: ListCableRoutesByBounds :many
SELECT cr.id, cr.tenant_id, cr.from_node_id, cr.to_node_id, cr.route_type,
    cr.coordinates, cr.distance_meters, cr.core_count, cr.description,
    cr.deleted_at, cr.created_at, cr.updated_at
FROM cable_routes cr
JOIN map_nodes fn ON cr.from_node_id = fn.id
JOIN map_nodes tn ON cr.to_node_id = tn.id
WHERE cr.deleted_at IS NULL
  AND (
    (fn.latitude BETWEEN $1 AND $2 AND fn.longitude BETWEEN $3 AND $4)
    OR
    (tn.latitude BETWEEN $1 AND $2 AND tn.longitude BETWEEN $3 AND $4)
  )
  AND ($5::varchar IS NULL OR cr.route_type = $5::varchar)
ORDER BY cr.created_at DESC
`

type ListCableRoutesByBoundsParams struct {
	Latitude    float64     `json:"latitude"`
	Latitude_2  float64     `json:"latitude_2"`
	Longitude   float64     `json:"longitude"`
	Longitude_2 float64     `json:"longitude_2"`
	RouteType   pgtype.Text `json:"route_type"`
}

func (q *Queries) ListCableRoutesByBounds(ctx context.Context, arg ListCableRoutesByBoundsParams) ([]CableRoute, error) {
	rows, err := q.db.Query(ctx, listCableRoutesByBounds,
		arg.Latitude,
		arg.Latitude_2,
		arg.Longitude,
		arg.Longitude_2,
		arg.RouteType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CableRoute{}
	for rows.Next() {
		var i CableRoute
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.RouteType,
			&i.Coordinates,
			&i.DistanceMeters,
			&i.CoreCount,
			&i.Description,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCableRoutesByNode = `-- name: ListCableRoutesByNode :many
SELECT id, tenant_id, from_node_id, to_node_id, route_type,
    coordinates, distance_meters, core_count, description,
    deleted_at, created_at, updated_at
FROM cable_routes
WHERE (from_node_id = $1 OR to_node_id = $1) AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListCableRoutesByNode(ctx context.Context, fromNodeID pgtype.UUID) ([]CableRoute, error) {
	rows, err := q.db.Query(ctx, listCableRoutesByNode, fromNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CableRoute{}
	for rows.Next() {
		var i CableRoute
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.RouteType,
			&i.Coordinates,
			&i.DistanceMeters,
			&i.CoreCount,
			&i.Description,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCableRoute = `-- name: SoftDeleteCableRoute :exec
UPDATE cable_routes SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCableRoute(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCableRoute, id)
	return err
}

const updateCableRoute = `-- name: UpdateCableRoute :one
UPDATE cable_routes SET
    route_type = $2,
    coordinates = $3,
    distance_meters = $4,
    core_count = $5,
    description = $6,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, from_node_id, to_node_id, route_type,
    coordinates, distance_meters, core_count, description,
    deleted_at, created_at, updated_at
`

type UpdateCableRouteParams struct {
	ID             pgtype.UUID `json:"id"`
	RouteType      string      `json:"route_type"`
	Coordinates    []byte      `json:"coordinates"`
	DistanceMeters float64     `json:"distance_meters"`
	CoreCount      pgtype.Int4 `json:"core_count"`
	Description    pgtype.Text `json:"description"`
}

func (q *Queries) UpdateCableRoute(ctx context.Context, arg UpdateCableRouteParams) (CableRoute, error) {
	row := q.db.QueryRow(ctx, updateCableRoute,
		arg.ID,
		arg.RouteType,
		arg.Coordinates,
		arg.DistanceMeters,
		arg.CoreCount,
		arg.Description,
	)
	var i CableRoute
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FromNodeID,
		&i.ToNodeID,
		&i.RouteType,
		&i.Coordinates,
		&i.DistanceMeters,
		&i.CoreCount,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
