// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dhcp_bindings.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDHCPBindings = `-- name: CountDHCPBindings :one
SELECT COUNT(*) FROM dhcp_bindings
WHERE router_id = $1 AND deleted_at IS NULL
  AND ($2::varchar IS NULL
       OR mac_address ILIKE '%' || $2::varchar || '%'
       OR host_name ILIKE '%' || $2::varchar || '%'
       OR host(ip_address) ILIKE '%' || $2::varchar || '%')
`

type CountDHCPBindingsParams struct {
	RouterID pgtype.UUID `json:"router_id"`
	Search   pgtype.Text `json:"search"`
}

func (q *Queries) CountDHCPBindings(ctx context.Context, arg CountDHCPBindingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDHCPBindings, arg.RouterID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDHCPBinding = `-- name: CreateDHCPBinding :one

INSERT INTO dhcp_bindings (
    tenant_id, router_id, customer_id, router_lease_id,
    server, mac_address, ip_address, host_name,
    comment, disabled, status, sync_status
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12
)
RETURNING id, tenant_id, router_id, customer_id, router_lease_id,
    server, mac_address, ip_address, host_name, comment, disabled,
    status, last_sync_at, sync_status, created_at, updated_at, deleted_at
`

type CreateDHCPBindingParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	RouterID      pgtype.UUID `json:"router_id"`
	CustomerID    pgtype.UUID `json:"customer_id"`
	RouterLeaseID pgtype.Text `json:"router_lease_id"`
	Server        string      `json:"server"`
	MacAddress    string      `json:"mac_address"`
	IpAddress     netip.Addr  `json:"ip_address"`
	HostName      pgtype.Text `json:"host_name"`
	Comment       string      `json:"comment"`
	Disabled      bool        `json:"disabled"`
	Status        string      `json:"status"`
	SyncStatus    string      `json:"sync_status"`
}

// Query SQL untuk operasi tabel dhcp_bindings.
func (q *Queries) CreateDHCPBinding(ctx context.Context, arg CreateDHCPBindingParams) (DhcpBinding, error) {
	row := q.db.QueryRow(ctx, createDHCPBinding,
		arg.TenantID,
		arg.RouterID,
		arg.CustomerID,
		arg.RouterLeaseID,
		arg.Server,
		arg.MacAddress,
		arg.IpAddress,
		arg.HostName,
		arg.Comment,
		arg.Disabled,
		arg.Status,
		arg.SyncStatus,
	)
	var i DhcpBinding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RouterID,
		&i.CustomerID,
		&i.RouterLeaseID,
		&i.Server,
		&i.MacAddress,
		&i.IpAddress,
		&i.HostName,
		&i.Comment,
		&i.Disabled,
		&i.Status,
		&i.LastSyncAt,
		&i.SyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDHCPBindingByID = `-- name: GetDHCPBindingByID :one
SELECT id, tenant_id, router_id, customer_id, router_lease_id,
    server, mac_address, ip_address, host_name, comment, disabled,
    status, last_sync_at, sync_status, created_at, updated_at, deleted_at
FROM dhcp_bindings
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDHCPBindingByID(ctx context.Context, id pgtype.UUID) (DhcpBinding, error) {
	row := q.db.QueryRow(ctx, getDHCPBindingByID, id)
	var i DhcpBinding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RouterID,
		&i.CustomerID,
		&i.RouterLeaseID,
		&i.Server,
		&i.MacAddress,
		&i.IpAddress,
		&i.HostName,
		&i.Comment,
		&i.Disabled,
		&i.Status,
		&i.LastSyncAt,
		&i.SyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDHCPBindingByRouterAndIP = `-- name: GetDHCPBindingByRouterAndIP :one
SELECT id, tenant_id, router_id, customer_id, router_lease_id,
    server, mac_address, ip_address, host_name, comment, disabled,
    status, last_sync_at, sync_status, created_at, updated_at, deleted_at
FROM dhcp_bindings
WHERE router_id = $1 AND ip_address = $2 AND deleted_at IS NULL
`

type GetDHCPBindingByRouterAndIPParams struct {
	RouterID  pgtype.UUID `json:"router_id"`
	IpAddress netip.Addr  `json:"ip_address"`
}

func (q *Queries) GetDHCPBindingByRouterAndIP(ctx context.Context, arg GetDHCPBindingByRouterAndIPParams) (DhcpBinding, error) {
	row := q.db.QueryRow(ctx, getDHCPBindingByRouterAndIP, arg.RouterID, arg.IpAddress)
	var i DhcpBinding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RouterID,
		&i.CustomerID,
		&i.RouterLeaseID,
		&i.Server,
		&i.MacAddress,
		&i.IpAddress,
		&i.HostName,
		&i.Comment,
		&i.Disabled,
		&i.Status,
		&i.LastSyncAt,
		&i.SyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDHCPBindingByRouterAndMAC = `-- name: GetDHCPBindingByRouterAndMAC :one
SELECT id, tenant_id, router_id, customer_id, router_lease_id,
    server, mac_address, ip_address, host_name, comment, disabled,
    status, last_sync_at, sync_status, created_at, updated_at, deleted_at
FROM dhcp_bindings
WHERE router_id = $1 AND lower(mac_address) = lower($2) AND deleted_at IS NULL
`

type GetDHCPBindingByRouterAndMACParams struct {
	RouterID pgtype.UUID `json:"router_id"`
	Lower    string      `json:"lower"`
}

func (q *Queries) GetDHCPBindingByRouterAndMAC(ctx context.Context, arg GetDHCPBindingByRouterAndMACParams) (DhcpBinding, error) {
	row := q.db.QueryRow(ctx, getDHCPBindingByRouterAndMAC, arg.RouterID, arg.Lower)
	var i DhcpBinding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RouterID,
		&i.CustomerID,
		&i.RouterLeaseID,
		&i.Server,
		&i.MacAddress,
		&i.IpAddress,
		&i.HostName,
		&i.Comment,
		&i.Disabled,
		&i.Status,
		&i.LastSyncAt,
		&i.SyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDHCPBindings = `-- name: ListDHCPBindings :many
SELECT id, tenant_id, router_id, customer_id, router_lease_id,
    server, mac_address, ip_address, host_name, comment, disabled,
    status, last_sync_at, sync_status, created_at, updated_at, deleted_at
FROM dhcp_bindings
WHERE router_id = $1 AND deleted_at IS NULL
  AND ($4::varchar IS NULL
       OR mac_address ILIKE '%' || $4::varchar || '%'
       OR host_name ILIKE '%' || $4::varchar || '%'
       OR host(ip_address) ILIKE '%' || $4::varchar || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDHCPBindingsParams struct {
	RouterID pgtype.UUID `json:"router_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Search   pgtype.Text `json:"search"`
}

func (q *Queries) ListDHCPBindings(ctx context.Context, arg ListDHCPBindingsParams) ([]DhcpBinding, error) {
	rows, err := q.db.Query(ctx, listDHCPBindings,
		arg.RouterID,
		arg.Limit,
		arg.Offset,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DhcpBinding{}
	for rows.Next() {
		var i DhcpBinding
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RouterID,
			&i.CustomerID,
			&i.RouterLeaseID,
			&i.Server,
			&i.MacAddress,
			&i.IpAddress,
			&i.HostName,
			&i.Comment,
			&i.Disabled,
			&i.Status,
			&i.LastSyncAt,
			&i.SyncStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDHCPBinding = `-- name: SoftDeleteDHCPBinding :exec
UPDATE dhcp_bindings SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDHCPBinding(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteDHCPBinding, id)
	return err
}

const updateDHCPBinding = `-- name: UpdateDHCPBinding :one
UPDATE dhcp_bindings SET
    customer_id = $2,
    router_lease_id = $3,
    server = $4,
    mac_address = $5,
    ip_address = $6,
    host_name = $7,
    comment = $8,
    disabled = $9,
    status = $10,
    sync_status = $11,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, router_id, customer_id, router_lease_id,
    server, mac_address, ip_address, host_name, comment, disabled,
    status, last_sync_at, sync_status, created_at, updated_at, deleted_at
`

type UpdateDHCPBindingParams struct {
	ID            pgtype.UUID `json:"id"`
	CustomerID    pgtype.UUID `json:"customer_id"`
	RouterLeaseID pgtype.Text `json:"router_lease_id"`
	Server        string      `json:"server"`
	MacAddress    string      `json:"mac_address"`
	IpAddress     netip.Addr  `json:"ip_address"`
	HostName      pgtype.Text `json:"host_name"`
	Comment       string      `json:"comment"`
	Disabled      bool        `json:"disabled"`
	Status        string      `json:"status"`
	SyncStatus    string      `json:"sync_status"`
}

func (q *Queries) UpdateDHCPBinding(ctx context.Context, arg UpdateDHCPBindingParams) (DhcpBinding, error) {
	row := q.db.QueryRow(ctx, updateDHCPBinding,
		arg.ID,
		arg.CustomerID,
		arg.RouterLeaseID,
		arg.Server,
		arg.MacAddress,
		arg.IpAddress,
		arg.HostName,
		arg.Comment,
		arg.Disabled,
		arg.Status,
		arg.SyncStatus,
	)
	var i DhcpBinding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RouterID,
		&i.CustomerID,
		&i.RouterLeaseID,
		&i.Server,
		&i.MacAddress,
		&i.IpAddress,
		&i.HostName,
		&i.Comment,
		&i.Disabled,
		&i.Status,
		&i.LastSyncAt,
		&i.SyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDHCPBindingSyncState = `-- name: UpdateDHCPBindingSyncState :exec
UPDATE dhcp_bindings SET
    router_lease_id = $2,
    sync_status = $3,
    last_sync_at = $4,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateDHCPBindingSyncStateParams struct {
	ID            pgtype.UUID        `json:"id"`
	RouterLeaseID pgtype.Text        `json:"router_lease_id"`
	SyncStatus    string             `json:"sync_status"`
	LastSyncAt    pgtype.Timestamptz `json:"last_sync_at"`
}

func (q *Queries) UpdateDHCPBindingSyncState(ctx context.Context, arg UpdateDHCPBindingSyncStateParams) error {
	_, err := q.db.Exec(ctx, updateDHCPBindingSyncState,
		arg.ID,
		arg.RouterLeaseID,
		arg.SyncStatus,
		arg.LastSyncAt,
	)
	return err
}
