// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: geocoding_cache.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredGeocodingCache = `-- name: DeleteExpiredGeocodingCache :execrows
DELETE FROM geocoding_cache
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredGeocodingCache(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredGeocodingCache)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGeocodingCache = `-- name: GetGeocodingCache :one

SELECT id, tenant_id, lat_round, lng_round,
    address, raw_json, expires_at, created_at
FROM geocoding_cache
WHERE tenant_id = $1 AND lat_round = $2 AND lng_round = $3
  AND expires_at > NOW()
`

type GetGeocodingCacheParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	LatRound float64     `json:"lat_round"`
	LngRound float64     `json:"lng_round"`
}

// Query SQL untuk operasi pada tabel geocoding_cache.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel geocoding_cache dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Cache entries memiliki TTL (expires_at) dan dibersihkan secara periodik.
func (q *Queries) GetGeocodingCache(ctx context.Context, arg GetGeocodingCacheParams) (GeocodingCache, error) {
	row := q.db.QueryRow(ctx, getGeocodingCache, arg.TenantID, arg.LatRound, arg.LngRound)
	var i GeocodingCache
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LatRound,
		&i.LngRound,
		&i.Address,
		&i.RawJson,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const setGeocodingCache = `-- name: SetGeocodingCache :exec
INSERT INTO geocoding_cache (
    tenant_id, lat_round, lng_round,
    address, raw_json, expires_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (tenant_id, lat_round, lng_round) DO UPDATE SET
    address = EXCLUDED.address,
    raw_json = EXCLUDED.raw_json,
    expires_at = EXCLUDED.expires_at
`

type SetGeocodingCacheParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	LatRound  float64            `json:"lat_round"`
	LngRound  float64            `json:"lng_round"`
	Address   string             `json:"address"`
	RawJson   []byte             `json:"raw_json"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) SetGeocodingCache(ctx context.Context, arg SetGeocodingCacheParams) error {
	_, err := q.db.Exec(ctx, setGeocodingCache,
		arg.TenantID,
		arg.LatRound,
		arg.LngRound,
		arg.Address,
		arg.RawJson,
		arg.ExpiresAt,
	)
	return err
}
