// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: map_nodes.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPhotosByMapNode = `-- name: CountPhotosByMapNode :one
SELECT COUNT(*) FROM node_photos
WHERE map_node_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountPhotosByMapNode(ctx context.Context, mapNodeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPhotosByMapNode, mapNodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMapNode = `-- name: CreateMapNode :one

INSERT INTO map_nodes (
    tenant_id, node_type, reference_id,
    latitude, longitude, custom_fields
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
RETURNING id, tenant_id, node_type, reference_id,
    latitude, longitude, custom_fields,
    deleted_at, created_at, updated_at
`

type CreateMapNodeParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	NodeType     string      `json:"node_type"`
	ReferenceID  pgtype.UUID `json:"reference_id"`
	Latitude     float64     `json:"latitude"`
	Longitude    float64     `json:"longitude"`
	CustomFields []byte      `json:"custom_fields"`
}

// Kueri SQL untuk operasi CRUD tabel map_nodes.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel map_nodes dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// kecuali kueri yang secara eksplisit menangani trashed nodes.
func (q *Queries) CreateMapNode(ctx context.Context, arg CreateMapNodeParams) (MapNode, error) {
	row := q.db.QueryRow(ctx, createMapNode,
		arg.TenantID,
		arg.NodeType,
		arg.ReferenceID,
		arg.Latitude,
		arg.Longitude,
		arg.CustomFields,
	)
	var i MapNode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NodeType,
		&i.ReferenceID,
		&i.Latitude,
		&i.Longitude,
		&i.CustomFields,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMapNodeByID = `-- name: GetMapNodeByID :one
SELECT id, tenant_id, node_type, reference_id,
    latitude, longitude, custom_fields,
    deleted_at, created_at, updated_at
FROM map_nodes
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMapNodeByID(ctx context.Context, id pgtype.UUID) (MapNode, error) {
	row := q.db.QueryRow(ctx, getMapNodeByID, id)
	var i MapNode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NodeType,
		&i.ReferenceID,
		&i.Latitude,
		&i.Longitude,
		&i.CustomFields,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMapNodeByReference = `-- name: GetMapNodeByReference :one
SELECT id, tenant_id, node_type, reference_id,
    latitude, longitude, custom_fields,
    deleted_at, created_at, updated_at
FROM map_nodes
WHERE tenant_id = $1 AND node_type = $2 AND reference_id = $3 AND deleted_at IS NULL
`

type GetMapNodeByReferenceParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	NodeType    string      `json:"node_type"`
	ReferenceID pgtype.UUID `json:"reference_id"`
}

func (q *Queries) GetMapNodeByReference(ctx context.Context, arg GetMapNodeByReferenceParams) (MapNode, error) {
	row := q.db.QueryRow(ctx, getMapNodeByReference, arg.TenantID, arg.NodeType, arg.ReferenceID)
	var i MapNode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NodeType,
		&i.ReferenceID,
		&i.Latitude,
		&i.Longitude,
		&i.CustomFields,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMapNodesByBounds = `-- name: ListMapNodesByBounds :many
SELECT mn.id, mn.tenant_id, mn.node_type, mn.reference_id,
    mn.latitude, mn.longitude, mn.custom_fields,
    mn.created_at, mn.updated_at,
    COALESCE(o.name, odp.name, '') AS name,
    COALESCE(o.status, ont.status, '') AS status,
    ont.serial_number,
    odp.splitter_type,
    odp.capacity,
    odp.used_ports,
    odp.address
FROM map_nodes mn
LEFT JOIN olts o ON mn.node_type = 'olt' AND mn.reference_id = o.id
LEFT JOIN odps odp ON mn.node_type = 'odp' AND mn.reference_id = odp.id
LEFT JOIN onts ont ON mn.node_type = 'ont' AND mn.reference_id = ont.id
WHERE mn.deleted_at IS NULL
  AND mn.latitude BETWEEN $1 AND $2
  AND mn.longitude BETWEEN $3 AND $4
  AND ($5::varchar IS NULL OR mn.node_type = $5::varchar)
ORDER BY mn.created_at DESC
`

type ListMapNodesByBoundsParams struct {
	Latitude    float64     `json:"latitude"`
	Latitude_2  float64     `json:"latitude_2"`
	Longitude   float64     `json:"longitude"`
	Longitude_2 float64     `json:"longitude_2"`
	NodeType    pgtype.Text `json:"node_type"`
}

type ListMapNodesByBoundsRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	NodeType     string             `json:"node_type"`
	ReferenceID  pgtype.UUID        `json:"reference_id"`
	Latitude     float64            `json:"latitude"`
	Longitude    float64            `json:"longitude"`
	CustomFields []byte             `json:"custom_fields"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	SerialNumber pgtype.Text        `json:"serial_number"`
	SplitterType pgtype.Text        `json:"splitter_type"`
	Capacity     pgtype.Int4        `json:"capacity"`
	UsedPorts    pgtype.Int4        `json:"used_ports"`
	Address      pgtype.Text        `json:"address"`
}

func (q *Queries) ListMapNodesByBounds(ctx context.Context, arg ListMapNodesByBoundsParams) ([]ListMapNodesByBoundsRow, error) {
	rows, err := q.db.Query(ctx, listMapNodesByBounds,
		arg.Latitude,
		arg.Latitude_2,
		arg.Longitude,
		arg.Longitude_2,
		arg.NodeType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMapNodesByBoundsRow{}
	for rows.Next() {
		var i ListMapNodesByBoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NodeType,
			&i.ReferenceID,
			&i.Latitude,
			&i.Longitude,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Status,
			&i.SerialNumber,
			&i.SplitterType,
			&i.Capacity,
			&i.UsedPorts,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedMapNodes = `-- name: ListTrashedMapNodes :many
SELECT id, tenant_id, node_type, reference_id,
    latitude, longitude, custom_fields,
    deleted_at, created_at, updated_at
FROM map_nodes
WHERE deleted_at IS NOT NULL AND tenant_id = $1
ORDER BY deleted_at DESC
`

func (q *Queries) ListTrashedMapNodes(ctx context.Context, tenantID pgtype.UUID) ([]MapNode, error) {
	rows, err := q.db.Query(ctx, listTrashedMapNodes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapNode{}
	for rows.Next() {
		var i MapNode
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NodeType,
			&i.ReferenceID,
			&i.Latitude,
			&i.Longitude,
			&i.CustomFields,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentDeleteExpiredMapNodes = `-- name: PermanentDeleteExpiredMapNodes :execrows
DELETE FROM map_nodes
WHERE deleted_at IS NOT NULL AND deleted_at < $1
`

func (q *Queries) PermanentDeleteExpiredMapNodes(ctx context.Context, deletedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, permanentDeleteExpiredMapNodes, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreMapNode = `-- name: RestoreMapNode :exec
UPDATE map_nodes SET deleted_at = NULL, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreMapNode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreMapNode, id)
	return err
}

const searchMapNodes = `-- name: SearchMapNodes :many
SELECT mn.id, mn.tenant_id, mn.node_type, mn.reference_id,
    mn.latitude, mn.longitude, mn.custom_fields,
    mn.created_at, mn.updated_at,
    COALESCE(o.name, odp.name, '') AS name,
    COALESCE(o.status, ont.status, '') AS status,
    ont.serial_number,
    odp.splitter_type,
    odp.capacity,
    odp.used_ports,
    odp.address
FROM map_nodes mn
LEFT JOIN olts o ON mn.node_type = 'olt' AND mn.reference_id = o.id
LEFT JOIN odps odp ON mn.node_type = 'odp' AND mn.reference_id = odp.id
LEFT JOIN onts ont ON mn.node_type = 'ont' AND mn.reference_id = ont.id
WHERE mn.deleted_at IS NULL
  AND mn.tenant_id = $1
  AND (
    o.name ILIKE '%' || $2 || '%'
    OR odp.name ILIKE '%' || $2 || '%'
    OR odp.address ILIKE '%' || $2 || '%'
    OR ont.serial_number ILIKE '%' || $2 || '%'
  )
ORDER BY mn.created_at DESC
LIMIT $3
`

type SearchMapNodesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  pgtype.Text `json:"column_2"`
	Limit    int32       `json:"limit"`
}

type SearchMapNodesRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	NodeType     string             `json:"node_type"`
	ReferenceID  pgtype.UUID        `json:"reference_id"`
	Latitude     float64            `json:"latitude"`
	Longitude    float64            `json:"longitude"`
	CustomFields []byte             `json:"custom_fields"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	SerialNumber pgtype.Text        `json:"serial_number"`
	SplitterType pgtype.Text        `json:"splitter_type"`
	Capacity     pgtype.Int4        `json:"capacity"`
	UsedPorts    pgtype.Int4        `json:"used_ports"`
	Address      pgtype.Text        `json:"address"`
}

func (q *Queries) SearchMapNodes(ctx context.Context, arg SearchMapNodesParams) ([]SearchMapNodesRow, error) {
	rows, err := q.db.Query(ctx, searchMapNodes, arg.TenantID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMapNodesRow{}
	for rows.Next() {
		var i SearchMapNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NodeType,
			&i.ReferenceID,
			&i.Latitude,
			&i.Longitude,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Status,
			&i.SerialNumber,
			&i.SplitterType,
			&i.Capacity,
			&i.UsedPorts,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMapNode = `-- name: SoftDeleteMapNode :exec
UPDATE map_nodes SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMapNode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteMapNode, id)
	return err
}

const updateMapNode = `-- name: UpdateMapNode :one
UPDATE map_nodes SET
    latitude = $2,
    longitude = $3,
    custom_fields = $4,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, node_type, reference_id,
    latitude, longitude, custom_fields,
    deleted_at, created_at, updated_at
`

type UpdateMapNodeParams struct {
	ID           pgtype.UUID `json:"id"`
	Latitude     float64     `json:"latitude"`
	Longitude    float64     `json:"longitude"`
	CustomFields []byte      `json:"custom_fields"`
}

func (q *Queries) UpdateMapNode(ctx context.Context, arg UpdateMapNodeParams) (MapNode, error) {
	row := q.db.QueryRow(ctx, updateMapNode,
		arg.ID,
		arg.Latitude,
		arg.Longitude,
		arg.CustomFields,
	)
	var i MapNode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NodeType,
		&i.ReferenceID,
		&i.Latitude,
		&i.Longitude,
		&i.CustomFields,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
