// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: map_label_settings.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMapLabelSettingsByTenantID = `-- name: GetMapLabelSettingsByTenantID :one

SELECT id, tenant_id, olt_labels, odp_labels, ont_labels,
    min_zoom_level, created_at, updated_at
FROM map_label_settings
WHERE tenant_id = $1
`

// Kueri SQL untuk operasi pada tabel map_label_settings.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel map_label_settings dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Setiap tenant memiliki satu record settings (UNIQUE tenant_id).
func (q *Queries) GetMapLabelSettingsByTenantID(ctx context.Context, tenantID pgtype.UUID) (MapLabelSetting, error) {
	row := q.db.QueryRow(ctx, getMapLabelSettingsByTenantID, tenantID)
	var i MapLabelSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OltLabels,
		&i.OdpLabels,
		&i.OntLabels,
		&i.MinZoomLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMapLabelSettings = `-- name: UpsertMapLabelSettings :one
INSERT INTO map_label_settings (
    tenant_id, olt_labels, odp_labels, ont_labels, min_zoom_level
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (tenant_id) DO UPDATE SET
    olt_labels = EXCLUDED.olt_labels,
    odp_labels = EXCLUDED.odp_labels,
    ont_labels = EXCLUDED.ont_labels,
    min_zoom_level = EXCLUDED.min_zoom_level,
    updated_at = NOW()
RETURNING id, tenant_id, olt_labels, odp_labels, ont_labels,
    min_zoom_level, created_at, updated_at
`

type UpsertMapLabelSettingsParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	OltLabels    []byte      `json:"olt_labels"`
	OdpLabels    []byte      `json:"odp_labels"`
	OntLabels    []byte      `json:"ont_labels"`
	MinZoomLevel int32       `json:"min_zoom_level"`
}

func (q *Queries) UpsertMapLabelSettings(ctx context.Context, arg UpsertMapLabelSettingsParams) (MapLabelSetting, error) {
	row := q.db.QueryRow(ctx, upsertMapLabelSettings,
		arg.TenantID,
		arg.OltLabels,
		arg.OdpLabels,
		arg.OntLabels,
		arg.MinZoomLevel,
	)
	var i MapLabelSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OltLabels,
		&i.OdpLabels,
		&i.OntLabels,
		&i.MinZoomLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
