// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: map_share_links.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMapShareLink = `-- name: CreateMapShareLink :one

INSERT INTO map_share_links (
    tenant_id, token, visible_layers,
    expires_at, password_hash, created_by
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
RETURNING id, tenant_id, token, visible_layers,
    expires_at, password_hash, access_count,
    created_by, created_at
`

type CreateMapShareLinkParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Token         string             `json:"token"`
	VisibleLayers []byte             `json:"visible_layers"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	CreatedBy     string             `json:"created_by"`
}

// Query SQL untuk operasi CRUD tabel map_share_links.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel map_share_links dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// GetMapShareLinkByToken tidak menggunakan RLS karena diakses secara publik via token.
func (q *Queries) CreateMapShareLink(ctx context.Context, arg CreateMapShareLinkParams) (MapShareLink, error) {
	row := q.db.QueryRow(ctx, createMapShareLink,
		arg.TenantID,
		arg.Token,
		arg.VisibleLayers,
		arg.ExpiresAt,
		arg.PasswordHash,
		arg.CreatedBy,
	)
	var i MapShareLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Token,
		&i.VisibleLayers,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.AccessCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMapShareLink = `-- name: DeleteMapShareLink :exec
DELETE FROM map_share_links
WHERE token = $1
`

func (q *Queries) DeleteMapShareLink(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteMapShareLink, token)
	return err
}

const getMapShareLinkByToken = `-- name: GetMapShareLinkByToken :one
SELECT id, tenant_id, token, visible_layers,
    expires_at, password_hash, access_count,
    created_by, created_at
FROM map_share_links
WHERE token = $1
`

func (q *Queries) GetMapShareLinkByToken(ctx context.Context, token string) (MapShareLink, error) {
	row := q.db.QueryRow(ctx, getMapShareLinkByToken, token)
	var i MapShareLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Token,
		&i.VisibleLayers,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.AccessCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const incrementShareLinkAccessCount = `-- name: IncrementShareLinkAccessCount :exec
UPDATE map_share_links SET access_count = access_count + 1
WHERE token = $1
`

func (q *Queries) IncrementShareLinkAccessCount(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, incrementShareLinkAccessCount, token)
	return err
}

const listMapShareLinksByTenant = `-- name: ListMapShareLinksByTenant :many
SELECT id, tenant_id, token, visible_layers,
    expires_at, password_hash, access_count,
    created_by, created_at
FROM map_share_links
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMapShareLinksByTenant(ctx context.Context, tenantID pgtype.UUID) ([]MapShareLink, error) {
	rows, err := q.db.Query(ctx, listMapShareLinksByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapShareLink{}
	for rows.Next() {
		var i MapShareLink
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Token,
			&i.VisibleLayers,
			&i.ExpiresAt,
			&i.PasswordHash,
			&i.AccessCount,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
