// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: map_change_history.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMapChangeHistory = `-- name: CreateMapChangeHistory :one

INSERT INTO map_change_history (
    tenant_id, map_node_id, action,
    old_value, new_value, performed_by
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
RETURNING id, tenant_id, map_node_id, action,
    old_value, new_value, performed_by, created_at
`

type CreateMapChangeHistoryParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	MapNodeID   pgtype.UUID `json:"map_node_id"`
	Action      string      `json:"action"`
	OldValue    []byte      `json:"old_value"`
	NewValue    []byte      `json:"new_value"`
	PerformedBy string      `json:"performed_by"`
}

// Kueri SQL untuk operasi pada tabel map_change_history.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel map_change_history dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Tabel ini bersifat append-only: hanya INSERT dan SELECT, tidak ada UPDATE atau DELETE.
func (q *Queries) CreateMapChangeHistory(ctx context.Context, arg CreateMapChangeHistoryParams) (MapChangeHistory, error) {
	row := q.db.QueryRow(ctx, createMapChangeHistory,
		arg.TenantID,
		arg.MapNodeID,
		arg.Action,
		arg.OldValue,
		arg.NewValue,
		arg.PerformedBy,
	)
	var i MapChangeHistory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MapNodeID,
		&i.Action,
		&i.OldValue,
		&i.NewValue,
		&i.PerformedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listMapChangeHistoryByNode = `-- name: ListMapChangeHistoryByNode :many
SELECT id, tenant_id, map_node_id, action,
    old_value, new_value, performed_by, created_at
FROM map_change_history
WHERE map_node_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMapChangeHistoryByNodeParams struct {
	MapNodeID pgtype.UUID `json:"map_node_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListMapChangeHistoryByNode(ctx context.Context, arg ListMapChangeHistoryByNodeParams) ([]MapChangeHistory, error) {
	rows, err := q.db.Query(ctx, listMapChangeHistoryByNode, arg.MapNodeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapChangeHistory{}
	for rows.Next() {
		var i MapChangeHistory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MapNodeID,
			&i.Action,
			&i.OldValue,
			&i.NewValue,
			&i.PerformedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
