// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mikrotik_command_audit_logs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMikroTikCommandAuditLog = `-- name: CreateMikroTikCommandAuditLog :exec

INSERT INTO mikrotik_command_audit_logs (
    tenant_id, router_id, user_id, action, command,
    target_type, target_id, status, error_message, remote_addr
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
`

type CreateMikroTikCommandAuditLogParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	RouterID     pgtype.UUID `json:"router_id"`
	UserID       pgtype.UUID `json:"user_id"`
	Action       string      `json:"action"`
	Command      string      `json:"command"`
	TargetType   pgtype.Text `json:"target_type"`
	TargetID     pgtype.Text `json:"target_id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	RemoteAddr   pgtype.Text `json:"remote_addr"`
}

// Query SQL untuk audit command MikroTik.
func (q *Queries) CreateMikroTikCommandAuditLog(ctx context.Context, arg CreateMikroTikCommandAuditLogParams) error {
	_, err := q.db.Exec(ctx, createMikroTikCommandAuditLog,
		arg.TenantID,
		arg.RouterID,
		arg.UserID,
		arg.Action,
		arg.Command,
		arg.TargetType,
		arg.TargetID,
		arg.Status,
		arg.ErrorMessage,
		arg.RemoteAddr,
	)
	return err
}
