// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type CableRoute struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	FromNodeID     pgtype.UUID        `json:"from_node_id"`
	ToNodeID       pgtype.UUID        `json:"to_node_id"`
	RouteType      string             `json:"route_type"`
	Coordinates    []byte             `json:"coordinates"`
	DistanceMeters float64            `json:"distance_meters"`
	CoreCount      pgtype.Int4        `json:"core_count"`
	Description    pgtype.Text        `json:"description"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DhcpBinding struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	RouterID      pgtype.UUID        `json:"router_id"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	RouterLeaseID pgtype.Text        `json:"router_lease_id"`
	Server        string             `json:"server"`
	MacAddress    string             `json:"mac_address"`
	IpAddress     netip.Addr         `json:"ip_address"`
	HostName      pgtype.Text        `json:"host_name"`
	Comment       string             `json:"comment"`
	Disabled      bool               `json:"disabled"`
	Status        string             `json:"status"`
	LastSyncAt    pgtype.Timestamptz `json:"last_sync_at"`
	SyncStatus    string             `json:"sync_status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type GeocodingCache struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	LatRound  float64            `json:"lat_round"`
	LngRound  float64            `json:"lng_round"`
	Address   string             `json:"address"`
	RawJson   []byte             `json:"raw_json"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MapChangeHistory struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	MapNodeID   pgtype.UUID        `json:"map_node_id"`
	Action      string             `json:"action"`
	OldValue    []byte             `json:"old_value"`
	NewValue    []byte             `json:"new_value"`
	PerformedBy string             `json:"performed_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MapLabelSetting struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	OltLabels    []byte             `json:"olt_labels"`
	OdpLabels    []byte             `json:"odp_labels"`
	OntLabels    []byte             `json:"ont_labels"`
	MinZoomLevel int32              `json:"min_zoom_level"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type MapNode struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	NodeType     string             `json:"node_type"`
	ReferenceID  pgtype.UUID        `json:"reference_id"`
	Latitude     float64            `json:"latitude"`
	Longitude    float64            `json:"longitude"`
	CustomFields []byte             `json:"custom_fields"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type MapShareLink struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Token         string             `json:"token"`
	VisibleLayers []byte             `json:"visible_layers"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	AccessCount   int32              `json:"access_count"`
	CreatedBy     string             `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type MikrotikCommandAuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	RouterID     pgtype.UUID        `json:"router_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Action       string             `json:"action"`
	Command      string             `json:"command"`
	TargetType   pgtype.Text        `json:"target_type"`
	TargetID     pgtype.Text        `json:"target_id"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	RemoteAddr   pgtype.Text        `json:"remote_addr"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type NodePhoto struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	MapNodeID     pgtype.UUID        `json:"map_node_id"`
	FilePath      string             `json:"file_path"`
	FileSizeBytes int32              `json:"file_size_bytes"`
	Caption       pgtype.Text        `json:"caption"`
	UploadedBy    string             `json:"uploaded_by"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Odp struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	OltID        pgtype.UUID        `json:"olt_id"`
	PonPortIndex int32              `json:"pon_port_index"`
	Name         string             `json:"name"`
	SplitterType string             `json:"splitter_type"`
	Capacity     int32              `json:"capacity"`
	UsedPorts    int32              `json:"used_ports"`
	Address      pgtype.Text        `json:"address"`
	Latitude     pgtype.Numeric     `json:"latitude"`
	Longitude    pgtype.Numeric     `json:"longitude"`
	Notes        pgtype.Text        `json:"notes"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Olt struct {
	ID                         pgtype.UUID        `json:"id"`
	TenantID                   pgtype.UUID        `json:"tenant_id"`
	Name                       string             `json:"name"`
	Host                       string             `json:"host"`
	SnmpVersion                string             `json:"snmp_version"`
	SnmpPort                   int32              `json:"snmp_port"`
	SnmpCommunityEncrypted     pgtype.Text        `json:"snmp_community_encrypted"`
	SnmpUsername               pgtype.Text        `json:"snmp_username"`
	SnmpAuthProtocol           pgtype.Text        `json:"snmp_auth_protocol"`
	SnmpAuthPasswordEncrypted  pgtype.Text        `json:"snmp_auth_password_encrypted"`
	SnmpPrivProtocol           pgtype.Text        `json:"snmp_priv_protocol"`
	SnmpPrivPasswordEncrypted  pgtype.Text        `json:"snmp_priv_password_encrypted"`
	CliProtocol                string             `json:"cli_protocol"`
	CliPort                    int32              `json:"cli_port"`
	CliUsername                string             `json:"cli_username"`
	CliPasswordEncrypted       string             `json:"cli_password_encrypted"`
	CliEnablePasswordEncrypted pgtype.Text        `json:"cli_enable_password_encrypted"`
	Brand                      pgtype.Text        `json:"brand"`
	Model                      pgtype.Text        `json:"model"`
	FirmwareVersion            pgtype.Text        `json:"firmware_version"`
	PonPortCount               int32              `json:"pon_port_count"`
	TotalOntCount              int32              `json:"total_ont_count"`
	Status                     string             `json:"status"`
	HealthCheckIntervalSec     int32              `json:"health_check_interval_sec"`
	LastOnlineAt               pgtype.Timestamptz `json:"last_online_at"`
	LastCheckedAt              pgtype.Timestamptz `json:"last_checked_at"`
	FailureCount               int32              `json:"failure_count"`
	Notes                      pgtype.Text        `json:"notes"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type OltAlarm struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	OltID        pgtype.UUID        `json:"olt_id"`
	PonPortIndex pgtype.Int4        `json:"pon_port_index"`
	OntIndex     pgtype.Int4        `json:"ont_index"`
	AlarmType    string             `json:"alarm_type"`
	Severity     string             `json:"severity"`
	Message      pgtype.Text        `json:"message"`
	Source       string             `json:"source"`
	Status       string             `json:"status"`
	ClearedAt    pgtype.Timestamptz `json:"cleared_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Ont struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	OltID                pgtype.UUID        `json:"olt_id"`
	PonPortIndex         int32              `json:"pon_port_index"`
	OntIndex             int32              `json:"ont_index"`
	SerialNumber         string             `json:"serial_number"`
	CustomerID           pgtype.UUID        `json:"customer_id"`
	OdpID                pgtype.UUID        `json:"odp_id"`
	VlanID               pgtype.UUID        `json:"vlan_id"`
	ServiceProfileID     pgtype.UUID        `json:"service_profile_id"`
	Status               string             `json:"status"`
	ProvisioningState    string             `json:"provisioning_state"`
	Description          pgtype.Text        `json:"description"`
	LastProvisionedAt    pgtype.Timestamptz `json:"last_provisioned_at"`
	LastDecommissionedAt pgtype.Timestamptz `json:"last_decommissioned_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PppoeProfile struct {
	ID                     pgtype.UUID        `json:"id"`
	TenantID               pgtype.UUID        `json:"tenant_id"`
	PackageID              pgtype.UUID        `json:"package_id"`
	ProfileName            string             `json:"profile_name"`
	DownloadLimit          string             `json:"download_limit"`
	UploadLimit            string             `json:"upload_limit"`
	BurstDownload          pgtype.Text        `json:"burst_download"`
	BurstUpload            pgtype.Text        `json:"burst_upload"`
	BurstThresholdDownload pgtype.Text        `json:"burst_threshold_download"`
	BurstThresholdUpload   pgtype.Text        `json:"burst_threshold_upload"`
	BurstTime              pgtype.Text        `json:"burst_time"`
	AddressPool            pgtype.Text        `json:"address_pool"`
	LocalAddress           string             `json:"local_address"`
	OnlyOne                bool               `json:"only_one"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type PppoeUser struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	RouterID          pgtype.UUID        `json:"router_id"`
	Username          string             `json:"username"`
	PasswordEncrypted string             `json:"password_encrypted"`
	ProfileName       string             `json:"profile_name"`
	Service           string             `json:"service"`
	RemoteAddress     pgtype.Text        `json:"remote_address"`
	Comment           string             `json:"comment"`
	Disabled          bool               `json:"disabled"`
	UseSimpleQueue    bool               `json:"use_simple_queue"`
	Status            string             `json:"status"`
	LastSyncAt        pgtype.Timestamptz `json:"last_sync_at"`
	SyncStatus        string             `json:"sync_status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type ProvisioningAuditLog struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	OltID            pgtype.UUID        `json:"olt_id"`
	OntID            pgtype.UUID        `json:"ont_id"`
	Action           string             `json:"action"`
	CommandsSent     []byte             `json:"commands_sent"`
	CommandResponses []byte             `json:"command_responses"`
	Status           string             `json:"status"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	PerformedBy      string             `json:"performed_by"`
	Brand            pgtype.Text        `json:"brand"`
	Model            pgtype.Text        `json:"model"`
	Transport        pgtype.Text        `json:"transport"`
	Operation        pgtype.Text        `json:"operation"`
	CorrelationID    pgtype.UUID        `json:"correlation_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ProvisioningSetting struct {
	ID                       pgtype.UUID        `json:"id"`
	TenantID                 pgtype.UUID        `json:"tenant_id"`
	AutoProvisioningEnabled  bool               `json:"auto_provisioning_enabled"`
	AutoPortMigrationEnabled bool               `json:"auto_port_migration_enabled"`
	VlanStrategy             string             `json:"vlan_strategy"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type Router struct {
	ID                     pgtype.UUID        `json:"id"`
	TenantID               pgtype.UUID        `json:"tenant_id"`
	Name                   string             `json:"name"`
	Host                   string             `json:"host"`
	Port                   int32              `json:"port"`
	Username               string             `json:"username"`
	PasswordEncrypted      string             `json:"password_encrypted"`
	UseSsl                 bool               `json:"use_ssl"`
	ServiceTypes           []byte             `json:"service_types"`
	RouterOsVersion        pgtype.Text        `json:"router_os_version"`
	BoardName              pgtype.Text        `json:"board_name"`
	CpuCount               pgtype.Int4        `json:"cpu_count"`
	TotalRamMb             pgtype.Int4        `json:"total_ram_mb"`
	Identity               pgtype.Text        `json:"identity"`
	Status                 string             `json:"status"`
	HealthCheckIntervalSec int32              `json:"health_check_interval_sec"`
	LastOnlineAt           pgtype.Timestamptz `json:"last_online_at"`
	LastCheckedAt          pgtype.Timestamptz `json:"last_checked_at"`
	LastUptimeSec          pgtype.Int8        `json:"last_uptime_sec"`
	FailureCount           int32              `json:"failure_count"`
	Notes                  pgtype.Text        `json:"notes"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type ServiceProfile struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	OltID            pgtype.UUID        `json:"olt_id"`
	Name             string             `json:"name"`
	LineProfileID    int32              `json:"line_profile_id"`
	ServiceProfileID int32              `json:"service_profile_id"`
	PackageID        pgtype.UUID        `json:"package_id"`
	Description      pgtype.Text        `json:"description"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type StaticIpAssignment struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	RouterID    pgtype.UUID        `json:"router_id"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	IpAddress   netip.Addr         `json:"ip_address"`
	AddressList string             `json:"address_list"`
	QueueName   pgtype.Text        `json:"queue_name"`
	RateLimit   pgtype.Text        `json:"rate_limit"`
	Comment     string             `json:"comment"`
	Status      string             `json:"status"`
	LastSyncAt  pgtype.Timestamptz `json:"last_sync_at"`
	SyncStatus  string             `json:"sync_status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Domain    pgtype.Text        `json:"domain"`
	Plan      string             `json:"plan"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Vlan struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	OltID       pgtype.UUID        `json:"olt_id"`
	VlanID      int32              `json:"vlan_id"`
	Name        string             `json:"name"`
	VlanType    string             `json:"vlan_type"`
	Description pgtype.Text        `json:"description"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type VpnMaintenanceWindow struct {
	ID             pgtype.UUID        `json:"id"`
	ServerEndpoint string             `json:"server_endpoint"`
	ScheduledStart pgtype.Timestamptz `json:"scheduled_start"`
	ScheduledEnd   pgtype.Timestamptz `json:"scheduled_end"`
	Description    pgtype.Text        `json:"description"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type VpnSubnet struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	SubnetPrefix    string             `json:"subnet_prefix"`
	TenantSeq       int32              `json:"tenant_seq"`
	ServerIp        string             `json:"server_ip"`
	NextClientIpSeq int32              `json:"next_client_ip_seq"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type VpnTunnel struct {
	ID                        pgtype.UUID        `json:"id"`
	TenantID                  pgtype.UUID        `json:"tenant_id"`
	RouterID                  pgtype.UUID        `json:"router_id"`
	TunnelName                string             `json:"tunnel_name"`
	Protocol                  string             `json:"protocol"`
	VpnIp                     string             `json:"vpn_ip"`
	ServerEndpoint            string             `json:"server_endpoint"`
	ServerPublicKey           pgtype.Text        `json:"server_public_key"`
	ClientPublicKey           pgtype.Text        `json:"client_public_key"`
	ClientPrivateKeyEncrypted pgtype.Text        `json:"client_private_key_encrypted"`
	PreSharedKeyEncrypted     pgtype.Text        `json:"pre_shared_key_encrypted"`
	L2tpUsername              pgtype.Text        `json:"l2tp_username"`
	L2tpPasswordEncrypted     pgtype.Text        `json:"l2tp_password_encrypted"`
	Status                    string             `json:"status"`
	ListenPort                int32              `json:"listen_port"`
	AllowedAddresses          string             `json:"allowed_addresses"`
	PersistentKeepalive       int32              `json:"persistent_keepalive"`
	LastHandshakeAt           pgtype.Timestamptz `json:"last_handshake_at"`
	LatencyMs                 pgtype.Int4        `json:"latency_ms"`
	BandwidthCapMbps          pgtype.Int4        `json:"bandwidth_cap_mbps"`
	RateLimitPps              int32              `json:"rate_limit_pps"`
	ActiveEndpoint            pgtype.Text        `json:"active_endpoint"`
	Notes                     pgtype.Text        `json:"notes"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
}
