// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_photos.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNodePhotosByNode = `-- name: CountNodePhotosByNode :one
SELECT COUNT(*) FROM node_photos
WHERE map_node_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountNodePhotosByNode(ctx context.Context, mapNodeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNodePhotosByNode, mapNodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNodePhoto = `-- name: CreateNodePhoto :one

INSERT INTO node_photos (
    tenant_id, map_node_id, file_path,
    file_size_bytes, caption, uploaded_by
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
RETURNING id, tenant_id, map_node_id, file_path,
    file_size_bytes, caption, uploaded_by,
    deleted_at, created_at
`

type CreateNodePhotoParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	MapNodeID     pgtype.UUID `json:"map_node_id"`
	FilePath      string      `json:"file_path"`
	FileSizeBytes int32       `json:"file_size_bytes"`
	Caption       pgtype.Text `json:"caption"`
	UploadedBy    string      `json:"uploaded_by"`
}

// Query SQL untuk operasi CRUD tabel node_photos.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel node_photos dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Semua query menyertakan WHERE deleted_at IS NULL untuk mengecualikan soft-deleted.
func (q *Queries) CreateNodePhoto(ctx context.Context, arg CreateNodePhotoParams) (NodePhoto, error) {
	row := q.db.QueryRow(ctx, createNodePhoto,
		arg.TenantID,
		arg.MapNodeID,
		arg.FilePath,
		arg.FileSizeBytes,
		arg.Caption,
		arg.UploadedBy,
	)
	var i NodePhoto
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MapNodeID,
		&i.FilePath,
		&i.FileSizeBytes,
		&i.Caption,
		&i.UploadedBy,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNodePhotosByNode = `-- name: ListNodePhotosByNode :many
SELECT id, tenant_id, map_node_id, file_path,
    file_size_bytes, caption, uploaded_by,
    deleted_at, created_at
FROM node_photos
WHERE map_node_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListNodePhotosByNode(ctx context.Context, mapNodeID pgtype.UUID) ([]NodePhoto, error) {
	rows, err := q.db.Query(ctx, listNodePhotosByNode, mapNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodePhoto{}
	for rows.Next() {
		var i NodePhoto
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MapNodeID,
			&i.FilePath,
			&i.FileSizeBytes,
			&i.Caption,
			&i.UploadedBy,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNodePhoto = `-- name: SoftDeleteNodePhoto :exec
UPDATE node_photos SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteNodePhoto(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteNodePhoto, id)
	return err
}
