// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: odps.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countODPs = `-- name: CountODPs :one
SELECT COUNT(*) FROM odps
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR olt_id = $1::uuid)
  AND ($2::integer IS NULL OR pon_port_index = $2::integer)
`

type CountODPsParams struct {
	OltID        pgtype.UUID `json:"olt_id"`
	PonPortIndex pgtype.Int4 `json:"pon_port_index"`
}

func (q *Queries) CountODPs(ctx context.Context, arg CountODPsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countODPs, arg.OltID, arg.PonPortIndex)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createODP = `-- name: CreateODP :one

INSERT INTO odps (
    tenant_id, olt_id, pon_port_index, name, splitter_type,
    capacity, used_ports, address, latitude, longitude, notes
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
)
RETURNING id, tenant_id, olt_id, pon_port_index, name, splitter_type,
    capacity, used_ports, address, latitude, longitude, notes,
    deleted_at, created_at, updated_at
`

type CreateODPParams struct {
	TenantID     pgtype.UUID    `json:"tenant_id"`
	OltID        pgtype.UUID    `json:"olt_id"`
	PonPortIndex int32          `json:"pon_port_index"`
	Name         string         `json:"name"`
	SplitterType string         `json:"splitter_type"`
	Capacity     int32          `json:"capacity"`
	UsedPorts    int32          `json:"used_ports"`
	Address      pgtype.Text    `json:"address"`
	Latitude     pgtype.Numeric `json:"latitude"`
	Longitude    pgtype.Numeric `json:"longitude"`
	Notes        pgtype.Text    `json:"notes"`
}

// Kueri SQL untuk operasi CRUD tabel odps.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel odps dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
func (q *Queries) CreateODP(ctx context.Context, arg CreateODPParams) (Odp, error) {
	row := q.db.QueryRow(ctx, createODP,
		arg.TenantID,
		arg.OltID,
		arg.PonPortIndex,
		arg.Name,
		arg.SplitterType,
		arg.Capacity,
		arg.UsedPorts,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Notes,
	)
	var i Odp
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OltID,
		&i.PonPortIndex,
		&i.Name,
		&i.SplitterType,
		&i.Capacity,
		&i.UsedPorts,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getODPByID = `-- name: GetODPByID :one
SELECT id, tenant_id, olt_id, pon_port_index, name, splitter_type,
    capacity, used_ports, address, latitude, longitude, notes,
    deleted_at, created_at, updated_at
FROM odps
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetODPByID(ctx context.Context, id pgtype.UUID) (Odp, error) {
	row := q.db.QueryRow(ctx, getODPByID, id)
	var i Odp
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OltID,
		&i.PonPortIndex,
		&i.Name,
		&i.SplitterType,
		&i.Capacity,
		&i.UsedPorts,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getODPsByOLTAndPort = `-- name: GetODPsByOLTAndPort :many
SELECT id, tenant_id, olt_id, pon_port_index, name, splitter_type,
    capacity, used_ports, address, latitude, longitude, notes,
    deleted_at, created_at, updated_at
FROM odps
WHERE olt_id = $1 AND pon_port_index = $2 AND deleted_at IS NULL
ORDER BY name ASC
`

type GetODPsByOLTAndPortParams struct {
	OltID        pgtype.UUID `json:"olt_id"`
	PonPortIndex int32       `json:"pon_port_index"`
}

func (q *Queries) GetODPsByOLTAndPort(ctx context.Context, arg GetODPsByOLTAndPortParams) ([]Odp, error) {
	rows, err := q.db.Query(ctx, getODPsByOLTAndPort, arg.OltID, arg.PonPortIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Odp{}
	for rows.Next() {
		var i Odp
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OltID,
			&i.PonPortIndex,
			&i.Name,
			&i.SplitterType,
			&i.Capacity,
			&i.UsedPorts,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Notes,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listODPs = `-- name: ListODPs :many
SELECT id, tenant_id, olt_id, pon_port_index, name, splitter_type,
    capacity, used_ports, address, latitude, longitude, notes,
    deleted_at, created_at, updated_at
FROM odps
WHERE deleted_at IS NULL
  AND ($3::uuid IS NULL OR olt_id = $3::uuid)
  AND ($4::integer IS NULL OR pon_port_index = $4::integer)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListODPsParams struct {
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	OltID        pgtype.UUID `json:"olt_id"`
	PonPortIndex pgtype.Int4 `json:"pon_port_index"`
}

func (q *Queries) ListODPs(ctx context.Context, arg ListODPsParams) ([]Odp, error) {
	rows, err := q.db.Query(ctx, listODPs,
		arg.Limit,
		arg.Offset,
		arg.OltID,
		arg.PonPortIndex,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Odp{}
	for rows.Next() {
		var i Odp
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OltID,
			&i.PonPortIndex,
			&i.Name,
			&i.SplitterType,
			&i.Capacity,
			&i.UsedPorts,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Notes,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oDPNameExists = `-- name: ODPNameExists :one
SELECT EXISTS(
    SELECT 1 FROM odps
    WHERE tenant_id = $1 AND name = $2 AND id != $3 AND deleted_at IS NULL
) AS exists
`

type ODPNameExistsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) ODPNameExists(ctx context.Context, arg ODPNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, oDPNameExists, arg.TenantID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteODP = `-- name: SoftDeleteODP :exec
UPDATE odps SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteODP(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteODP, id)
	return err
}

const updateODP = `-- name: UpdateODP :one
UPDATE odps SET
    name = $2,
    address = $3,
    latitude = $4,
    longitude = $5,
    notes = $6,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, olt_id, pon_port_index, name, splitter_type,
    capacity, used_ports, address, latitude, longitude, notes,
    deleted_at, created_at, updated_at
`

type UpdateODPParams struct {
	ID        pgtype.UUID    `json:"id"`
	Name      string         `json:"name"`
	Address   pgtype.Text    `json:"address"`
	Latitude  pgtype.Numeric `json:"latitude"`
	Longitude pgtype.Numeric `json:"longitude"`
	Notes     pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateODP(ctx context.Context, arg UpdateODPParams) (Odp, error) {
	row := q.db.QueryRow(ctx, updateODP,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Notes,
	)
	var i Odp
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OltID,
		&i.PonPortIndex,
		&i.Name,
		&i.SplitterType,
		&i.Capacity,
		&i.UsedPorts,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
