// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: olt_alarms.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearOLTAlarm = `-- name: ClearOLTAlarm :exec
UPDATE olt_alarms SET
    status = 'cleared',
    cleared_at = NOW()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) ClearOLTAlarm(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearOLTAlarm, id)
	return err
}

const countActiveAlarms = `-- name: CountActiveAlarms :one
SELECT COUNT(*) FROM olt_alarms
WHERE olt_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveAlarms(ctx context.Context, oltID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAlarms, oltID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveAlarmsByTenant = `-- name: CountActiveAlarmsByTenant :one
SELECT COUNT(*) FROM olt_alarms
WHERE status = 'active'
`

func (q *Queries) CountActiveAlarmsByTenant(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAlarmsByTenant)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOLTAlarms = `-- name: CountOLTAlarms :one
SELECT COUNT(*) FROM olt_alarms
WHERE olt_id = $1
  AND ($2::varchar IS NULL OR severity = $2::varchar)
  AND ($3::varchar IS NULL OR status = $3::varchar)
`

type CountOLTAlarmsParams struct {
	OltID    pgtype.UUID `json:"olt_id"`
	Severity pgtype.Text `json:"severity"`
	Status   pgtype.Text `json:"status"`
}

func (q *Queries) CountOLTAlarms(ctx context.Context, arg CountOLTAlarmsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOLTAlarms, arg.OltID, arg.Severity, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOLTAlarm = `-- name: CreateOLTAlarm :one

INSERT INTO olt_alarms (
    tenant_id, olt_id, pon_port_index, ont_index,
    alarm_type, severity, message, source, status
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9
)
RETURNING id, tenant_id, olt_id, pon_port_index, ont_index,
    alarm_type, severity, message, source, status,
    cleared_at, created_at
`

type CreateOLTAlarmParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	OltID        pgtype.UUID `json:"olt_id"`
	PonPortIndex pgtype.Int4 `json:"pon_port_index"`
	OntIndex     pgtype.Int4 `json:"ont_index"`
	AlarmType    string      `json:"alarm_type"`
	Severity     string      `json:"severity"`
	Message      pgtype.Text `json:"message"`
	Source       string      `json:"source"`
	Status       string      `json:"status"`
}

// Kueri SQL untuk operasi CRUD tabel olt_alarms.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel olt_alarms dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
func (q *Queries) CreateOLTAlarm(ctx context.Context, arg CreateOLTAlarmParams) (OltAlarm, error) {
	row := q.db.QueryRow(ctx, createOLTAlarm,
		arg.TenantID,
		arg.OltID,
		arg.PonPortIndex,
		arg.OntIndex,
		arg.AlarmType,
		arg.Severity,
		arg.Message,
		arg.Source,
		arg.Status,
	)
	var i OltAlarm
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OltID,
		&i.PonPortIndex,
		&i.OntIndex,
		&i.AlarmType,
		&i.Severity,
		&i.Message,
		&i.Source,
		&i.Status,
		&i.ClearedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOLTAlarms = `-- name: ListOLTAlarms :many
SELECT id, tenant_id, olt_id, pon_port_index, ont_index,
    alarm_type, severity, message, source, status,
    cleared_at, created_at
FROM olt_alarms
WHERE olt_id = $1
  AND ($4::varchar IS NULL OR severity = $4::varchar)
  AND ($5::varchar IS NULL OR status = $5::varchar)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOLTAlarmsParams struct {
	OltID    pgtype.UUID `json:"olt_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Severity pgtype.Text `json:"severity"`
	Status   pgtype.Text `json:"status"`
}

func (q *Queries) ListOLTAlarms(ctx context.Context, arg ListOLTAlarmsParams) ([]OltAlarm, error) {
	rows, err := q.db.Query(ctx, listOLTAlarms,
		arg.OltID,
		arg.Limit,
		arg.Offset,
		arg.Severity,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OltAlarm{}
	for rows.Next() {
		var i OltAlarm
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OltID,
			&i.PonPortIndex,
			&i.OntIndex,
			&i.AlarmType,
			&i.Severity,
			&i.Message,
			&i.Source,
			&i.Status,
			&i.ClearedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOLTAlarms = `-- name: PurgeOLTAlarms :execrows
DELETE FROM olt_alarms
WHERE created_at < $1
`

func (q *Queries) PurgeOLTAlarms(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOLTAlarms, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
