// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: olts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOLTs = `-- name: CountOLTs :one
SELECT COUNT(*) FROM olts
WHERE deleted_at IS NULL
  AND ($1::varchar IS NULL OR status = $1::varchar)
  AND ($2::varchar IS NULL OR brand = $2::varchar)
  AND ($3::varchar IS NULL OR name ILIKE '%' || $3::varchar || '%' OR host ILIKE '%' || $3::varchar || '%')
`

type CountOLTsParams struct {
	Status pgtype.Text `json:"status"`
	Brand  pgtype.Text `json:"brand"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) CountOLTs(ctx context.Context, arg CountOLTsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOLTs, arg.Status, arg.Brand, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOLTsByStatus = `-- name: CountOLTsByStatus :many
SELECT status, COUNT(*) AS count
FROM olts
WHERE deleted_at IS NULL
GROUP BY status
`

type CountOLTsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountOLTsByStatus(ctx context.Context) ([]CountOLTsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countOLTsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOLTsByStatusRow{}
	for rows.Next() {
		var i CountOLTsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOLT = `-- name: CreateOLT :one

INSERT INTO olts (
    tenant_id, name, host, snmp_version, snmp_port,
    snmp_community_encrypted, snmp_username, snmp_auth_protocol,
    snmp_auth_password_encrypted, snmp_priv_protocol, snmp_priv_password_encrypted,
    cli_protocol, cli_port, cli_username, cli_password_encrypted,
    cli_enable_password_encrypted, brand, model, firmware_version,
    pon_port_count, total_ont_count, status,
    health_check_interval_sec, notes
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14, $15,
    $16, $17, $18, $19,
    $20, $21, $22,
    $23, $24
)
RETURNING id, tenant_id, name, host, snmp_version, snmp_port,
    snmp_community_encrypted, snmp_username, snmp_auth_protocol,
    snmp_auth_password_encrypted, snmp_priv_protocol, snmp_priv_password_encrypted,
    cli_protocol, cli_port, cli_username, cli_password_encrypted,
    cli_enable_password_encrypted, brand, model, firmware_version,
    pon_port_count, total_ont_count, status,
    health_check_interval_sec, last_online_at, last_checked_at,
    failure_count, notes, deleted_at, created_at, updated_at
`

type CreateOLTParams struct {
	TenantID                   pgtype.UUID `json:"tenant_id"`
	Name                       string      `json:"name"`
	Host                       string      `json:"host"`
	SnmpVersion                string      `json:"snmp_version"`
	SnmpPort                   int32       `json:"snmp_port"`
	SnmpCommunityEncrypted     pgtype.Text `json:"snmp_community_encrypted"`
	SnmpUsername               pgtype.Text `json:"snmp_username"`
	SnmpAuthProtocol           pgtype.Text `json:"snmp_auth_protocol"`
	SnmpAuthPasswordEncrypted  pgtype.Text `json:"snmp_auth_password_encrypted"`
	SnmpPrivProtocol           pgtype.Text `json:"snmp_priv_protocol"`
	SnmpPrivPasswordEncrypted  pgtype.Text `json:"snmp_priv_password_encrypted"`
	CliProtocol                string      `json:"cli_protocol"`
	CliPort                    int32       `json:"cli_port"`
	CliUsername                string      `json:"cli_username"`
	CliPasswordEncrypted       string      `json:"cli_password_encrypted"`
	CliEnablePasswordEncrypted pgtype.Text `json:"cli_enable_password_encrypted"`
	Brand                      pgtype.Text `json:"brand"`
	Model                      pgtype.Text `json:"model"`
	FirmwareVersion            pgtype.Text `json:"firmware_version"`
	PonPortCount               int32       `json:"pon_port_count"`
	TotalOntCount              int32       `json:"total_ont_count"`
	Status                     string      `json:"status"`
	HealthCheckIntervalSec     int32       `json:"health_check_interval_sec"`
	Notes                      pgtype.Text `json:"notes"`
}

// Query SQL untuk operasi CRUD tabel olts.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel olts dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Semua query menyertakan WHERE deleted_at IS NULL untuk mengecualikan soft-deleted.
func (q *Queries) CreateOLT(ctx context.Context, arg CreateOLTParams) (Olt, error) {
	row := q.db.QueryRow(ctx, createOLT,
		arg.TenantID,
		arg.Name,
		arg.Host,
		arg.SnmpVersion,
		arg.SnmpPort,
		arg.SnmpCommunityEncrypted,
		arg.SnmpUsername,
		arg.SnmpAuthProtocol,
		arg.SnmpAuthPasswordEncrypted,
		arg.SnmpPrivProtocol,
		arg.SnmpPrivPasswordEncrypted,
		arg.CliProtocol,
		arg.CliPort,
		arg.CliUsername,
		arg.CliPasswordEncrypted,
		arg.CliEnablePasswordEncrypted,
		arg.Brand,
		arg.Model,
		arg.FirmwareVersion,
		arg.PonPortCount,
		arg.TotalOntCount,
		arg.Status,
		arg.HealthCheckIntervalSec,
		arg.Notes,
	)
	var i Olt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Host,
		&i.SnmpVersion,
		&i.SnmpPort,
		&i.SnmpCommunityEncrypted,
		&i.SnmpUsername,
		&i.SnmpAuthProtocol,
		&i.SnmpAuthPasswordEncrypted,
		&i.SnmpPrivProtocol,
		&i.SnmpPrivPasswordEncrypted,
		&i.CliProtocol,
		&i.CliPort,
		&i.CliUsername,
		&i.CliPasswordEncrypted,
		&i.CliEnablePasswordEncrypted,
		&i.Brand,
		&i.Model,
		&i.FirmwareVersion,
		&i.PonPortCount,
		&i.TotalOntCount,
		&i.Status,
		&i.HealthCheckIntervalSec,
		&i.LastOnlineAt,
		&i.LastCheckedAt,
		&i.FailureCount,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveOLTs = `-- name: GetActiveOLTs :many
SELECT id, tenant_id, name, host, snmp_version, snmp_port,
    snmp_community_encrypted, snmp_username, snmp_auth_protocol,
    snmp_auth_password_encrypted, snmp_priv_protocol, snmp_priv_password_encrypted,
    cli_protocol, cli_port, cli_username, cli_password_encrypted,
    cli_enable_password_encrypted, brand, model, firmware_version,
    pon_port_count, total_ont_count, status,
    health_check_interval_sec, last_online_at, last_checked_at,
    failure_count, notes, deleted_at, created_at, updated_at
FROM olts
WHERE deleted_at IS NULL AND status != 'maintenance'
`

func (q *Queries) GetActiveOLTs(ctx context.Context) ([]Olt, error) {
	rows, err := q.db.Query(ctx, getActiveOLTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Olt{}
	for rows.Next() {
		var i Olt
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Host,
			&i.SnmpVersion,
			&i.SnmpPort,
			&i.SnmpCommunityEncrypted,
			&i.SnmpUsername,
			&i.SnmpAuthProtocol,
			&i.SnmpAuthPasswordEncrypted,
			&i.SnmpPrivProtocol,
			&i.SnmpPrivPasswordEncrypted,
			&i.CliProtocol,
			&i.CliPort,
			&i.CliUsername,
			&i.CliPasswordEncrypted,
			&i.CliEnablePasswordEncrypted,
			&i.Brand,
			&i.Model,
			&i.FirmwareVersion,
			&i.PonPortCount,
			&i.TotalOntCount,
			&i.Status,
			&i.HealthCheckIntervalSec,
			&i.LastOnlineAt,
			&i.LastCheckedAt,
			&i.FailureCount,
			&i.Notes,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOLTByID = `-- name: GetOLTByID :one
SELECT id, tenant_id, name, host, snmp_version, snmp_port,
    snmp_community_encrypted, snmp_username, snmp_auth_protocol,
    snmp_auth_password_encrypted, snmp_priv_protocol, snmp_priv_password_encrypted,
    cli_protocol, cli_port, cli_username, cli_password_encrypted,
    cli_enable_password_encrypted, brand, model, firmware_version,
    pon_port_count, total_ont_count, status,
    health_check_interval_sec, last_online_at, last_checked_at,
    failure_count, notes, deleted_at, created_at, updated_at
FROM olts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOLTByID(ctx context.Context, id pgtype.UUID) (Olt, error) {
	row := q.db.QueryRow(ctx, getOLTByID, id)
	var i Olt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Host,
		&i.SnmpVersion,
		&i.SnmpPort,
		&i.SnmpCommunityEncrypted,
		&i.SnmpUsername,
		&i.SnmpAuthProtocol,
		&i.SnmpAuthPasswordEncrypted,
		&i.SnmpPrivProtocol,
		&i.SnmpPrivPasswordEncrypted,
		&i.CliProtocol,
		&i.CliPort,
		&i.CliUsername,
		&i.CliPasswordEncrypted,
		&i.CliEnablePasswordEncrypted,
		&i.Brand,
		&i.Model,
		&i.FirmwareVersion,
		&i.PonPortCount,
		&i.TotalOntCount,
		&i.Status,
		&i.HealthCheckIntervalSec,
		&i.LastOnlineAt,
		&i.LastCheckedAt,
		&i.FailureCount,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOnlineOLTs = `-- name: GetOnlineOLTs :many
SELECT id, tenant_id, name, host, snmp_version, snmp_port,
    snmp_community_encrypted, snmp_username, snmp_auth_protocol,
    snmp_auth_password_encrypted, snmp_priv_protocol, snmp_priv_password_encrypted,
    cli_protocol, cli_port, cli_username, cli_password_encrypted,
    cli_enable_password_encrypted, brand, model, firmware_version,
    pon_port_count, total_ont_count, status,
    health_check_interval_sec, last_online_at, last_checked_at,
    failure_count, notes, deleted_at, created_at, updated_at
FROM olts
WHERE deleted_at IS NULL AND status = 'online'
`

func (q *Queries) GetOnlineOLTs(ctx context.Context) ([]Olt, error) {
	rows, err := q.db.Query(ctx, getOnlineOLTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Olt{}
	for rows.Next() {
		var i Olt
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Host,
			&i.SnmpVersion,
			&i.SnmpPort,
			&i.SnmpCommunityEncrypted,
			&i.SnmpUsername,
			&i.SnmpAuthProtocol,
			&i.SnmpAuthPasswordEncrypted,
			&i.SnmpPrivProtocol,
			&i.SnmpPrivPasswordEncrypted,
			&i.CliProtocol,
			&i.CliPort,
			&i.CliUsername,
			&i.CliPasswordEncrypted,
			&i.CliEnablePasswordEncrypted,
			&i.Brand,
			&i.Model,
			&i.FirmwareVersion,
			&i.PonPortCount,
			&i.TotalOntCount,
			&i.Status,
			&i.HealthCheckIntervalSec,
			&i.LastOnlineAt,
			&i.LastCheckedAt,
			&i.FailureCount,
			&i.Notes,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOLTs = `-- name: ListOLTs :many
SELECT id, tenant_id, name, host, snmp_version, snmp_port,
    snmp_community_encrypted, snmp_username, snmp_auth_protocol,
    snmp_auth_password_encrypted, snmp_priv_protocol, snmp_priv_password_encrypted,
    cli_protocol, cli_port, cli_username, cli_password_encrypted,
    cli_enable_password_encrypted, brand, model, firmware_version,
    pon_port_count, total_ont_count, status,
    health_check_interval_sec, last_online_at, last_checked_at,
    failure_count, notes, deleted_at, created_at, updated_at
FROM olts
WHERE deleted_at IS NULL
  AND ($3::varchar IS NULL OR status = $3::varchar)
  AND ($4::varchar IS NULL OR brand = $4::varchar)
  AND ($5::varchar IS NULL OR name ILIKE '%' || $5::varchar || '%' OR host ILIKE '%' || $5::varchar || '%')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOLTsParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status pgtype.Text `json:"status"`
	Brand  pgtype.Text `json:"brand"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) ListOLTs(ctx context.Context, arg ListOLTsParams) ([]Olt, error) {
	rows, err := q.db.Query(ctx, listOLTs,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Brand,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Olt{}
	for rows.Next() {
		var i Olt
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Host,
			&i.SnmpVersion,
			&i.SnmpPort,
			&i.SnmpCommunityEncrypted,
			&i.SnmpUsername,
			&i.SnmpAuthProtocol,
			&i.SnmpAuthPasswordEncrypted,
			&i.SnmpPrivProtocol,
			&i.SnmpPrivPasswordEncrypted,
			&i.CliProtocol,
			&i.CliPort,
			&i.CliUsername,
			&i.CliPasswordEncrypted,
			&i.CliEnablePasswordEncrypted,
			&i.Brand,
			&i.Model,
			&i.FirmwareVersion,
			&i.PonPortCount,
			&i.TotalOntCount,
			&i.Status,
			&i.HealthCheckIntervalSec,
			&i.LastOnlineAt,
			&i.LastCheckedAt,
			&i.FailureCount,
			&i.Notes,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oLTNameExists = `-- name: OLTNameExists :one
SELECT EXISTS(
    SELECT 1 FROM olts
    WHERE tenant_id = $1 AND name = $2 AND id != $3 AND deleted_at IS NULL
) AS exists
`

type OLTNameExistsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) OLTNameExists(ctx context.Context, arg OLTNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, oLTNameExists, arg.TenantID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteOLT = `-- name: SoftDeleteOLT :exec
UPDATE olts SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOLT(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteOLT, id)
	return err
}

const updateOLT = `-- name: UpdateOLT :one
UPDATE olts SET
    name = $2,
    host = $3,
    snmp_version = $4,
    snmp_port = $5,
    snmp_community_encrypted = $6,
    snmp_username = $7,
    snmp_auth_protocol = $8,
    snmp_auth_password_encrypted = $9,
    snmp_priv_protocol = $10,
    snmp_priv_password_encrypted = $11,
    cli_protocol = $12,
    cli_port = $13,
    cli_username = $14,
    cli_password_encrypted = $15,
    cli_enable_password_encrypted = $16,
    brand = $17,
    model = $18,
    firmware_version = $19,
    pon_port_count = $20,
    status = $21,
    health_check_interval_sec = $22,
    notes = $23,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, name, host, snmp_version, snmp_port,
    snmp_community_encrypted, snmp_username, snmp_auth_protocol,
    snmp_auth_password_encrypted, snmp_priv_protocol, snmp_priv_password_encrypted,
    cli_protocol, cli_port, cli_username, cli_password_encrypted,
    cli_enable_password_encrypted, brand, model, firmware_version,
    pon_port_count, total_ont_count, status,
    health_check_interval_sec, last_online_at, last_checked_at,
    failure_count, notes, deleted_at, created_at, updated_at
`

type UpdateOLTParams struct {
	ID                         pgtype.UUID `json:"id"`
	Name                       string      `json:"name"`
	Host                       string      `json:"host"`
	SnmpVersion                string      `json:"snmp_version"`
	SnmpPort                   int32       `json:"snmp_port"`
	SnmpCommunityEncrypted     pgtype.Text `json:"snmp_community_encrypted"`
	SnmpUsername               pgtype.Text `json:"snmp_username"`
	SnmpAuthProtocol           pgtype.Text `json:"snmp_auth_protocol"`
	SnmpAuthPasswordEncrypted  pgtype.Text `json:"snmp_auth_password_encrypted"`
	SnmpPrivProtocol           pgtype.Text `json:"snmp_priv_protocol"`
	SnmpPrivPasswordEncrypted  pgtype.Text `json:"snmp_priv_password_encrypted"`
	CliProtocol                string      `json:"cli_protocol"`
	CliPort                    int32       `json:"cli_port"`
	CliUsername                string      `json:"cli_username"`
	CliPasswordEncrypted       string      `json:"cli_password_encrypted"`
	CliEnablePasswordEncrypted pgtype.Text `json:"cli_enable_password_encrypted"`
	Brand                      pgtype.Text `json:"brand"`
	Model                      pgtype.Text `json:"model"`
	FirmwareVersion            pgtype.Text `json:"firmware_version"`
	PonPortCount               int32       `json:"pon_port_count"`
	Status                     string      `json:"status"`
	HealthCheckIntervalSec     int32       `json:"health_check_interval_sec"`
	Notes                      pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateOLT(ctx context.Context, arg UpdateOLTParams) (Olt, error) {
	row := q.db.QueryRow(ctx, updateOLT,
		arg.ID,
		arg.Name,
		arg.Host,
		arg.SnmpVersion,
		arg.SnmpPort,
		arg.SnmpCommunityEncrypted,
		arg.SnmpUsername,
		arg.SnmpAuthProtocol,
		arg.SnmpAuthPasswordEncrypted,
		arg.SnmpPrivProtocol,
		arg.SnmpPrivPasswordEncrypted,
		arg.CliProtocol,
		arg.CliPort,
		arg.CliUsername,
		arg.CliPasswordEncrypted,
		arg.CliEnablePasswordEncrypted,
		arg.Brand,
		arg.Model,
		arg.FirmwareVersion,
		arg.PonPortCount,
		arg.Status,
		arg.HealthCheckIntervalSec,
		arg.Notes,
	)
	var i Olt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Host,
		&i.SnmpVersion,
		&i.SnmpPort,
		&i.SnmpCommunityEncrypted,
		&i.SnmpUsername,
		&i.SnmpAuthProtocol,
		&i.SnmpAuthPasswordEncrypted,
		&i.SnmpPrivProtocol,
		&i.SnmpPrivPasswordEncrypted,
		&i.CliProtocol,
		&i.CliPort,
		&i.CliUsername,
		&i.CliPasswordEncrypted,
		&i.CliEnablePasswordEncrypted,
		&i.Brand,
		&i.Model,
		&i.FirmwareVersion,
		&i.PonPortCount,
		&i.TotalOntCount,
		&i.Status,
		&i.HealthCheckIntervalSec,
		&i.LastOnlineAt,
		&i.LastCheckedAt,
		&i.FailureCount,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOLTHealthCheck = `-- name: UpdateOLTHealthCheck :exec
UPDATE olts SET
    last_checked_at = $2,
    last_online_at = $3,
    failure_count = $4,
    status = $5,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateOLTHealthCheckParams struct {
	ID            pgtype.UUID        `json:"id"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
	LastOnlineAt  pgtype.Timestamptz `json:"last_online_at"`
	FailureCount  int32              `json:"failure_count"`
	Status        string             `json:"status"`
}

func (q *Queries) UpdateOLTHealthCheck(ctx context.Context, arg UpdateOLTHealthCheckParams) error {
	_, err := q.db.Exec(ctx, updateOLTHealthCheck,
		arg.ID,
		arg.LastCheckedAt,
		arg.LastOnlineAt,
		arg.FailureCount,
		arg.Status,
	)
	return err
}

const updateOLTONTCounts = `-- name: UpdateOLTONTCounts :exec
UPDATE olts SET
    total_ont_count = $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateOLTONTCountsParams struct {
	ID            pgtype.UUID `json:"id"`
	TotalOntCount int32       `json:"total_ont_count"`
}

func (q *Queries) UpdateOLTONTCounts(ctx context.Context, arg UpdateOLTONTCountsParams) error {
	_, err := q.db.Exec(ctx, updateOLTONTCounts, arg.ID, arg.TotalOntCount)
	return err
}
