// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pppoe_profiles.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPPPoEProfile = `-- name: CreatePPPoEProfile :one

INSERT INTO pppoe_profiles (
    tenant_id, package_id, profile_name,
    download_limit, upload_limit,
    burst_download, burst_upload,
    burst_threshold_download, burst_threshold_upload,
    burst_time, address_pool, local_address, only_one
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10, $11, $12, $13
)
RETURNING id, tenant_id, package_id, profile_name,
    download_limit, upload_limit,
    burst_download, burst_upload,
    burst_threshold_download, burst_threshold_upload,
    burst_time, address_pool, local_address, only_one,
    created_at, updated_at
`

type CreatePPPoEProfileParams struct {
	TenantID               pgtype.UUID `json:"tenant_id"`
	PackageID              pgtype.UUID `json:"package_id"`
	ProfileName            string      `json:"profile_name"`
	DownloadLimit          string      `json:"download_limit"`
	UploadLimit            string      `json:"upload_limit"`
	BurstDownload          pgtype.Text `json:"burst_download"`
	BurstUpload            pgtype.Text `json:"burst_upload"`
	BurstThresholdDownload pgtype.Text `json:"burst_threshold_download"`
	BurstThresholdUpload   pgtype.Text `json:"burst_threshold_upload"`
	BurstTime              pgtype.Text `json:"burst_time"`
	AddressPool            pgtype.Text `json:"address_pool"`
	LocalAddress           string      `json:"local_address"`
	OnlyOne                bool        `json:"only_one"`
}

// Query SQL untuk operasi CRUD tabel pppoe_profiles.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel pppoe_profiles dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Tabel ini TIDAK menggunakan soft-delete (tidak ada kolom deleted_at).
func (q *Queries) CreatePPPoEProfile(ctx context.Context, arg CreatePPPoEProfileParams) (PppoeProfile, error) {
	row := q.db.QueryRow(ctx, createPPPoEProfile,
		arg.TenantID,
		arg.PackageID,
		arg.ProfileName,
		arg.DownloadLimit,
		arg.UploadLimit,
		arg.BurstDownload,
		arg.BurstUpload,
		arg.BurstThresholdDownload,
		arg.BurstThresholdUpload,
		arg.BurstTime,
		arg.AddressPool,
		arg.LocalAddress,
		arg.OnlyOne,
	)
	var i PppoeProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PackageID,
		&i.ProfileName,
		&i.DownloadLimit,
		&i.UploadLimit,
		&i.BurstDownload,
		&i.BurstUpload,
		&i.BurstThresholdDownload,
		&i.BurstThresholdUpload,
		&i.BurstTime,
		&i.AddressPool,
		&i.LocalAddress,
		&i.OnlyOne,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPPPoEProfileByID = `-- name: GetPPPoEProfileByID :one
SELECT id, tenant_id, package_id, profile_name,
    download_limit, upload_limit,
    burst_download, burst_upload,
    burst_threshold_download, burst_threshold_upload,
    burst_time, address_pool, local_address, only_one,
    created_at, updated_at
FROM pppoe_profiles
WHERE id = $1
`

func (q *Queries) GetPPPoEProfileByID(ctx context.Context, id pgtype.UUID) (PppoeProfile, error) {
	row := q.db.QueryRow(ctx, getPPPoEProfileByID, id)
	var i PppoeProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PackageID,
		&i.ProfileName,
		&i.DownloadLimit,
		&i.UploadLimit,
		&i.BurstDownload,
		&i.BurstUpload,
		&i.BurstThresholdDownload,
		&i.BurstThresholdUpload,
		&i.BurstTime,
		&i.AddressPool,
		&i.LocalAddress,
		&i.OnlyOne,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPPPoEProfileByPackageID = `-- name: GetPPPoEProfileByPackageID :one
SELECT id, tenant_id, package_id, profile_name,
    download_limit, upload_limit,
    burst_download, burst_upload,
    burst_threshold_download, burst_threshold_upload,
    burst_time, address_pool, local_address, only_one,
    created_at, updated_at
FROM pppoe_profiles
WHERE package_id = $1
`

func (q *Queries) GetPPPoEProfileByPackageID(ctx context.Context, packageID pgtype.UUID) (PppoeProfile, error) {
	row := q.db.QueryRow(ctx, getPPPoEProfileByPackageID, packageID)
	var i PppoeProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PackageID,
		&i.ProfileName,
		&i.DownloadLimit,
		&i.UploadLimit,
		&i.BurstDownload,
		&i.BurstUpload,
		&i.BurstThresholdDownload,
		&i.BurstThresholdUpload,
		&i.BurstTime,
		&i.AddressPool,
		&i.LocalAddress,
		&i.OnlyOne,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPPPoEProfileByProfileName = `-- name: GetPPPoEProfileByProfileName :one
SELECT id, tenant_id, package_id, profile_name,
    download_limit, upload_limit,
    burst_download, burst_upload,
    burst_threshold_download, burst_threshold_upload,
    burst_time, address_pool, local_address, only_one,
    created_at, updated_at
FROM pppoe_profiles
WHERE tenant_id = $1 AND profile_name = $2
`

type GetPPPoEProfileByProfileNameParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ProfileName string      `json:"profile_name"`
}

func (q *Queries) GetPPPoEProfileByProfileName(ctx context.Context, arg GetPPPoEProfileByProfileNameParams) (PppoeProfile, error) {
	row := q.db.QueryRow(ctx, getPPPoEProfileByProfileName, arg.TenantID, arg.ProfileName)
	var i PppoeProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PackageID,
		&i.ProfileName,
		&i.DownloadLimit,
		&i.UploadLimit,
		&i.BurstDownload,
		&i.BurstUpload,
		&i.BurstThresholdDownload,
		&i.BurstThresholdUpload,
		&i.BurstTime,
		&i.AddressPool,
		&i.LocalAddress,
		&i.OnlyOne,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPPPoEProfilesByTenant = `-- name: ListPPPoEProfilesByTenant :many
SELECT id, tenant_id, package_id, profile_name,
    download_limit, upload_limit,
    burst_download, burst_upload,
    burst_threshold_download, burst_threshold_upload,
    burst_time, address_pool, local_address, only_one,
    created_at, updated_at
FROM pppoe_profiles
WHERE tenant_id = $1
ORDER BY profile_name ASC
`

func (q *Queries) ListPPPoEProfilesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]PppoeProfile, error) {
	rows, err := q.db.Query(ctx, listPPPoEProfilesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PppoeProfile{}
	for rows.Next() {
		var i PppoeProfile
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PackageID,
			&i.ProfileName,
			&i.DownloadLimit,
			&i.UploadLimit,
			&i.BurstDownload,
			&i.BurstUpload,
			&i.BurstThresholdDownload,
			&i.BurstThresholdUpload,
			&i.BurstTime,
			&i.AddressPool,
			&i.LocalAddress,
			&i.OnlyOne,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePPPoEProfile = `-- name: UpdatePPPoEProfile :one
UPDATE pppoe_profiles SET
    profile_name = $2,
    download_limit = $3,
    upload_limit = $4,
    burst_download = $5,
    burst_upload = $6,
    burst_threshold_download = $7,
    burst_threshold_upload = $8,
    burst_time = $9,
    address_pool = $10,
    local_address = $11,
    only_one = $12,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, package_id, profile_name,
    download_limit, upload_limit,
    burst_download, burst_upload,
    burst_threshold_download, burst_threshold_upload,
    burst_time, address_pool, local_address, only_one,
    created_at, updated_at
`

type UpdatePPPoEProfileParams struct {
	ID                     pgtype.UUID `json:"id"`
	ProfileName            string      `json:"profile_name"`
	DownloadLimit          string      `json:"download_limit"`
	UploadLimit            string      `json:"upload_limit"`
	BurstDownload          pgtype.Text `json:"burst_download"`
	BurstUpload            pgtype.Text `json:"burst_upload"`
	BurstThresholdDownload pgtype.Text `json:"burst_threshold_download"`
	BurstThresholdUpload   pgtype.Text `json:"burst_threshold_upload"`
	BurstTime              pgtype.Text `json:"burst_time"`
	AddressPool            pgtype.Text `json:"address_pool"`
	LocalAddress           string      `json:"local_address"`
	OnlyOne                bool        `json:"only_one"`
}

func (q *Queries) UpdatePPPoEProfile(ctx context.Context, arg UpdatePPPoEProfileParams) (PppoeProfile, error) {
	row := q.db.QueryRow(ctx, updatePPPoEProfile,
		arg.ID,
		arg.ProfileName,
		arg.DownloadLimit,
		arg.UploadLimit,
		arg.BurstDownload,
		arg.BurstUpload,
		arg.BurstThresholdDownload,
		arg.BurstThresholdUpload,
		arg.BurstTime,
		arg.AddressPool,
		arg.LocalAddress,
		arg.OnlyOne,
	)
	var i PppoeProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PackageID,
		&i.ProfileName,
		&i.DownloadLimit,
		&i.UploadLimit,
		&i.BurstDownload,
		&i.BurstUpload,
		&i.BurstThresholdDownload,
		&i.BurstThresholdUpload,
		&i.BurstTime,
		&i.AddressPool,
		&i.LocalAddress,
		&i.OnlyOne,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
