// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provisioning_settings.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProvisioningSettingsByTenantID = `-- name: GetProvisioningSettingsByTenantID :one

SELECT id, tenant_id, auto_provisioning_enabled, auto_port_migration_enabled,
    vlan_strategy, created_at, updated_at
FROM provisioning_settings
WHERE tenant_id = $1
`

// Query SQL untuk operasi tabel provisioning_settings.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Satu record per tenant, menggunakan upsert untuk create/update.
func (q *Queries) GetProvisioningSettingsByTenantID(ctx context.Context, tenantID pgtype.UUID) (ProvisioningSetting, error) {
	row := q.db.QueryRow(ctx, getProvisioningSettingsByTenantID, tenantID)
	var i ProvisioningSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AutoProvisioningEnabled,
		&i.AutoPortMigrationEnabled,
		&i.VlanStrategy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProvisioningSettings = `-- name: UpsertProvisioningSettings :one
INSERT INTO provisioning_settings (
    tenant_id, auto_provisioning_enabled, auto_port_migration_enabled, vlan_strategy
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (tenant_id) DO UPDATE SET
    auto_provisioning_enabled = EXCLUDED.auto_provisioning_enabled,
    auto_port_migration_enabled = EXCLUDED.auto_port_migration_enabled,
    vlan_strategy = EXCLUDED.vlan_strategy,
    updated_at = NOW()
RETURNING id, tenant_id, auto_provisioning_enabled, auto_port_migration_enabled,
    vlan_strategy, created_at, updated_at
`

type UpsertProvisioningSettingsParams struct {
	TenantID                 pgtype.UUID `json:"tenant_id"`
	AutoProvisioningEnabled  bool        `json:"auto_provisioning_enabled"`
	AutoPortMigrationEnabled bool        `json:"auto_port_migration_enabled"`
	VlanStrategy             string      `json:"vlan_strategy"`
}

func (q *Queries) UpsertProvisioningSettings(ctx context.Context, arg UpsertProvisioningSettingsParams) (ProvisioningSetting, error) {
	row := q.db.QueryRow(ctx, upsertProvisioningSettings,
		arg.TenantID,
		arg.AutoProvisioningEnabled,
		arg.AutoPortMigrationEnabled,
		arg.VlanStrategy,
	)
	var i ProvisioningSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AutoProvisioningEnabled,
		&i.AutoPortMigrationEnabled,
		&i.VlanStrategy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
