// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: routers.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countByStatus = `-- name: CountByStatus :many
SELECT status, COUNT(*) AS count
FROM routers
WHERE deleted_at IS NULL
GROUP BY status
`

type CountByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountByStatus(ctx context.Context) ([]CountByStatusRow, error) {
	rows, err := q.db.Query(ctx, countByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountByStatusRow{}
	for rows.Next() {
		var i CountByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRouters = `-- name: CountRouters :one
SELECT COUNT(*) FROM routers
WHERE deleted_at IS NULL
  AND ($1::varchar IS NULL OR status = $1::varchar)
  AND ($2::varchar IS NULL OR name ILIKE '%' || $2::varchar || '%')
`

type CountRoutersParams struct {
	Status pgtype.Text `json:"status"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) CountRouters(ctx context.Context, arg CountRoutersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRouters, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRouter = `-- name: CreateRouter :one

INSERT INTO routers (
    tenant_id, name, host, port, username, password_encrypted,
    use_ssl, service_types, router_os_version, board_name,
    cpu_count, total_ram_mb, identity, status,
    health_check_interval_sec, notes
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16
)
RETURNING id, tenant_id, name, host, port, username, password_encrypted,
    use_ssl, service_types, router_os_version, board_name,
    cpu_count, total_ram_mb, identity, status,
    health_check_interval_sec, last_online_at, last_checked_at,
    last_uptime_sec, failure_count, notes,
    deleted_at, created_at, updated_at
`

type CreateRouterParams struct {
	TenantID               pgtype.UUID `json:"tenant_id"`
	Name                   string      `json:"name"`
	Host                   string      `json:"host"`
	Port                   int32       `json:"port"`
	Username               string      `json:"username"`
	PasswordEncrypted      string      `json:"password_encrypted"`
	UseSsl                 bool        `json:"use_ssl"`
	ServiceTypes           []byte      `json:"service_types"`
	RouterOsVersion        pgtype.Text `json:"router_os_version"`
	BoardName              pgtype.Text `json:"board_name"`
	CpuCount               pgtype.Int4 `json:"cpu_count"`
	TotalRamMb             pgtype.Int4 `json:"total_ram_mb"`
	Identity               pgtype.Text `json:"identity"`
	Status                 string      `json:"status"`
	HealthCheckIntervalSec int32       `json:"health_check_interval_sec"`
	Notes                  pgtype.Text `json:"notes"`
}

// Kueri SQL untuk operasi CRUD tabel routers.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel routers dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Semua kueri menyertakan WHERE deleted_at IS NULL untuk mengecualikan hapus lunak.
func (q *Queries) CreateRouter(ctx context.Context, arg CreateRouterParams) (Router, error) {
	row := q.db.QueryRow(ctx, createRouter,
		arg.TenantID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.PasswordEncrypted,
		arg.UseSsl,
		arg.ServiceTypes,
		arg.RouterOsVersion,
		arg.BoardName,
		arg.CpuCount,
		arg.TotalRamMb,
		arg.Identity,
		arg.Status,
		arg.HealthCheckIntervalSec,
		arg.Notes,
	)
	var i Router
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEncrypted,
		&i.UseSsl,
		&i.ServiceTypes,
		&i.RouterOsVersion,
		&i.BoardName,
		&i.CpuCount,
		&i.TotalRamMb,
		&i.Identity,
		&i.Status,
		&i.HealthCheckIntervalSec,
		&i.LastOnlineAt,
		&i.LastCheckedAt,
		&i.LastUptimeSec,
		&i.FailureCount,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveRouters = `-- name: GetActiveRouters :many
SELECT id, tenant_id, name, host, port, username, password_encrypted,
    use_ssl, service_types, router_os_version, board_name,
    cpu_count, total_ram_mb, identity, status,
    health_check_interval_sec, last_online_at, last_checked_at,
    last_uptime_sec, failure_count, notes,
    deleted_at, created_at, updated_at
FROM routers
WHERE deleted_at IS NULL AND status != 'maintenance'
`

func (q *Queries) GetActiveRouters(ctx context.Context) ([]Router, error) {
	rows, err := q.db.Query(ctx, getActiveRouters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Router{}
	for rows.Next() {
		var i Router
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.PasswordEncrypted,
			&i.UseSsl,
			&i.ServiceTypes,
			&i.RouterOsVersion,
			&i.BoardName,
			&i.CpuCount,
			&i.TotalRamMb,
			&i.Identity,
			&i.Status,
			&i.HealthCheckIntervalSec,
			&i.LastOnlineAt,
			&i.LastCheckedAt,
			&i.LastUptimeSec,
			&i.FailureCount,
			&i.Notes,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRouterByID = `-- name: GetRouterByID :one
SELECT id, tenant_id, name, host, port, username, password_encrypted,
    use_ssl, service_types, router_os_version, board_name,
    cpu_count, total_ram_mb, identity, status,
    health_check_interval_sec, last_online_at, last_checked_at,
    last_uptime_sec, failure_count, notes,
    deleted_at, created_at, updated_at
FROM routers
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRouterByID(ctx context.Context, id pgtype.UUID) (Router, error) {
	row := q.db.QueryRow(ctx, getRouterByID, id)
	var i Router
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEncrypted,
		&i.UseSsl,
		&i.ServiceTypes,
		&i.RouterOsVersion,
		&i.BoardName,
		&i.CpuCount,
		&i.TotalRamMb,
		&i.Identity,
		&i.Status,
		&i.HealthCheckIntervalSec,
		&i.LastOnlineAt,
		&i.LastCheckedAt,
		&i.LastUptimeSec,
		&i.FailureCount,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRouters = `-- name: ListRouters :many
SELECT id, tenant_id, name, host, port, username, password_encrypted,
    use_ssl, service_types, router_os_version, board_name,
    cpu_count, total_ram_mb, identity, status,
    health_check_interval_sec, last_online_at, last_checked_at,
    last_uptime_sec, failure_count, notes,
    deleted_at, created_at, updated_at
FROM routers
WHERE deleted_at IS NULL
  AND ($3::varchar IS NULL OR status = $3::varchar)
  AND ($4::varchar IS NULL OR name ILIKE '%' || $4::varchar || '%')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRoutersParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status pgtype.Text `json:"status"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) ListRouters(ctx context.Context, arg ListRoutersParams) ([]Router, error) {
	rows, err := q.db.Query(ctx, listRouters,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Router{}
	for rows.Next() {
		var i Router
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.PasswordEncrypted,
			&i.UseSsl,
			&i.ServiceTypes,
			&i.RouterOsVersion,
			&i.BoardName,
			&i.CpuCount,
			&i.TotalRamMb,
			&i.Identity,
			&i.Status,
			&i.HealthCheckIntervalSec,
			&i.LastOnlineAt,
			&i.LastCheckedAt,
			&i.LastUptimeSec,
			&i.FailureCount,
			&i.Notes,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nameExists = `-- name: NameExists :one
SELECT EXISTS(
    SELECT 1 FROM routers
    WHERE tenant_id = $1 AND name = $2 AND id != $3 AND deleted_at IS NULL
) AS exists
`

type NameExistsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) NameExists(ctx context.Context, arg NameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, nameExists, arg.TenantID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteRouter = `-- name: SoftDeleteRouter :exec
UPDATE routers SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRouter(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteRouter, id)
	return err
}

const updateHealthCheck = `-- name: UpdateHealthCheck :exec
UPDATE routers SET
    last_checked_at = COALESCE($2, last_checked_at),
    last_online_at = COALESCE($3, last_online_at),
    last_uptime_sec = COALESCE($4, last_uptime_sec),
    failure_count = $5,
    status = COALESCE(NULLIF($6, ''), status),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateHealthCheckParams struct {
	ID            pgtype.UUID        `json:"id"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
	LastOnlineAt  pgtype.Timestamptz `json:"last_online_at"`
	LastUptimeSec pgtype.Int8        `json:"last_uptime_sec"`
	FailureCount  int32              `json:"failure_count"`
	Column6       interface{}        `json:"column_6"`
}

func (q *Queries) UpdateHealthCheck(ctx context.Context, arg UpdateHealthCheckParams) error {
	_, err := q.db.Exec(ctx, updateHealthCheck,
		arg.ID,
		arg.LastCheckedAt,
		arg.LastOnlineAt,
		arg.LastUptimeSec,
		arg.FailureCount,
		arg.Column6,
	)
	return err
}

const updateRouter = `-- name: UpdateRouter :one
UPDATE routers SET
    name = $2,
    host = $3,
    port = $4,
    username = $5,
    password_encrypted = $6,
    use_ssl = $7,
    service_types = $8,
    router_os_version = $9,
    board_name = $10,
    cpu_count = $11,
    total_ram_mb = $12,
    identity = $13,
    status = $14,
    health_check_interval_sec = $15,
    last_online_at = $16,
    last_uptime_sec = $17,
    notes = $18,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, name, host, port, username, password_encrypted,
    use_ssl, service_types, router_os_version, board_name,
    cpu_count, total_ram_mb, identity, status,
    health_check_interval_sec, last_online_at, last_checked_at,
    last_uptime_sec, failure_count, notes,
    deleted_at, created_at, updated_at
`

type UpdateRouterParams struct {
	ID                     pgtype.UUID        `json:"id"`
	Name                   string             `json:"name"`
	Host                   string             `json:"host"`
	Port                   int32              `json:"port"`
	Username               string             `json:"username"`
	PasswordEncrypted      string             `json:"password_encrypted"`
	UseSsl                 bool               `json:"use_ssl"`
	ServiceTypes           []byte             `json:"service_types"`
	RouterOsVersion        pgtype.Text        `json:"router_os_version"`
	BoardName              pgtype.Text        `json:"board_name"`
	CpuCount               pgtype.Int4        `json:"cpu_count"`
	TotalRamMb             pgtype.Int4        `json:"total_ram_mb"`
	Identity               pgtype.Text        `json:"identity"`
	Status                 string             `json:"status"`
	HealthCheckIntervalSec int32              `json:"health_check_interval_sec"`
	LastOnlineAt           pgtype.Timestamptz `json:"last_online_at"`
	LastUptimeSec          pgtype.Int8        `json:"last_uptime_sec"`
	Notes                  pgtype.Text        `json:"notes"`
}

func (q *Queries) UpdateRouter(ctx context.Context, arg UpdateRouterParams) (Router, error) {
	row := q.db.QueryRow(ctx, updateRouter,
		arg.ID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.PasswordEncrypted,
		arg.UseSsl,
		arg.ServiceTypes,
		arg.RouterOsVersion,
		arg.BoardName,
		arg.CpuCount,
		arg.TotalRamMb,
		arg.Identity,
		arg.Status,
		arg.HealthCheckIntervalSec,
		arg.LastOnlineAt,
		arg.LastUptimeSec,
		arg.Notes,
	)
	var i Router
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEncrypted,
		&i.UseSsl,
		&i.ServiceTypes,
		&i.RouterOsVersion,
		&i.BoardName,
		&i.CpuCount,
		&i.TotalRamMb,
		&i.Identity,
		&i.Status,
		&i.HealthCheckIntervalSec,
		&i.LastOnlineAt,
		&i.LastCheckedAt,
		&i.LastUptimeSec,
		&i.FailureCount,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
