// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vlans.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVLANActiveONTs = `-- name: CountVLANActiveONTs :one
SELECT COUNT(*) FROM onts
WHERE vlan_id = $1 AND deleted_at IS NULL AND status != 'decommissioned'
`

func (q *Queries) CountVLANActiveONTs(ctx context.Context, vlanID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVLANActiveONTs, vlanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVLANs = `-- name: CountVLANs :one
SELECT COUNT(*) FROM vlans
WHERE olt_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountVLANs(ctx context.Context, oltID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVLANs, oltID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVLAN = `-- name: CreateVLAN :one

INSERT INTO vlans (
    tenant_id, olt_id, vlan_id, name, vlan_type, description
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, tenant_id, olt_id, vlan_id, name, vlan_type, description,
    deleted_at, created_at, updated_at
`

type CreateVLANParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	OltID       pgtype.UUID `json:"olt_id"`
	VlanID      int32       `json:"vlan_id"`
	Name        string      `json:"name"`
	VlanType    string      `json:"vlan_type"`
	Description pgtype.Text `json:"description"`
}

// Query SQL untuk operasi CRUD tabel vlans.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel vlans dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Semua query menyertakan WHERE deleted_at IS NULL untuk mengecualikan soft-deleted.
func (q *Queries) CreateVLAN(ctx context.Context, arg CreateVLANParams) (Vlan, error) {
	row := q.db.QueryRow(ctx, createVLAN,
		arg.TenantID,
		arg.OltID,
		arg.VlanID,
		arg.Name,
		arg.VlanType,
		arg.Description,
	)
	var i Vlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OltID,
		&i.VlanID,
		&i.Name,
		&i.VlanType,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultVLAN = `-- name: GetDefaultVLAN :one
SELECT id, tenant_id, olt_id, vlan_id, name, vlan_type, description,
    deleted_at, created_at, updated_at
FROM vlans
WHERE olt_id = $1 AND vlan_type = 'data' AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetDefaultVLAN(ctx context.Context, oltID pgtype.UUID) (Vlan, error) {
	row := q.db.QueryRow(ctx, getDefaultVLAN, oltID)
	var i Vlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OltID,
		&i.VlanID,
		&i.Name,
		&i.VlanType,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVLANByID = `-- name: GetVLANByID :one
SELECT id, tenant_id, olt_id, vlan_id, name, vlan_type, description,
    deleted_at, created_at, updated_at
FROM vlans
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVLANByID(ctx context.Context, id pgtype.UUID) (Vlan, error) {
	row := q.db.QueryRow(ctx, getVLANByID, id)
	var i Vlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OltID,
		&i.VlanID,
		&i.Name,
		&i.VlanType,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVLANByOLTAndVLANID = `-- name: GetVLANByOLTAndVLANID :one
SELECT id, tenant_id, olt_id, vlan_id, name, vlan_type, description,
    deleted_at, created_at, updated_at
FROM vlans
WHERE olt_id = $1 AND vlan_id = $2 AND deleted_at IS NULL
`

type GetVLANByOLTAndVLANIDParams struct {
	OltID  pgtype.UUID `json:"olt_id"`
	VlanID int32       `json:"vlan_id"`
}

func (q *Queries) GetVLANByOLTAndVLANID(ctx context.Context, arg GetVLANByOLTAndVLANIDParams) (Vlan, error) {
	row := q.db.QueryRow(ctx, getVLANByOLTAndVLANID, arg.OltID, arg.VlanID)
	var i Vlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OltID,
		&i.VlanID,
		&i.Name,
		&i.VlanType,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVLANs = `-- name: ListVLANs :many
SELECT id, tenant_id, olt_id, vlan_id, name, vlan_type, description,
    deleted_at, created_at, updated_at
FROM vlans
WHERE olt_id = $1 AND deleted_at IS NULL
ORDER BY vlan_id ASC
LIMIT $2 OFFSET $3
`

type ListVLANsParams struct {
	OltID  pgtype.UUID `json:"olt_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListVLANs(ctx context.Context, arg ListVLANsParams) ([]Vlan, error) {
	rows, err := q.db.Query(ctx, listVLANs, arg.OltID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vlan{}
	for rows.Next() {
		var i Vlan
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OltID,
			&i.VlanID,
			&i.Name,
			&i.VlanType,
			&i.Description,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVLAN = `-- name: SoftDeleteVLAN :exec
UPDATE vlans SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteVLAN(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteVLAN, id)
	return err
}

const updateVLAN = `-- name: UpdateVLAN :one
UPDATE vlans SET
    name = $2,
    vlan_type = $3,
    description = $4,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, olt_id, vlan_id, name, vlan_type, description,
    deleted_at, created_at, updated_at
`

type UpdateVLANParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	VlanType    string      `json:"vlan_type"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateVLAN(ctx context.Context, arg UpdateVLANParams) (Vlan, error) {
	row := q.db.QueryRow(ctx, updateVLAN,
		arg.ID,
		arg.Name,
		arg.VlanType,
		arg.Description,
	)
	var i Vlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OltID,
		&i.VlanID,
		&i.Name,
		&i.VlanType,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const vLANIDExists = `-- name: VLANIDExists :one
SELECT EXISTS(
    SELECT 1 FROM vlans
    WHERE olt_id = $1 AND vlan_id = $2 AND id != $3 AND deleted_at IS NULL
) AS exists
`

type VLANIDExistsParams struct {
	OltID  pgtype.UUID `json:"olt_id"`
	VlanID int32       `json:"vlan_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) VLANIDExists(ctx context.Context, arg VLANIDExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, vLANIDExists, arg.OltID, arg.VlanID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
