// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vpn_subnets.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVPNSubnet = `-- name: CreateVPNSubnet :one
INSERT INTO vpn_subnets (
    tenant_id, subnet_prefix, tenant_seq, server_ip, next_client_ip_seq
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, tenant_id, subnet_prefix, tenant_seq, server_ip, next_client_ip_seq, created_at
`

type CreateVPNSubnetParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	SubnetPrefix    string      `json:"subnet_prefix"`
	TenantSeq       int32       `json:"tenant_seq"`
	ServerIp        string      `json:"server_ip"`
	NextClientIpSeq int32       `json:"next_client_ip_seq"`
}

func (q *Queries) CreateVPNSubnet(ctx context.Context, arg CreateVPNSubnetParams) (VpnSubnet, error) {
	row := q.db.QueryRow(ctx, createVPNSubnet,
		arg.TenantID,
		arg.SubnetPrefix,
		arg.TenantSeq,
		arg.ServerIp,
		arg.NextClientIpSeq,
	)
	var i VpnSubnet
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubnetPrefix,
		&i.TenantSeq,
		&i.ServerIp,
		&i.NextClientIpSeq,
		&i.CreatedAt,
	)
	return i, err
}

const getNextTenantSeq = `-- name: GetNextTenantSeq :one
SELECT COALESCE(MAX(tenant_seq), 0) + 1 AS next_seq
FROM vpn_subnets
`

// Mengambil tenant_seq berikutnya yang tersedia untuk alokasi subnet baru.
func (q *Queries) GetNextTenantSeq(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextTenantSeq)
	var next_seq int32
	err := row.Scan(&next_seq)
	return next_seq, err
}

const getVPNSubnetByTenantID = `-- name: GetVPNSubnetByTenantID :one

SELECT id, tenant_id, subnet_prefix, tenant_seq, server_ip, next_client_ip_seq, created_at
FROM vpn_subnets
WHERE tenant_id = $1
`

// Query SQL untuk operasi tabel vpn_subnets.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel vpn_subnets dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Setiap tenant mendapat 1 subnet /24: 10.99.{tenant_seq}.0/24.
func (q *Queries) GetVPNSubnetByTenantID(ctx context.Context, tenantID pgtype.UUID) (VpnSubnet, error) {
	row := q.db.QueryRow(ctx, getVPNSubnetByTenantID, tenantID)
	var i VpnSubnet
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubnetPrefix,
		&i.TenantSeq,
		&i.ServerIp,
		&i.NextClientIpSeq,
		&i.CreatedAt,
	)
	return i, err
}

const incrementNextClientIPSeq = `-- name: IncrementNextClientIPSeq :one
UPDATE vpn_subnets
SET next_client_ip_seq = next_client_ip_seq + 1
WHERE tenant_id = $1
RETURNING next_client_ip_seq - 1 AS current_seq
`

// Menaikkan next_client_ip_seq dan mengembalikan nilai sebelumnya (untuk alokasi IP client).
func (q *Queries) IncrementNextClientIPSeq(ctx context.Context, tenantID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementNextClientIPSeq, tenantID)
	var current_seq int32
	err := row.Scan(&current_seq)
	return current_seq, err
}
