// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: areas.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const areaCustomerCount = `-- name: AreaCustomerCount :one
SELECT COUNT(*)::integer AS count
FROM customers
WHERE area_id = $1 AND deleted_at IS NULL
`

func (q *Queries) AreaCustomerCount(ctx context.Context, areaID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, areaCustomerCount, areaID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const areaNameExists = `-- name: AreaNameExists :one
SELECT EXISTS(
    SELECT 1 FROM areas
    WHERE tenant_id = $1 AND name = $2 AND id != $3
) AS exists
`

type AreaNameExistsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) AreaNameExists(ctx context.Context, arg AreaNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, areaNameExists, arg.TenantID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createArea = `-- name: CreateArea :one

INSERT INTO areas (tenant_id, name, description, odp_id, center_lat, center_lng)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, description, odp_id, center_lat, center_lng, created_at, updated_at
`

type CreateAreaParams struct {
	TenantID    pgtype.UUID    `json:"tenant_id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	OdpID       pgtype.Text    `json:"odp_id"`
	CenterLat   pgtype.Numeric `json:"center_lat"`
	CenterLng   pgtype.Numeric `json:"center_lng"`
}

// Kueri SQL untuk operasi CRUD tabel areas.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel areas dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
func (q *Queries) CreateArea(ctx context.Context, arg CreateAreaParams) (Area, error) {
	row := q.db.QueryRow(ctx, createArea,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.OdpID,
		arg.CenterLat,
		arg.CenterLng,
	)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.OdpID,
		&i.CenterLat,
		&i.CenterLng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArea = `-- name: DeleteArea :exec
DELETE FROM areas WHERE id = $1
`

func (q *Queries) DeleteArea(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArea, id)
	return err
}

const getAreaByID = `-- name: GetAreaByID :one
SELECT id, tenant_id, name, description, odp_id, center_lat, center_lng, created_at, updated_at
FROM areas
WHERE id = $1
`

func (q *Queries) GetAreaByID(ctx context.Context, id pgtype.UUID) (Area, error) {
	row := q.db.QueryRow(ctx, getAreaByID, id)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.OdpID,
		&i.CenterLat,
		&i.CenterLng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAreas = `-- name: ListAreas :many
SELECT a.id, a.tenant_id, a.name, a.description, a.odp_id,
    a.center_lat, a.center_lng, a.created_at, a.updated_at,
    COUNT(c.id)::integer AS customer_count
FROM areas a
LEFT JOIN customers c ON c.area_id = a.id AND c.deleted_at IS NULL
WHERE a.tenant_id = $1
GROUP BY a.id, a.tenant_id, a.name, a.description, a.odp_id,
    a.center_lat, a.center_lng, a.created_at, a.updated_at
ORDER BY a.name ASC
`

type ListAreasRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	OdpID         pgtype.Text        `json:"odp_id"`
	CenterLat     pgtype.Numeric     `json:"center_lat"`
	CenterLng     pgtype.Numeric     `json:"center_lng"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CustomerCount int32              `json:"customer_count"`
}

func (q *Queries) ListAreas(ctx context.Context, tenantID pgtype.UUID) ([]ListAreasRow, error) {
	rows, err := q.db.Query(ctx, listAreas, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAreasRow{}
	for rows.Next() {
		var i ListAreasRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.OdpID,
			&i.CenterLat,
			&i.CenterLng,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArea = `-- name: UpdateArea :one
UPDATE areas SET
    name = $2,
    description = $3,
    odp_id = $4,
    center_lat = $5,
    center_lng = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, name, description, odp_id, center_lat, center_lng, created_at, updated_at
`

type UpdateAreaParams struct {
	ID          pgtype.UUID    `json:"id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	OdpID       pgtype.Text    `json:"odp_id"`
	CenterLat   pgtype.Numeric `json:"center_lat"`
	CenterLng   pgtype.Numeric `json:"center_lng"`
}

func (q *Queries) UpdateArea(ctx context.Context, arg UpdateAreaParams) (Area, error) {
	row := q.db.QueryRow(ctx, updateArea,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OdpID,
		arg.CenterLat,
		arg.CenterLng,
	)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.OdpID,
		&i.CenterLat,
		&i.CenterLng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
