// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: audit_logs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec

INSERT INTO audit_logs (tenant_id, entity_type, entity_id, action, actor_id, actor_name, changes, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAuditLogParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Action     string      `json:"action"`
	ActorID    pgtype.UUID `json:"actor_id"`
	ActorName  string      `json:"actor_name"`
	Changes    []byte      `json:"changes"`
	Metadata   []byte      `json:"metadata"`
}

// Kueri SQL untuk operasi CRUD tabel audit_logs.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel audit_logs dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.TenantID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.ActorID,
		arg.ActorName,
		arg.Changes,
		arg.Metadata,
	)
	return err
}

const listAuditLogsByEntity = `-- name: ListAuditLogsByEntity :many
SELECT id, tenant_id, entity_type, entity_id, action, actor_id, actor_name, changes, metadata, created_at
FROM audit_logs
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
`

type ListAuditLogsByEntityParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
}

func (q *Queries) ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.ActorID,
			&i.ActorName,
			&i.Changes,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
