// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: auth_tokens.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO email_verifications (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateEmailVerificationParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, createEmailVerification, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createPasswordReset = `-- name: CreatePasswordReset :exec

INSERT INTO password_resets (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreatePasswordResetParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Kueri SQL untuk operasi CRUD tabel password_resets dan email_verifications.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Token disimpan sebagai SHA-256 hash, plaintext hanya dikirim ke user.
func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.Exec(ctx, createPasswordReset, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const getEmailVerificationByHash = `-- name: GetEmailVerificationByHash :one
SELECT id, user_id, token_hash, expires_at, used, created_at
FROM email_verifications WHERE token_hash = $1
`

func (q *Queries) GetEmailVerificationByHash(ctx context.Context, tokenHash string) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByHash, tokenHash)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetByHash = `-- name: GetPasswordResetByHash :one
SELECT id, user_id, token_hash, expires_at, used, created_at
FROM password_resets WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetByHash(ctx context.Context, tokenHash string) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByHash, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateEmailVerifications = `-- name: InvalidateEmailVerifications :exec
UPDATE email_verifications SET used = true WHERE user_id = $1 AND used = false
`

func (q *Queries) InvalidateEmailVerifications(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidateEmailVerifications, userID)
	return err
}

const invalidatePasswordResets = `-- name: InvalidatePasswordResets :exec
UPDATE password_resets SET used = true WHERE user_id = $1 AND used = false
`

func (q *Queries) InvalidatePasswordResets(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidatePasswordResets, userID)
	return err
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :exec
UPDATE email_verifications SET used = true WHERE id = $1
`

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerificationUsed, id)
	return err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_resets SET used = true WHERE id = $1
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetUsed, id)
	return err
}
