// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: billing_settings.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBillingSettingsByTenantID = `-- name: GetBillingSettingsByTenantID :one

SELECT id, tenant_id, generate_days, grace_period_days, suspend_days, tax_enabled, tax_rate, penalty_enabled, penalty_type, penalty_amount, penalty_percentage, penalty_daily_amount, penalty_max_amount, invoice_prefix, new_customer_billing, timezone, auto_isolir, auto_open_isolir, created_at, updated_at
FROM billing_settings
WHERE tenant_id = $1
`

// Kueri SQL untuk operasi CRUD tabel billing_settings.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel billing_settings dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Setiap tenant memiliki tepat satu baris billing_settings (UNIQUE pada tenant_id).
// Mengambil billing settings berdasarkan tenant ID.
func (q *Queries) GetBillingSettingsByTenantID(ctx context.Context, tenantID pgtype.UUID) (BillingSetting, error) {
	row := q.db.QueryRow(ctx, getBillingSettingsByTenantID, tenantID)
	var i BillingSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GenerateDays,
		&i.GracePeriodDays,
		&i.SuspendDays,
		&i.TaxEnabled,
		&i.TaxRate,
		&i.PenaltyEnabled,
		&i.PenaltyType,
		&i.PenaltyAmount,
		&i.PenaltyPercentage,
		&i.PenaltyDailyAmount,
		&i.PenaltyMaxAmount,
		&i.InvoicePrefix,
		&i.NewCustomerBilling,
		&i.Timezone,
		&i.AutoIsolir,
		&i.AutoOpenIsolir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllBillingSettings = `-- name: ListAllBillingSettings :many
SELECT id, tenant_id, generate_days, grace_period_days, suspend_days, tax_enabled, tax_rate, penalty_enabled, penalty_type, penalty_amount, penalty_percentage, penalty_daily_amount, penalty_max_amount, invoice_prefix, new_customer_billing, timezone, auto_isolir, auto_open_isolir, created_at, updated_at
FROM billing_settings
`

// Mengambil semua billing settings (untuk job cron lintas tenant).
// Kueri ini dijalankan tanpa RLS context (superuser/service role).
func (q *Queries) ListAllBillingSettings(ctx context.Context) ([]BillingSetting, error) {
	rows, err := q.db.Query(ctx, listAllBillingSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingSetting{}
	for rows.Next() {
		var i BillingSetting
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.GenerateDays,
			&i.GracePeriodDays,
			&i.SuspendDays,
			&i.TaxEnabled,
			&i.TaxRate,
			&i.PenaltyEnabled,
			&i.PenaltyType,
			&i.PenaltyAmount,
			&i.PenaltyPercentage,
			&i.PenaltyDailyAmount,
			&i.PenaltyMaxAmount,
			&i.InvoicePrefix,
			&i.NewCustomerBilling,
			&i.Timezone,
			&i.AutoIsolir,
			&i.AutoOpenIsolir,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBillingSettings = `-- name: UpsertBillingSettings :one
INSERT INTO billing_settings (
    tenant_id, generate_days, grace_period_days, suspend_days,
    tax_enabled, tax_rate, penalty_enabled, penalty_type,
    penalty_amount, penalty_percentage, penalty_daily_amount, penalty_max_amount,
    invoice_prefix, new_customer_billing, timezone,
    auto_isolir, auto_open_isolir
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15,
    $16, $17
)
ON CONFLICT (tenant_id) DO UPDATE SET
    generate_days = EXCLUDED.generate_days,
    grace_period_days = EXCLUDED.grace_period_days,
    suspend_days = EXCLUDED.suspend_days,
    tax_enabled = EXCLUDED.tax_enabled,
    tax_rate = EXCLUDED.tax_rate,
    penalty_enabled = EXCLUDED.penalty_enabled,
    penalty_type = EXCLUDED.penalty_type,
    penalty_amount = EXCLUDED.penalty_amount,
    penalty_percentage = EXCLUDED.penalty_percentage,
    penalty_daily_amount = EXCLUDED.penalty_daily_amount,
    penalty_max_amount = EXCLUDED.penalty_max_amount,
    invoice_prefix = EXCLUDED.invoice_prefix,
    new_customer_billing = EXCLUDED.new_customer_billing,
    timezone = EXCLUDED.timezone,
    auto_isolir = EXCLUDED.auto_isolir,
    auto_open_isolir = EXCLUDED.auto_open_isolir,
    updated_at = NOW()
RETURNING id, tenant_id, generate_days, grace_period_days, suspend_days, tax_enabled, tax_rate, penalty_enabled, penalty_type, penalty_amount, penalty_percentage, penalty_daily_amount, penalty_max_amount, invoice_prefix, new_customer_billing, timezone, auto_isolir, auto_open_isolir, created_at, updated_at
`

type UpsertBillingSettingsParams struct {
	TenantID           pgtype.UUID    `json:"tenant_id"`
	GenerateDays       int32          `json:"generate_days"`
	GracePeriodDays    int32          `json:"grace_period_days"`
	SuspendDays        int32          `json:"suspend_days"`
	TaxEnabled         bool           `json:"tax_enabled"`
	TaxRate            pgtype.Numeric `json:"tax_rate"`
	PenaltyEnabled     bool           `json:"penalty_enabled"`
	PenaltyType        string         `json:"penalty_type"`
	PenaltyAmount      int64          `json:"penalty_amount"`
	PenaltyPercentage  pgtype.Numeric `json:"penalty_percentage"`
	PenaltyDailyAmount int64          `json:"penalty_daily_amount"`
	PenaltyMaxAmount   int64          `json:"penalty_max_amount"`
	InvoicePrefix      string         `json:"invoice_prefix"`
	NewCustomerBilling string         `json:"new_customer_billing"`
	Timezone           string         `json:"timezone"`
	AutoIsolir         bool           `json:"auto_isolir"`
	AutoOpenIsolir     bool           `json:"auto_open_isolir"`
}

// Membuat atau memperbarui billing settings untuk tenant.
// Menggunakan INSERT ON CONFLICT untuk upsert berdasarkan tenant_id.
func (q *Queries) UpsertBillingSettings(ctx context.Context, arg UpsertBillingSettingsParams) (BillingSetting, error) {
	row := q.db.QueryRow(ctx, upsertBillingSettings,
		arg.TenantID,
		arg.GenerateDays,
		arg.GracePeriodDays,
		arg.SuspendDays,
		arg.TaxEnabled,
		arg.TaxRate,
		arg.PenaltyEnabled,
		arg.PenaltyType,
		arg.PenaltyAmount,
		arg.PenaltyPercentage,
		arg.PenaltyDailyAmount,
		arg.PenaltyMaxAmount,
		arg.InvoicePrefix,
		arg.NewCustomerBilling,
		arg.Timezone,
		arg.AutoIsolir,
		arg.AutoOpenIsolir,
	)
	var i BillingSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GenerateDays,
		&i.GracePeriodDays,
		&i.SuspendDays,
		&i.TaxEnabled,
		&i.TaxRate,
		&i.PenaltyEnabled,
		&i.PenaltyType,
		&i.PenaltyAmount,
		&i.PenaltyPercentage,
		&i.PenaltyDailyAmount,
		&i.PenaltyMaxAmount,
		&i.InvoicePrefix,
		&i.NewCustomerBilling,
		&i.Timezone,
		&i.AutoIsolir,
		&i.AutoOpenIsolir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
