// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForBulkCreateInvoiceItems implements pgx.CopyFromSource.
type iteratorForBulkCreateInvoiceItems struct {
	rows                 []BulkCreateInvoiceItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateInvoiceItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateInvoiceItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TenantID,
		r.rows[0].InvoiceID,
		r.rows[0].ItemType,
		r.rows[0].Description,
		r.rows[0].Quantity,
		r.rows[0].UnitPrice,
		r.rows[0].Amount,
		r.rows[0].SortOrder,
		r.rows[0].Metadata,
	}, nil
}

func (r iteratorForBulkCreateInvoiceItems) Err() error {
	return nil
}

// Query SQL untuk operasi CRUD tabel invoice_items.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel invoice_items dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Bulk insert item invoice menggunakan PostgreSQL COPY protocol.
func (q *Queries) BulkCreateInvoiceItems(ctx context.Context, arg []BulkCreateInvoiceItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"invoice_items"}, []string{"tenant_id", "invoice_id", "item_type", "description", "quantity", "unit_price", "amount", "sort_order", "metadata"}, &iteratorForBulkCreateInvoiceItems{rows: arg})
}

// iteratorForBulkCreateVouchers implements pgx.CopyFromSource.
type iteratorForBulkCreateVouchers struct {
	rows                 []BulkCreateVouchersParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateVouchers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateVouchers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TenantID,
		r.rows[0].Code,
		r.rows[0].PackageID,
		r.rows[0].Status,
	}, nil
}

func (r iteratorForBulkCreateVouchers) Err() error {
	return nil
}

// Query SQL untuk operasi CRUD tabel vouchers.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel vouchers dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Query List dan ListByReseller dibangun secara dinamis di repository (sama seperti customer/package).
// Bulk insert voucher baru menggunakan PostgreSQL COPY protocol.
func (q *Queries) BulkCreateVouchers(ctx context.Context, arg []BulkCreateVouchersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"vouchers"}, []string{"tenant_id", "code", "package_id", "status"}, &iteratorForBulkCreateVouchers{rows: arg})
}
