// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: customer_recurring_items.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurringItem = `-- name: CreateRecurringItem :one

INSERT INTO customer_recurring_items (
    tenant_id, customer_id, description, amount,
    is_active, start_date, end_date
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
RETURNING id, tenant_id, customer_id, description, amount, is_active, start_date, end_date, created_at, updated_at
`

type CreateRecurringItemParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	CustomerID  pgtype.UUID `json:"customer_id"`
	Description string      `json:"description"`
	Amount      int64       `json:"amount"`
	IsActive    bool        `json:"is_active"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

// Kueri SQL untuk operasi CRUD tabel customer_recurring_items.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel customer_recurring_items dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Membuat item berulang baru dan mengembalikan semua kolom.
func (q *Queries) CreateRecurringItem(ctx context.Context, arg CreateRecurringItemParams) (CustomerRecurringItem, error) {
	row := q.db.QueryRow(ctx, createRecurringItem,
		arg.TenantID,
		arg.CustomerID,
		arg.Description,
		arg.Amount,
		arg.IsActive,
		arg.StartDate,
		arg.EndDate,
	)
	var i CustomerRecurringItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.Description,
		&i.Amount,
		&i.IsActive,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateRecurringItem = `-- name: DeactivateRecurringItem :exec
UPDATE customer_recurring_items SET
    is_active = false,
    updated_at = NOW()
WHERE id = $1
`

// Menonaktifkan item berulang (atur is_active = false).
func (q *Queries) DeactivateRecurringItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateRecurringItem, id)
	return err
}

const getRecurringItemByID = `-- name: GetRecurringItemByID :one
SELECT id, tenant_id, customer_id, description, amount, is_active, start_date, end_date, created_at, updated_at
FROM customer_recurring_items
WHERE id = $1
`

// Mengambil item berulang berdasarkan ID.
func (q *Queries) GetRecurringItemByID(ctx context.Context, id pgtype.UUID) (CustomerRecurringItem, error) {
	row := q.db.QueryRow(ctx, getRecurringItemByID, id)
	var i CustomerRecurringItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.Description,
		&i.Amount,
		&i.IsActive,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRecurringItemsByCustomer = `-- name: ListActiveRecurringItemsByCustomer :many
SELECT id, tenant_id, customer_id, description, amount, is_active, start_date, end_date, created_at, updated_at
FROM customer_recurring_items
WHERE customer_id = $1
  AND is_active = true
  AND start_date <= $2
  AND (end_date IS NULL OR end_date > $2)
ORDER BY created_at ASC
`

type ListActiveRecurringItemsByCustomerParams struct {
	CustomerID pgtype.UUID `json:"customer_id"`
	StartDate  pgtype.Date `json:"start_date"`
}

// Mengambil item berulang aktif untuk customer pada tanggal periode tertentu.
// Item aktif: is_active = true, start_date <= period_date, dan (end_date IS NULL atau end_date > period_date).
func (q *Queries) ListActiveRecurringItemsByCustomer(ctx context.Context, arg ListActiveRecurringItemsByCustomerParams) ([]CustomerRecurringItem, error) {
	rows, err := q.db.Query(ctx, listActiveRecurringItemsByCustomer, arg.CustomerID, arg.StartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerRecurringItem{}
	for rows.Next() {
		var i CustomerRecurringItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.Description,
			&i.Amount,
			&i.IsActive,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringItemsByCustomer = `-- name: ListRecurringItemsByCustomer :many
SELECT id, tenant_id, customer_id, description, amount, is_active, start_date, end_date, created_at, updated_at
FROM customer_recurring_items
WHERE customer_id = $1
ORDER BY created_at ASC
`

// Mengambil semua item berulang untuk customer tertentu.
func (q *Queries) ListRecurringItemsByCustomer(ctx context.Context, customerID pgtype.UUID) ([]CustomerRecurringItem, error) {
	rows, err := q.db.Query(ctx, listRecurringItemsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerRecurringItem{}
	for rows.Next() {
		var i CustomerRecurringItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.Description,
			&i.Amount,
			&i.IsActive,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringItem = `-- name: UpdateRecurringItem :one
UPDATE customer_recurring_items SET
    description = $2,
    amount = $3,
    end_date = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, customer_id, description, amount, is_active, start_date, end_date, created_at, updated_at
`

type UpdateRecurringItemParams struct {
	ID          pgtype.UUID `json:"id"`
	Description string      `json:"description"`
	Amount      int64       `json:"amount"`
	EndDate     pgtype.Date `json:"end_date"`
}

// Memperbarui item berulang dan mengembalikan item yang diperbarui.
func (q *Queries) UpdateRecurringItem(ctx context.Context, arg UpdateRecurringItemParams) (CustomerRecurringItem, error) {
	row := q.db.QueryRow(ctx, updateRecurringItem,
		arg.ID,
		arg.Description,
		arg.Amount,
		arg.EndDate,
	)
	var i CustomerRecurringItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.Description,
		&i.Amount,
		&i.IsActive,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
