// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: customers.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomersByStatusAktif = `-- name: CountCustomersByStatusAktif :one
SELECT COUNT(*) FROM customers WHERE status = 'aktif' AND deleted_at IS NULL
`

func (q *Queries) CountCustomersByStatusAktif(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomersByStatusAktif)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCustomersByStatusBerhenti = `-- name: CountCustomersByStatusBerhenti :one
SELECT COUNT(*) FROM customers WHERE status = 'berhenti' AND deleted_at IS NULL
`

func (q *Queries) CountCustomersByStatusBerhenti(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomersByStatusBerhenti)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCustomersByStatusIsolir = `-- name: CountCustomersByStatusIsolir :one
SELECT COUNT(*) FROM customers WHERE status = 'isolir' AND deleted_at IS NULL
`

func (q *Queries) CountCustomersByStatusIsolir(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomersByStatusIsolir)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCustomersByStatusPending = `-- name: CountCustomersByStatusPending :one
SELECT COUNT(*) FROM customers WHERE status = 'pending' AND deleted_at IS NULL
`

func (q *Queries) CountCustomersByStatusPending(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomersByStatusPending)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCustomersByStatusSuspend = `-- name: CountCustomersByStatusSuspend :one
SELECT COUNT(*) FROM customers WHERE status = 'suspend' AND deleted_at IS NULL
`

func (q *Queries) CountCustomersByStatusSuspend(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomersByStatusSuspend)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one

INSERT INTO customers (
    tenant_id, customer_id_seq, name, phone, email, address,
    area_id, latitude, longitude, package_id, activation_date,
    due_date, connection_method, pppoe_username, pppoe_password,
    mac_address, router_id, odp_port, credit_balance, notes, status
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21
)
RETURNING id, tenant_id, customer_id_seq, name, phone, email, address,
    area_id, latitude, longitude, package_id, activation_date,
    due_date, connection_method, pppoe_username, pppoe_password,
    mac_address, router_id, odp_port, credit_balance, notes, status,
    deleted_at, created_at, updated_at
`

type CreateCustomerParams struct {
	TenantID         pgtype.UUID    `json:"tenant_id"`
	CustomerIDSeq    pgtype.Text    `json:"customer_id_seq"`
	Name             string         `json:"name"`
	Phone            string         `json:"phone"`
	Email            pgtype.Text    `json:"email"`
	Address          string         `json:"address"`
	AreaID           pgtype.UUID    `json:"area_id"`
	Latitude         pgtype.Numeric `json:"latitude"`
	Longitude        pgtype.Numeric `json:"longitude"`
	PackageID        pgtype.UUID    `json:"package_id"`
	ActivationDate   pgtype.Date    `json:"activation_date"`
	DueDate          int32          `json:"due_date"`
	ConnectionMethod string         `json:"connection_method"`
	PppoeUsername    pgtype.Text    `json:"pppoe_username"`
	PppoePassword    pgtype.Text    `json:"pppoe_password"`
	MacAddress       pgtype.Text    `json:"mac_address"`
	RouterID         pgtype.UUID    `json:"router_id"`
	OdpPort          pgtype.Text    `json:"odp_port"`
	CreditBalance    int64          `json:"credit_balance"`
	Notes            pgtype.Text    `json:"notes"`
	Status           string         `json:"status"`
}

// Kueri SQL untuk operasi CRUD tabel customers (schema lengkap 24 kolom).
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel customers dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.TenantID,
		arg.CustomerIDSeq,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.AreaID,
		arg.Latitude,
		arg.Longitude,
		arg.PackageID,
		arg.ActivationDate,
		arg.DueDate,
		arg.ConnectionMethod,
		arg.PppoeUsername,
		arg.PppoePassword,
		arg.MacAddress,
		arg.RouterID,
		arg.OdpPort,
		arg.CreditBalance,
		arg.Notes,
		arg.Status,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerIDSeq,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.AreaID,
		&i.Latitude,
		&i.Longitude,
		&i.PackageID,
		&i.ActivationDate,
		&i.DueDate,
		&i.ConnectionMethod,
		&i.PppoeUsername,
		&i.PppoePassword,
		&i.MacAddress,
		&i.RouterID,
		&i.OdpPort,
		&i.CreditBalance,
		&i.Notes,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, tenant_id, customer_id_seq, name, phone, email, address,
    area_id, latitude, longitude, package_id, activation_date,
    due_date, connection_method, pppoe_username, pppoe_password,
    mac_address, router_id, odp_port, credit_balance, notes, status,
    deleted_at, created_at, updated_at
FROM customers
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerIDSeq,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.AreaID,
		&i.Latitude,
		&i.Longitude,
		&i.PackageID,
		&i.ActivationDate,
		&i.DueDate,
		&i.ConnectionMethod,
		&i.PppoeUsername,
		&i.PppoePassword,
		&i.MacAddress,
		&i.RouterID,
		&i.OdpPort,
		&i.CreditBalance,
		&i.Notes,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaxCustomerSeq = `-- name: GetMaxCustomerSeq :one
SELECT COALESCE(MAX(
    CAST(SUBSTRING(customer_id_seq FROM 'PLG-(\d+)') AS INTEGER)
), 0)::integer AS max_seq
FROM customers
WHERE tenant_id = $1
`

func (q *Queries) GetMaxCustomerSeq(ctx context.Context, tenantID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxCustomerSeq, tenantID)
	var max_seq int32
	err := row.Scan(&max_seq)
	return max_seq, err
}

const phoneExists = `-- name: PhoneExists :one
SELECT EXISTS(
    SELECT 1 FROM customers
    WHERE tenant_id = $1 AND phone = $2 AND id != $3 AND deleted_at IS NULL
) AS exists
`

type PhoneExistsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Phone    string      `json:"phone"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) PhoneExists(ctx context.Context, arg PhoneExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, phoneExists, arg.TenantID, arg.Phone, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const searchCustomersForPayment = `-- name: SearchCustomersForPayment :many
SELECT id, tenant_id, customer_id_seq, name, phone, email, address,
    area_id, latitude, longitude, package_id, activation_date,
    due_date, connection_method, pppoe_username, pppoe_password,
    mac_address, router_id, odp_port, credit_balance, notes, status,
    deleted_at, created_at, updated_at
FROM customers
WHERE tenant_id = $1
  AND (name ILIKE $2 OR customer_id_seq ILIKE $2 OR phone ILIKE $2)
  AND status IN ('aktif', 'isolir')
  AND deleted_at IS NULL
LIMIT 10
`

type SearchCustomersForPaymentParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
}

// Mencari pelanggan berdasarkan nama, customer_id_seq, atau telepon untuk quick payment.
// Mengembalikan maksimal 10 hasil, hanya status aktif atau isolir.
func (q *Queries) SearchCustomersForPayment(ctx context.Context, arg SearchCustomersForPaymentParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, searchCustomersForPayment, arg.TenantID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerIDSeq,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.AreaID,
			&i.Latitude,
			&i.Longitude,
			&i.PackageID,
			&i.ActivationDate,
			&i.DueDate,
			&i.ConnectionMethod,
			&i.PppoeUsername,
			&i.PppoePassword,
			&i.MacAddress,
			&i.RouterID,
			&i.OdpPort,
			&i.CreditBalance,
			&i.Notes,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCustomer = `-- name: SoftDeleteCustomer :exec
UPDATE customers SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCustomer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCustomer, id)
	return err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers SET
    name = $2,
    phone = $3,
    email = $4,
    address = $5,
    area_id = $6,
    latitude = $7,
    longitude = $8,
    package_id = $9,
    activation_date = $10,
    due_date = $11,
    connection_method = $12,
    pppoe_username = $13,
    pppoe_password = $14,
    mac_address = $15,
    router_id = $16,
    odp_port = $17,
    credit_balance = $18,
    notes = $19,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, customer_id_seq, name, phone, email, address,
    area_id, latitude, longitude, package_id, activation_date,
    due_date, connection_method, pppoe_username, pppoe_password,
    mac_address, router_id, odp_port, credit_balance, notes, status,
    deleted_at, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID               pgtype.UUID    `json:"id"`
	Name             string         `json:"name"`
	Phone            string         `json:"phone"`
	Email            pgtype.Text    `json:"email"`
	Address          string         `json:"address"`
	AreaID           pgtype.UUID    `json:"area_id"`
	Latitude         pgtype.Numeric `json:"latitude"`
	Longitude        pgtype.Numeric `json:"longitude"`
	PackageID        pgtype.UUID    `json:"package_id"`
	ActivationDate   pgtype.Date    `json:"activation_date"`
	DueDate          int32          `json:"due_date"`
	ConnectionMethod string         `json:"connection_method"`
	PppoeUsername    pgtype.Text    `json:"pppoe_username"`
	PppoePassword    pgtype.Text    `json:"pppoe_password"`
	MacAddress       pgtype.Text    `json:"mac_address"`
	RouterID         pgtype.UUID    `json:"router_id"`
	OdpPort          pgtype.Text    `json:"odp_port"`
	CreditBalance    int64          `json:"credit_balance"`
	Notes            pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.AreaID,
		arg.Latitude,
		arg.Longitude,
		arg.PackageID,
		arg.ActivationDate,
		arg.DueDate,
		arg.ConnectionMethod,
		arg.PppoeUsername,
		arg.PppoePassword,
		arg.MacAddress,
		arg.RouterID,
		arg.OdpPort,
		arg.CreditBalance,
		arg.Notes,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerIDSeq,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.AreaID,
		&i.Latitude,
		&i.Longitude,
		&i.PackageID,
		&i.ActivationDate,
		&i.DueDate,
		&i.ConnectionMethod,
		&i.PppoeUsername,
		&i.PppoePassword,
		&i.MacAddress,
		&i.RouterID,
		&i.OdpPort,
		&i.CreditBalance,
		&i.Notes,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomerPackage = `-- name: UpdateCustomerPackage :one
UPDATE customers SET package_id = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, customer_id_seq, name, phone, email, address,
    area_id, latitude, longitude, package_id, activation_date,
    due_date, connection_method, pppoe_username, pppoe_password,
    mac_address, router_id, odp_port, credit_balance, notes, status,
    deleted_at, created_at, updated_at
`

type UpdateCustomerPackageParams struct {
	ID        pgtype.UUID `json:"id"`
	PackageID pgtype.UUID `json:"package_id"`
}

func (q *Queries) UpdateCustomerPackage(ctx context.Context, arg UpdateCustomerPackageParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerPackage, arg.ID, arg.PackageID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerIDSeq,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.AreaID,
		&i.Latitude,
		&i.Longitude,
		&i.PackageID,
		&i.ActivationDate,
		&i.DueDate,
		&i.ConnectionMethod,
		&i.PppoeUsername,
		&i.PppoePassword,
		&i.MacAddress,
		&i.RouterID,
		&i.OdpPort,
		&i.CreditBalance,
		&i.Notes,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomerStatus = `-- name: UpdateCustomerStatus :one
UPDATE customers SET status = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, customer_id_seq, name, phone, email, address,
    area_id, latitude, longitude, package_id, activation_date,
    due_date, connection_method, pppoe_username, pppoe_password,
    mac_address, router_id, odp_port, credit_balance, notes, status,
    deleted_at, created_at, updated_at
`

type UpdateCustomerStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateCustomerStatus(ctx context.Context, arg UpdateCustomerStatusParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerStatus, arg.ID, arg.Status)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerIDSeq,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.AreaID,
		&i.Latitude,
		&i.Longitude,
		&i.PackageID,
		&i.ActivationDate,
		&i.DueDate,
		&i.ConnectionMethod,
		&i.PppoeUsername,
		&i.PppoePassword,
		&i.MacAddress,
		&i.RouterID,
		&i.OdpPort,
		&i.CreditBalance,
		&i.Notes,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
