// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: expenses.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one

INSERT INTO expenses (
    tenant_id, category_id, amount, description,
    expense_date, is_recurring, recurring_day, created_by_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, tenant_id, category_id, amount, description, expense_date, is_recurring, recurring_day, created_by_id, deleted_at, created_at, updated_at
`

type CreateExpenseParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	CategoryID   pgtype.UUID `json:"category_id"`
	Amount       int64       `json:"amount"`
	Description  string      `json:"description"`
	ExpenseDate  pgtype.Date `json:"expense_date"`
	IsRecurring  bool        `json:"is_recurring"`
	RecurringDay pgtype.Int4 `json:"recurring_day"`
	CreatedByID  pgtype.UUID `json:"created_by_id"`
}

// Kueri SQL untuk operasi CRUD tabel expenses.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel expenses dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Membuat pengeluaran baru dan mengembalikan semua kolom.
func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.TenantID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.ExpenseDate,
		arg.IsRecurring,
		arg.RecurringDay,
		arg.CreatedByID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.ExpenseDate,
		&i.IsRecurring,
		&i.RecurringDay,
		&i.CreatedByID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT e.id, e.tenant_id, e.category_id, e.amount, e.description, e.expense_date, e.is_recurring, e.recurring_day, e.created_by_id, e.deleted_at, e.created_at, e.updated_at,
    ec.name AS category_name
FROM expenses e
JOIN expense_categories ec ON ec.id = e.category_id
WHERE e.id = $1 AND e.deleted_at IS NULL
`

type GetExpenseByIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Amount       int64              `json:"amount"`
	Description  string             `json:"description"`
	ExpenseDate  pgtype.Date        `json:"expense_date"`
	IsRecurring  bool               `json:"is_recurring"`
	RecurringDay pgtype.Int4        `json:"recurring_day"`
	CreatedByID  pgtype.UUID        `json:"created_by_id"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CategoryName string             `json:"category_name"`
}

// Mengambil pengeluaran berdasarkan ID beserta nama kategori melalui JOIN.
func (q *Queries) GetExpenseByID(ctx context.Context, id pgtype.UUID) (GetExpenseByIDRow, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, id)
	var i GetExpenseByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.ExpenseDate,
		&i.IsRecurring,
		&i.RecurringDay,
		&i.CreatedByID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
	)
	return i, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT e.id, e.tenant_id, e.category_id, e.amount, e.description, e.expense_date, e.is_recurring, e.recurring_day, e.created_by_id, e.deleted_at, e.created_at, e.updated_at,
    ec.name AS category_name
FROM expenses e
JOIN expense_categories ec ON ec.id = e.category_id
WHERE e.tenant_id = $1
  AND e.expense_date >= $2
  AND e.expense_date <= $3
  AND ($4::uuid IS NULL OR e.category_id = $4::uuid)
  AND e.deleted_at IS NULL
ORDER BY e.expense_date DESC
`

type ListExpensesParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
	CategoryID    pgtype.UUID `json:"category_id"`
}

type ListExpensesRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Amount       int64              `json:"amount"`
	Description  string             `json:"description"`
	ExpenseDate  pgtype.Date        `json:"expense_date"`
	IsRecurring  bool               `json:"is_recurring"`
	RecurringDay pgtype.Int4        `json:"recurring_day"`
	CreatedByID  pgtype.UUID        `json:"created_by_id"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CategoryName string             `json:"category_name"`
}

// Mengambil daftar pengeluaran untuk tenant dengan filter periode dan kategori opsional.
// Menggunakan sqlc.narg untuk category_id opsional.
// Diurutkan berdasarkan expense_date descending (terbaru di atas).
func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.TenantID,
		arg.ExpenseDate,
		arg.ExpenseDate_2,
		arg.CategoryID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesRow{}
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.ExpenseDate,
			&i.IsRecurring,
			&i.RecurringDay,
			&i.CreatedByID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringExpenses = `-- name: ListRecurringExpenses :many
SELECT id, tenant_id, category_id, amount, description, expense_date, is_recurring, recurring_day, created_by_id, deleted_at, created_at, updated_at FROM expenses
WHERE is_recurring = true AND deleted_at IS NULL
`

// Mengambil semua pengeluaran berulang yang aktif (untuk auto-buat bulanan oleh worker).
func (q *Queries) ListRecurringExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listRecurringExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.ExpenseDate,
			&i.IsRecurring,
			&i.RecurringDay,
			&i.CreatedByID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteExpense = `-- name: SoftDeleteExpense :exec
UPDATE expenses SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

// Menghapus pengeluaran secara hapus lunak (atur deleted_at).
func (q *Queries) SoftDeleteExpense(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteExpense, id)
	return err
}

const sumExpensesByCategory = `-- name: SumExpensesByCategory :many
SELECT ec.name AS label,
    COALESCE(SUM(e.amount), 0)::bigint AS amount
FROM expenses e
JOIN expense_categories ec ON ec.id = e.category_id
WHERE e.tenant_id = $1
  AND e.expense_date >= $2
  AND e.expense_date <= $3
  AND e.deleted_at IS NULL
GROUP BY ec.name
ORDER BY amount DESC
`

type SumExpensesByCategoryParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

type SumExpensesByCategoryRow struct {
	Label  string `json:"label"`
	Amount int64  `json:"amount"`
}

// Menghitung total pengeluaran per kategori untuk laporan laba rugi.
// Mengembalikan nama kategori dan total nominal, diurutkan berdasarkan total terbesar.
func (q *Queries) SumExpensesByCategory(ctx context.Context, arg SumExpensesByCategoryParams) ([]SumExpensesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, sumExpensesByCategory, arg.TenantID, arg.ExpenseDate, arg.ExpenseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumExpensesByCategoryRow{}
	for rows.Next() {
		var i SumExpensesByCategoryRow
		if err := rows.Scan(&i.Label, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses SET
    category_id = $2,
    amount = $3,
    description = $4,
    expense_date = $5,
    is_recurring = $6,
    recurring_day = $7,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, category_id, amount, description, expense_date, is_recurring, recurring_day, created_by_id, deleted_at, created_at, updated_at
`

type UpdateExpenseParams struct {
	ID           pgtype.UUID `json:"id"`
	CategoryID   pgtype.UUID `json:"category_id"`
	Amount       int64       `json:"amount"`
	Description  string      `json:"description"`
	ExpenseDate  pgtype.Date `json:"expense_date"`
	IsRecurring  bool        `json:"is_recurring"`
	RecurringDay pgtype.Int4 `json:"recurring_day"`
}

// Memperbarui data pengeluaran (kategori, jumlah, deskripsi, tanggal, berulang).
func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.ExpenseDate,
		arg.IsRecurring,
		arg.RecurringDay,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.ExpenseDate,
		&i.IsRecurring,
		&i.RecurringDay,
		&i.CreatedByID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
