// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: invoice_sequences.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const nextInvoiceSequence = `-- name: NextInvoiceSequence :one

INSERT INTO invoice_sequences (
    tenant_id, year, month, last_seq
) VALUES (
    $1, $2, $3, 1
)
ON CONFLICT (tenant_id, year, month) DO UPDATE SET
    last_seq = invoice_sequences.last_seq + 1,
    updated_at = NOW()
RETURNING last_seq
`

type NextInvoiceSequenceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Year     int32       `json:"year"`
	Month    int32       `json:"month"`
}

// Kueri SQL untuk operasi pada tabel invoice_sequences.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel invoice_sequences dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Sequence digunakan untuk auto-increment nomor invoice per tenant per bulan.
// Mengambil dan increment sequence secara atomik menggunakan INSERT ON CONFLICT.
// Jika row belum ada untuk tenant/year/month, buat baru dengan last_seq = 1.
// Jika sudah ada, increment last_seq dan kembalikan nilai baru.
func (q *Queries) NextInvoiceSequence(ctx context.Context, arg NextInvoiceSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextInvoiceSequence, arg.TenantID, arg.Year, arg.Month)
	var last_seq int32
	err := row.Scan(&last_seq)
	return last_seq, err
}
