// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice_items.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateInvoiceItemsParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	InvoiceID   pgtype.UUID `json:"invoice_id"`
	ItemType    string      `json:"item_type"`
	Description string      `json:"description"`
	Quantity    int32       `json:"quantity"`
	UnitPrice   int64       `json:"unit_price"`
	Amount      int64       `json:"amount"`
	SortOrder   int32       `json:"sort_order"`
	Metadata    []byte      `json:"metadata"`
}

const deleteInvoiceItemsByInvoice = `-- name: DeleteInvoiceItemsByInvoice :exec
DELETE FROM invoice_items
WHERE invoice_id = $1
`

// Menghapus semua item untuk invoice tertentu (digunakan saat edit invoice).
func (q *Queries) DeleteInvoiceItemsByInvoice(ctx context.Context, invoiceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoiceItemsByInvoice, invoiceID)
	return err
}

const listInvoiceItemsByInvoice = `-- name: ListInvoiceItemsByInvoice :many
SELECT id, tenant_id, invoice_id, item_type, description, quantity, unit_price, amount, sort_order, metadata, created_at
FROM invoice_items
WHERE invoice_id = $1
ORDER BY sort_order ASC
`

// Mengambil semua item untuk invoice tertentu, diurutkan berdasarkan sort_order.
func (q *Queries) ListInvoiceItemsByInvoice(ctx context.Context, invoiceID pgtype.UUID) ([]InvoiceItem, error) {
	rows, err := q.db.Query(ctx, listInvoiceItemsByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceItem{}
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceID,
			&i.ItemType,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.Amount,
			&i.SortOrder,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
