// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: invoice_isolir.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOutstandingInvoices = `-- name: CountOutstandingInvoices :one
SELECT COUNT(*)
FROM invoices
WHERE customer_id = $1
  AND status NOT IN ('lunas', 'batal')
`

// Menghitung jumlah invoice outstanding untuk customer tertentu.
func (q *Queries) CountOutstandingInvoices(ctx context.Context, customerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOutstandingInvoices, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findOverdueForIsolir = `-- name: FindOverdueForIsolir :many

SELECT i.id, i.tenant_id, i.customer_id, i.invoice_number,
    i.period_month, i.period_year, i.due_date,
    i.subtotal, i.tax_amount, i.penalty_amount, i.discount_amount,
    i.credit_applied, i.total_amount, i.paid_amount,
    i.status, i.notes, i.is_prepaid, i.prepaid_months,
    i.version, i.created_at, i.updated_at
FROM invoices i
JOIN customers c ON c.id = i.customer_id
WHERE i.tenant_id = $1
  AND i.status IN ('belum_bayar', 'terlambat')
  AND $2::date > i.due_date + $3::integer
  AND c.status = 'aktif'
  AND c.deleted_at IS NULL
`

type FindOverdueForIsolirParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	CurrentDate     pgtype.Date `json:"current_date"`
	GracePeriodDays int32       `json:"grace_period_days"`
}

// Kueri SQL untuk operasi invoice terkait modul isolir.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel invoices dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Kueri ini digunakan oleh IsolirUsecase untuk mendeteksi invoice terlambat dan outstanding.
// Mengambil invoice yang sudah melewati grace period untuk proses auto-isolir.
// Hanya untuk pelanggan dengan status aktif (eligible untuk isolir).
// Mengembalikan field invoice beserta customer_id.
func (q *Queries) FindOverdueForIsolir(ctx context.Context, arg FindOverdueForIsolirParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, findOverdueForIsolir, arg.TenantID, arg.CurrentDate, arg.GracePeriodDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.InvoiceNumber,
			&i.PeriodMonth,
			&i.PeriodYear,
			&i.DueDate,
			&i.Subtotal,
			&i.TaxAmount,
			&i.PenaltyAmount,
			&i.DiscountAmount,
			&i.CreditApplied,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.Status,
			&i.Notes,
			&i.IsPrepaid,
			&i.PrepaidMonths,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOverdueForSuspend = `-- name: FindOverdueForSuspend :many
SELECT i.id, i.tenant_id, i.customer_id, i.invoice_number,
    i.period_month, i.period_year, i.due_date,
    i.subtotal, i.tax_amount, i.penalty_amount, i.discount_amount,
    i.credit_applied, i.total_amount, i.paid_amount,
    i.status, i.notes, i.is_prepaid, i.prepaid_months,
    i.version, i.created_at, i.updated_at
FROM invoices i
JOIN customers c ON c.id = i.customer_id
WHERE i.tenant_id = $1
  AND i.status IN ('belum_bayar', 'terlambat')
  AND $2::date > i.due_date + $3::integer
  AND c.status = 'isolir'
  AND c.deleted_at IS NULL
`

type FindOverdueForSuspendParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	CurrentDate pgtype.Date `json:"current_date"`
	SuspendDays int32       `json:"suspend_days"`
}

// Mengambil invoice yang sudah melewati suspend_days untuk proses suspend.
// Hanya untuk pelanggan dengan status isolir (eligible untuk suspend).
func (q *Queries) FindOverdueForSuspend(ctx context.Context, arg FindOverdueForSuspendParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, findOverdueForSuspend, arg.TenantID, arg.CurrentDate, arg.SuspendDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.InvoiceNumber,
			&i.PeriodMonth,
			&i.PeriodYear,
			&i.DueDate,
			&i.Subtotal,
			&i.TaxAmount,
			&i.PenaltyAmount,
			&i.DiscountAmount,
			&i.CreditApplied,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.Status,
			&i.Notes,
			&i.IsPrepaid,
			&i.PrepaidMonths,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasOutstandingInvoices = `-- name: HasOutstandingInvoices :one
SELECT EXISTS(
    SELECT 1 FROM invoices
    WHERE customer_id = $1
      AND status NOT IN ('lunas', 'batal')
) AS exists
`

// Mengecek apakah customer masih punya invoice yang belum lunas.
// Invoice outstanding = status bukan lunas dan bukan batal.
func (q *Queries) HasOutstandingInvoices(ctx context.Context, customerID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasOutstandingInvoices, customerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const sumOutstandingAmount = `-- name: SumOutstandingAmount :one
SELECT COALESCE(SUM(total_amount), 0)::bigint AS total
FROM invoices
WHERE customer_id = $1
  AND status NOT IN ('lunas', 'batal')
`

// Menghitung total tagihan outstanding untuk customer tertentu.
// Mengembalikan 0 jika tidak ada invoice outstanding.
func (q *Queries) SumOutstandingAmount(ctx context.Context, customerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumOutstandingAmount, customerID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
