// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice_audit_logs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoiceAuditLog = `-- name: CreateInvoiceAuditLog :one

INSERT INTO invoice_audit_logs (
    tenant_id, invoice_id, action, actor_id, actor_name, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, tenant_id, invoice_id, action, actor_id, actor_name, metadata, created_at
`

type CreateInvoiceAuditLogParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	InvoiceID pgtype.UUID `json:"invoice_id"`
	Action    string      `json:"action"`
	ActorID   string      `json:"actor_id"`
	ActorName string      `json:"actor_name"`
	Metadata  []byte      `json:"metadata"`
}

// Query SQL untuk operasi pada tabel invoice_audit_logs.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel invoice_audit_logs bersifat append-only (hanya SELECT dan INSERT).
// Dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Membuat satu entri audit log invoice dan mengembalikan semua kolom.
func (q *Queries) CreateInvoiceAuditLog(ctx context.Context, arg CreateInvoiceAuditLogParams) (InvoiceAuditLog, error) {
	row := q.db.QueryRow(ctx, createInvoiceAuditLog,
		arg.TenantID,
		arg.InvoiceID,
		arg.Action,
		arg.ActorID,
		arg.ActorName,
		arg.Metadata,
	)
	var i InvoiceAuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvoiceID,
		&i.Action,
		&i.ActorID,
		&i.ActorName,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByInvoice = `-- name: ListAuditLogsByInvoice :many
SELECT id, tenant_id, invoice_id, action, actor_id, actor_name, metadata, created_at
FROM invoice_audit_logs
WHERE invoice_id = $1
ORDER BY created_at ASC
`

// Mengambil semua audit log untuk invoice tertentu, diurutkan berdasarkan created_at.
func (q *Queries) ListAuditLogsByInvoice(ctx context.Context, invoiceID pgtype.UUID) ([]InvoiceAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceAuditLog{}
	for rows.Next() {
		var i InvoiceAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceID,
			&i.Action,
			&i.ActorID,
			&i.ActorName,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
