// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice_payments.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoicePayment = `-- name: CreateInvoicePayment :one

INSERT INTO invoice_payments (
    tenant_id, invoice_id, amount, payment_method, payment_date,
    reference_number, notes, recorded_by_id, recorded_by_name
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
RETURNING id, tenant_id, invoice_id, amount, payment_method, payment_date, reference_number, notes, recorded_by_id, recorded_by_name, voided, voided_at, voided_by, void_reason, created_at, receipt_number, receipt_group_id, proof_image_url
`

type CreateInvoicePaymentParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	InvoiceID       pgtype.UUID `json:"invoice_id"`
	Amount          int64       `json:"amount"`
	PaymentMethod   string      `json:"payment_method"`
	PaymentDate     pgtype.Date `json:"payment_date"`
	ReferenceNumber pgtype.Text `json:"reference_number"`
	Notes           pgtype.Text `json:"notes"`
	RecordedByID    pgtype.UUID `json:"recorded_by_id"`
	RecordedByName  string      `json:"recorded_by_name"`
}

// Query SQL untuk operasi CRUD tabel invoice_payments.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel invoice_payments dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Membuat catatan pembayaran baru dan mengembalikan semua kolom.
func (q *Queries) CreateInvoicePayment(ctx context.Context, arg CreateInvoicePaymentParams) (InvoicePayment, error) {
	row := q.db.QueryRow(ctx, createInvoicePayment,
		arg.TenantID,
		arg.InvoiceID,
		arg.Amount,
		arg.PaymentMethod,
		arg.PaymentDate,
		arg.ReferenceNumber,
		arg.Notes,
		arg.RecordedByID,
		arg.RecordedByName,
	)
	var i InvoicePayment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvoiceID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentDate,
		&i.ReferenceNumber,
		&i.Notes,
		&i.RecordedByID,
		&i.RecordedByName,
		&i.Voided,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedAt,
		&i.ReceiptNumber,
		&i.ReceiptGroupID,
		&i.ProofImageUrl,
	)
	return i, err
}

const findDuplicatePayment = `-- name: FindDuplicatePayment :one
SELECT EXISTS(
    SELECT 1 FROM invoice_payments ip
    JOIN invoices i ON i.id = ip.invoice_id
    WHERE i.customer_id = $1
      AND ip.amount = $2
      AND ip.payment_method = $3
      AND ip.payment_date = $4
      AND ip.voided = false
      AND ip.created_at >= NOW() - INTERVAL '24 hours'
) AS exists
`

type FindDuplicatePaymentParams struct {
	CustomerID    pgtype.UUID `json:"customer_id"`
	Amount        int64       `json:"amount"`
	PaymentMethod string      `json:"payment_method"`
	PaymentDate   pgtype.Date `json:"payment_date"`
}

// Mengecek apakah ada pembayaran duplikat dalam 24 jam terakhir.
// Duplikat didefinisikan sebagai pembayaran dengan customer_id, amount, payment_method,
// dan payment_date yang sama, belum di-void.
func (q *Queries) FindDuplicatePayment(ctx context.Context, arg FindDuplicatePaymentParams) (bool, error) {
	row := q.db.QueryRow(ctx, findDuplicatePayment,
		arg.CustomerID,
		arg.Amount,
		arg.PaymentMethod,
		arg.PaymentDate,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT ip.id, ip.tenant_id, ip.invoice_id, ip.amount, ip.payment_method, ip.payment_date, ip.reference_number, ip.notes, ip.recorded_by_id, ip.recorded_by_name, ip.voided, ip.voided_at, ip.voided_by, ip.void_reason, ip.created_at, ip.receipt_number, ip.receipt_group_id, ip.proof_image_url,
    i.invoice_number AS invoice_number
FROM invoice_payments ip
JOIN invoices i ON i.id = ip.invoice_id
WHERE ip.id = $1
`

type GetPaymentByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	InvoiceID       pgtype.UUID        `json:"invoice_id"`
	Amount          int64              `json:"amount"`
	PaymentMethod   string             `json:"payment_method"`
	PaymentDate     pgtype.Date        `json:"payment_date"`
	ReferenceNumber pgtype.Text        `json:"reference_number"`
	Notes           pgtype.Text        `json:"notes"`
	RecordedByID    pgtype.UUID        `json:"recorded_by_id"`
	RecordedByName  string             `json:"recorded_by_name"`
	Voided          bool               `json:"voided"`
	VoidedAt        pgtype.Timestamptz `json:"voided_at"`
	VoidedBy        pgtype.Text        `json:"voided_by"`
	VoidReason      pgtype.Text        `json:"void_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ReceiptNumber   pgtype.Text        `json:"receipt_number"`
	ReceiptGroupID  pgtype.UUID        `json:"receipt_group_id"`
	ProofImageUrl   pgtype.Text        `json:"proof_image_url"`
	InvoiceNumber   string             `json:"invoice_number"`
}

// Mengambil satu pembayaran berdasarkan ID beserta nomor invoice melalui JOIN.
func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (GetPaymentByIDRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i GetPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvoiceID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentDate,
		&i.ReferenceNumber,
		&i.Notes,
		&i.RecordedByID,
		&i.RecordedByName,
		&i.Voided,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedAt,
		&i.ReceiptNumber,
		&i.ReceiptGroupID,
		&i.ProofImageUrl,
		&i.InvoiceNumber,
	)
	return i, err
}

const getPaymentSummaryByMethod = `-- name: GetPaymentSummaryByMethod :many
SELECT
    payment_method,
    COUNT(*)::bigint AS count,
    COALESCE(SUM(amount), 0)::bigint AS total_amount
FROM invoice_payments
WHERE voided = false
  AND EXTRACT(MONTH FROM payment_date) = $1
  AND EXTRACT(YEAR FROM payment_date) = $2
GROUP BY payment_method
`

type GetPaymentSummaryByMethodParams struct {
	PaymentDate   pgtype.Date `json:"payment_date"`
	PaymentDate_2 pgtype.Date `json:"payment_date_2"`
}

type GetPaymentSummaryByMethodRow struct {
	PaymentMethod string `json:"payment_method"`
	Count         int64  `json:"count"`
	TotalAmount   int64  `json:"total_amount"`
}

// Mengambil ringkasan pembayaran per metode pembayaran untuk bulan dan tahun tertentu.
func (q *Queries) GetPaymentSummaryByMethod(ctx context.Context, arg GetPaymentSummaryByMethodParams) ([]GetPaymentSummaryByMethodRow, error) {
	rows, err := q.db.Query(ctx, getPaymentSummaryByMethod, arg.PaymentDate, arg.PaymentDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPaymentSummaryByMethodRow{}
	for rows.Next() {
		var i GetPaymentSummaryByMethodRow
		if err := rows.Scan(&i.PaymentMethod, &i.Count, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentSummaryMonth = `-- name: GetPaymentSummaryMonth :one
SELECT
    COUNT(*)::bigint AS count,
    COALESCE(SUM(amount), 0)::bigint AS total_amount
FROM invoice_payments
WHERE voided = false
  AND EXTRACT(MONTH FROM payment_date) = $1
  AND EXTRACT(YEAR FROM payment_date) = $2
`

type GetPaymentSummaryMonthParams struct {
	PaymentDate   pgtype.Date `json:"payment_date"`
	PaymentDate_2 pgtype.Date `json:"payment_date_2"`
}

type GetPaymentSummaryMonthRow struct {
	Count       int64 `json:"count"`
	TotalAmount int64 `json:"total_amount"`
}

// Mengambil ringkasan pembayaran untuk bulan dan tahun tertentu.
func (q *Queries) GetPaymentSummaryMonth(ctx context.Context, arg GetPaymentSummaryMonthParams) (GetPaymentSummaryMonthRow, error) {
	row := q.db.QueryRow(ctx, getPaymentSummaryMonth, arg.PaymentDate, arg.PaymentDate_2)
	var i GetPaymentSummaryMonthRow
	err := row.Scan(&i.Count, &i.TotalAmount)
	return i, err
}

const getPaymentSummaryToday = `-- name: GetPaymentSummaryToday :one
SELECT
    COUNT(*)::bigint AS count,
    COALESCE(SUM(amount), 0)::bigint AS total_amount
FROM invoice_payments
WHERE voided = false
  AND (created_at AT TIME ZONE $1)::date = (NOW() AT TIME ZONE $1)::date
`

type GetPaymentSummaryTodayRow struct {
	Count       int64 `json:"count"`
	TotalAmount int64 `json:"total_amount"`
}

// Mengambil ringkasan pembayaran hari ini (jumlah dan total nominal).
// Menggunakan parameter timezone untuk konversi ke tanggal lokal tenant.
func (q *Queries) GetPaymentSummaryToday(ctx context.Context, timezone pgtype.Interval) (GetPaymentSummaryTodayRow, error) {
	row := q.db.QueryRow(ctx, getPaymentSummaryToday, timezone)
	var i GetPaymentSummaryTodayRow
	err := row.Scan(&i.Count, &i.TotalAmount)
	return i, err
}

const listPaymentsByInvoice = `-- name: ListPaymentsByInvoice :many
SELECT id, tenant_id, invoice_id, amount, payment_method, payment_date, reference_number, notes, recorded_by_id, recorded_by_name, voided, voided_at, voided_by, void_reason, created_at, receipt_number, receipt_group_id, proof_image_url
FROM invoice_payments
WHERE invoice_id = $1 AND voided = false
ORDER BY created_at ASC
`

// Mengambil semua pembayaran non-void untuk invoice tertentu, diurutkan berdasarkan created_at.
func (q *Queries) ListPaymentsByInvoice(ctx context.Context, invoiceID pgtype.UUID) ([]InvoicePayment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoicePayment{}
	for rows.Next() {
		var i InvoicePayment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceID,
			&i.Amount,
			&i.PaymentMethod,
			&i.PaymentDate,
			&i.ReferenceNumber,
			&i.Notes,
			&i.RecordedByID,
			&i.RecordedByName,
			&i.Voided,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
			&i.CreatedAt,
			&i.ReceiptNumber,
			&i.ReceiptGroupID,
			&i.ProofImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const voidPayment = `-- name: VoidPayment :exec
UPDATE invoice_payments SET
    voided = true,
    voided_at = NOW(),
    voided_by = $2,
    void_reason = $3
WHERE id = $1
`

type VoidPaymentParams struct {
	ID         pgtype.UUID `json:"id"`
	VoidedBy   pgtype.Text `json:"voided_by"`
	VoidReason pgtype.Text `json:"void_reason"`
}

// Menandai pembayaran sebagai void dengan alasan dan waktu void.
func (q *Queries) VoidPayment(ctx context.Context, arg VoidPaymentParams) error {
	_, err := q.db.Exec(ctx, voidPayment, arg.ID, arg.VoidedBy, arg.VoidReason)
	return err
}
