// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: kpi_targets.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getKPITargetByTenant = `-- name: GetKPITargetByTenant :one

SELECT id, tenant_id, monthly_revenue_target, collection_rate_target, max_receivables, new_customers_monthly_target, max_churn_rate, total_customers_target, sla_uptime_target, max_active_alarms, min_signal_quality_percentage, created_at, updated_at FROM kpi_targets
WHERE tenant_id = $1
`

// Kueri SQL untuk operasi CRUD tabel kpi_targets.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel kpi_targets dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Setiap tenant hanya memiliki satu baris kpi_targets (UNIQUE pada tenant_id).
// Mengambil target KPI berdasarkan tenant_id.
func (q *Queries) GetKPITargetByTenant(ctx context.Context, tenantID pgtype.UUID) (KpiTarget, error) {
	row := q.db.QueryRow(ctx, getKPITargetByTenant, tenantID)
	var i KpiTarget
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MonthlyRevenueTarget,
		&i.CollectionRateTarget,
		&i.MaxReceivables,
		&i.NewCustomersMonthlyTarget,
		&i.MaxChurnRate,
		&i.TotalCustomersTarget,
		&i.SlaUptimeTarget,
		&i.MaxActiveAlarms,
		&i.MinSignalQualityPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertKPITarget = `-- name: UpsertKPITarget :one
INSERT INTO kpi_targets (
    tenant_id,
    monthly_revenue_target,
    collection_rate_target,
    max_receivables,
    new_customers_monthly_target,
    max_churn_rate,
    total_customers_target,
    sla_uptime_target,
    max_active_alarms,
    min_signal_quality_percentage
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (tenant_id) DO UPDATE SET
    monthly_revenue_target = EXCLUDED.monthly_revenue_target,
    collection_rate_target = EXCLUDED.collection_rate_target,
    max_receivables = EXCLUDED.max_receivables,
    new_customers_monthly_target = EXCLUDED.new_customers_monthly_target,
    max_churn_rate = EXCLUDED.max_churn_rate,
    total_customers_target = EXCLUDED.total_customers_target,
    sla_uptime_target = EXCLUDED.sla_uptime_target,
    max_active_alarms = EXCLUDED.max_active_alarms,
    min_signal_quality_percentage = EXCLUDED.min_signal_quality_percentage,
    updated_at = NOW()
RETURNING id, tenant_id, monthly_revenue_target, collection_rate_target, max_receivables, new_customers_monthly_target, max_churn_rate, total_customers_target, sla_uptime_target, max_active_alarms, min_signal_quality_percentage, created_at, updated_at
`

type UpsertKPITargetParams struct {
	TenantID                   pgtype.UUID    `json:"tenant_id"`
	MonthlyRevenueTarget       pgtype.Int8    `json:"monthly_revenue_target"`
	CollectionRateTarget       pgtype.Numeric `json:"collection_rate_target"`
	MaxReceivables             pgtype.Int8    `json:"max_receivables"`
	NewCustomersMonthlyTarget  pgtype.Int4    `json:"new_customers_monthly_target"`
	MaxChurnRate               pgtype.Numeric `json:"max_churn_rate"`
	TotalCustomersTarget       pgtype.Int4    `json:"total_customers_target"`
	SlaUptimeTarget            pgtype.Numeric `json:"sla_uptime_target"`
	MaxActiveAlarms            pgtype.Int4    `json:"max_active_alarms"`
	MinSignalQualityPercentage pgtype.Numeric `json:"min_signal_quality_percentage"`
}

// Membuat atau memperbarui target KPI untuk tenant.
// Jika tenant sudah memiliki target, semua kolom diperbarui.
func (q *Queries) UpsertKPITarget(ctx context.Context, arg UpsertKPITargetParams) (KpiTarget, error) {
	row := q.db.QueryRow(ctx, upsertKPITarget,
		arg.TenantID,
		arg.MonthlyRevenueTarget,
		arg.CollectionRateTarget,
		arg.MaxReceivables,
		arg.NewCustomersMonthlyTarget,
		arg.MaxChurnRate,
		arg.TotalCustomersTarget,
		arg.SlaUptimeTarget,
		arg.MaxActiveAlarms,
		arg.MinSignalQualityPercentage,
	)
	var i KpiTarget
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MonthlyRevenueTarget,
		&i.CollectionRateTarget,
		&i.MaxReceivables,
		&i.NewCustomersMonthlyTarget,
		&i.MaxChurnRate,
		&i.TotalCustomersTarget,
		&i.SlaUptimeTarget,
		&i.MaxActiveAlarms,
		&i.MinSignalQualityPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
