// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Area struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	OdpID       pgtype.Text        `json:"odp_id"`
	CenterLat   pgtype.Numeric     `json:"center_lat"`
	CenterLng   pgtype.Numeric     `json:"center_lng"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Action     string             `json:"action"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	ActorName  string             `json:"actor_name"`
	Changes    []byte             `json:"changes"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type BillingSetting struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	GenerateDays       int32              `json:"generate_days"`
	GracePeriodDays    int32              `json:"grace_period_days"`
	SuspendDays        int32              `json:"suspend_days"`
	TaxEnabled         bool               `json:"tax_enabled"`
	TaxRate            pgtype.Numeric     `json:"tax_rate"`
	PenaltyEnabled     bool               `json:"penalty_enabled"`
	PenaltyType        string             `json:"penalty_type"`
	PenaltyAmount      int64              `json:"penalty_amount"`
	PenaltyPercentage  pgtype.Numeric     `json:"penalty_percentage"`
	PenaltyDailyAmount int64              `json:"penalty_daily_amount"`
	PenaltyMaxAmount   int64              `json:"penalty_max_amount"`
	InvoicePrefix      string             `json:"invoice_prefix"`
	NewCustomerBilling string             `json:"new_customer_billing"`
	Timezone           string             `json:"timezone"`
	AutoIsolir         bool               `json:"auto_isolir"`
	AutoOpenIsolir     bool               `json:"auto_open_isolir"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type CreditNote struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	CreditNoteNumber string             `json:"credit_note_number"`
	InvoiceID        pgtype.UUID        `json:"invoice_id"`
	Amount           int64              `json:"amount"`
	Reason           string             `json:"reason"`
	ApplyToCredit    bool               `json:"apply_to_credit"`
	CreatedByID      string             `json:"created_by_id"`
	CreatedByName    string             `json:"created_by_name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type CustomReportTemplate struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	Name               string             `json:"name"`
	Metrics            []byte             `json:"metrics"`
	GroupBy            string             `json:"group_by"`
	SubGroupBy         pgtype.Text        `json:"sub_group_by"`
	DisplayType        string             `json:"display_type"`
	DefaultPeriodRange pgtype.Text        `json:"default_period_range"`
	CreatedByID        pgtype.UUID        `json:"created_by_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	CustomerIDSeq    pgtype.Text        `json:"customer_id_seq"`
	Name             string             `json:"name"`
	Phone            string             `json:"phone"`
	Email            pgtype.Text        `json:"email"`
	Address          string             `json:"address"`
	AreaID           pgtype.UUID        `json:"area_id"`
	Latitude         pgtype.Numeric     `json:"latitude"`
	Longitude        pgtype.Numeric     `json:"longitude"`
	PackageID        pgtype.UUID        `json:"package_id"`
	ActivationDate   pgtype.Date        `json:"activation_date"`
	DueDate          int32              `json:"due_date"`
	ConnectionMethod string             `json:"connection_method"`
	PppoeUsername    pgtype.Text        `json:"pppoe_username"`
	PppoePassword    pgtype.Text        `json:"pppoe_password"`
	MacAddress       pgtype.Text        `json:"mac_address"`
	RouterID         pgtype.UUID        `json:"router_id"`
	OdpPort          pgtype.Text        `json:"odp_port"`
	CreditBalance    int64              `json:"credit_balance"`
	Notes            pgtype.Text        `json:"notes"`
	Status           string             `json:"status"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type CustomerRecurringItem struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	Description string             `json:"description"`
	Amount      int64              `json:"amount"`
	IsActive    bool               `json:"is_active"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DebitNote struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	DebitNoteNumber string             `json:"debit_note_number"`
	CustomerID      pgtype.UUID        `json:"customer_id"`
	DueDate         pgtype.Date        `json:"due_date"`
	TotalAmount     int64              `json:"total_amount"`
	InvoiceID       pgtype.UUID        `json:"invoice_id"`
	CreatedByID     string             `json:"created_by_id"`
	CreatedByName   string             `json:"created_by_name"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type DebitNoteItem struct {
	ID          pgtype.UUID `json:"id"`
	DebitNoteID pgtype.UUID `json:"debit_note_id"`
	Description string      `json:"description"`
	Amount      int64       `json:"amount"`
}

type EmailVerification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Expense struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Amount       int64              `json:"amount"`
	Description  string             `json:"description"`
	ExpenseDate  pgtype.Date        `json:"expense_date"`
	IsRecurring  bool               `json:"is_recurring"`
	RecurringDay pgtype.Int4        `json:"recurring_day"`
	CreatedByID  pgtype.UUID        `json:"created_by_id"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ExpenseCategory struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	IsDefault bool               `json:"is_default"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Invoice struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	CustomerID     pgtype.UUID        `json:"customer_id"`
	InvoiceNumber  string             `json:"invoice_number"`
	PeriodMonth    int32              `json:"period_month"`
	PeriodYear     int32              `json:"period_year"`
	DueDate        pgtype.Date        `json:"due_date"`
	Subtotal       int64              `json:"subtotal"`
	TaxAmount      int64              `json:"tax_amount"`
	PenaltyAmount  int64              `json:"penalty_amount"`
	DiscountAmount int64              `json:"discount_amount"`
	CreditApplied  int64              `json:"credit_applied"`
	TotalAmount    int64              `json:"total_amount"`
	PaidAmount     int64              `json:"paid_amount"`
	Status         string             `json:"status"`
	Notes          pgtype.Text        `json:"notes"`
	IsPrepaid      bool               `json:"is_prepaid"`
	PrepaidMonths  pgtype.Int4        `json:"prepaid_months"`
	Version        int32              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type InvoiceAuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	InvoiceID pgtype.UUID        `json:"invoice_id"`
	Action    string             `json:"action"`
	ActorID   string             `json:"actor_id"`
	ActorName string             `json:"actor_name"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type InvoiceItem struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	InvoiceID   pgtype.UUID        `json:"invoice_id"`
	ItemType    string             `json:"item_type"`
	Description string             `json:"description"`
	Quantity    int32              `json:"quantity"`
	UnitPrice   int64              `json:"unit_price"`
	Amount      int64              `json:"amount"`
	SortOrder   int32              `json:"sort_order"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type InvoicePayment struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	InvoiceID       pgtype.UUID        `json:"invoice_id"`
	Amount          int64              `json:"amount"`
	PaymentMethod   string             `json:"payment_method"`
	PaymentDate     pgtype.Date        `json:"payment_date"`
	ReferenceNumber pgtype.Text        `json:"reference_number"`
	Notes           pgtype.Text        `json:"notes"`
	RecordedByID    pgtype.UUID        `json:"recorded_by_id"`
	RecordedByName  string             `json:"recorded_by_name"`
	Voided          bool               `json:"voided"`
	VoidedAt        pgtype.Timestamptz `json:"voided_at"`
	VoidedBy        pgtype.Text        `json:"voided_by"`
	VoidReason      pgtype.Text        `json:"void_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ReceiptNumber   pgtype.Text        `json:"receipt_number"`
	ReceiptGroupID  pgtype.UUID        `json:"receipt_group_id"`
	ProofImageUrl   pgtype.Text        `json:"proof_image_url"`
}

type InvoiceSequence struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Year      int32              `json:"year"`
	Month     int32              `json:"month"`
	LastSeq   int32              `json:"last_seq"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type KpiTarget struct {
	ID                         pgtype.UUID        `json:"id"`
	TenantID                   pgtype.UUID        `json:"tenant_id"`
	MonthlyRevenueTarget       pgtype.Int8        `json:"monthly_revenue_target"`
	CollectionRateTarget       pgtype.Numeric     `json:"collection_rate_target"`
	MaxReceivables             pgtype.Int8        `json:"max_receivables"`
	NewCustomersMonthlyTarget  pgtype.Int4        `json:"new_customers_monthly_target"`
	MaxChurnRate               pgtype.Numeric     `json:"max_churn_rate"`
	TotalCustomersTarget       pgtype.Int4        `json:"total_customers_target"`
	SlaUptimeTarget            pgtype.Numeric     `json:"sla_uptime_target"`
	MaxActiveAlarms            pgtype.Int4        `json:"max_active_alarms"`
	MinSignalQualityPercentage pgtype.Numeric     `json:"min_signal_quality_percentage"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type Package struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	Type                string             `json:"type"`
	Name                string             `json:"name"`
	Description         pgtype.Text        `json:"description"`
	IsActive            bool               `json:"is_active"`
	DownloadMbps        int32              `json:"download_mbps"`
	UploadMbps          int32              `json:"upload_mbps"`
	BandwidthType       pgtype.Text        `json:"bandwidth_type"`
	BurstDownloadMbps   pgtype.Int4        `json:"burst_download_mbps"`
	BurstUploadMbps     pgtype.Int4        `json:"burst_upload_mbps"`
	BurstThresholdMbps  pgtype.Int4        `json:"burst_threshold_mbps"`
	BurstTimeSeconds    pgtype.Int4        `json:"burst_time_seconds"`
	QuotaType           string             `json:"quota_type"`
	QuotaMb             pgtype.Int4        `json:"quota_mb"`
	QuotaAction         pgtype.Text        `json:"quota_action"`
	ThrottleMbps        pgtype.Int4        `json:"throttle_mbps"`
	MonthlyPrice        pgtype.Int8        `json:"monthly_price"`
	InstallationFee     int64              `json:"installation_fee"`
	SellPrice           pgtype.Int8        `json:"sell_price"`
	ResellerPrice       pgtype.Int8        `json:"reseller_price"`
	DurationValue       pgtype.Int4        `json:"duration_value"`
	DurationUnit        pgtype.Text        `json:"duration_unit"`
	SharedUsers         int32              `json:"shared_users"`
	MikrotikProfileName pgtype.Text        `json:"mikrotik_profile_name"`
	AddressPool         pgtype.Text        `json:"address_pool"`
	ParentQueue         pgtype.Text        `json:"parent_queue"`
	HotspotProfileName  pgtype.Text        `json:"hotspot_profile_name"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type PasswordReset struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PaymentGatewayConfig struct {
	ID                     pgtype.UUID        `json:"id"`
	TenantID               pgtype.UUID        `json:"tenant_id"`
	GatewayProvider        string             `json:"gateway_provider"`
	IsActive               bool               `json:"is_active"`
	ApiKeyEncrypted        string             `json:"api_key_encrypted"`
	WebhookSecretEncrypted string             `json:"webhook_secret_encrypted"`
	EnabledMethods         []byte             `json:"enabled_methods"`
	PaymentLinkExpiryDays  int32              `json:"payment_link_expiry_days"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type PaymentLink struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	CustomerID      pgtype.UUID        `json:"customer_id"`
	GatewayProvider string             `json:"gateway_provider"`
	GatewayConfigID pgtype.UUID        `json:"gateway_config_id"`
	ExternalID      string             `json:"external_id"`
	PaymentUrl      string             `json:"payment_url"`
	Amount          int64              `json:"amount"`
	Status          string             `json:"status"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	PaidMethod      pgtype.Text        `json:"paid_method"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PaymentLinkInvoice struct {
	ID            pgtype.UUID `json:"id"`
	PaymentLinkID pgtype.UUID `json:"payment_link_id"`
	InvoiceID     pgtype.UUID `json:"invoice_id"`
}

type PendingSync struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	OperationType string             `json:"operation_type"`
	Status        string             `json:"status"`
	RetryCount    int32              `json:"retry_count"`
	MaxRetries    int32              `json:"max_retries"`
	LastRetryAt   pgtype.Timestamptz `json:"last_retry_at"`
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ReceiptSequence struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Year      int32              `json:"year"`
	Month     int32              `json:"month"`
	LastSeq   int32              `json:"last_seq"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ReportJob struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ReportType  string             `json:"report_type"`
	Format      string             `json:"format"`
	Filters     []byte             `json:"filters"`
	Status      string             `json:"status"`
	DownloadUrl pgtype.Text        `json:"download_url"`
	Error       pgtype.Text        `json:"error"`
	RequestedBy pgtype.UUID        `json:"requested_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ReportSchedule struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ReportType   string             `json:"report_type"`
	ScheduleType string             `json:"schedule_type"`
	Format       string             `json:"format"`
	Recipients   []byte             `json:"recipients"`
	Filters      []byte             `json:"filters"`
	IsActive     bool               `json:"is_active"`
	CreatedByID  pgtype.UUID        `json:"created_by_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Reseller struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	Name               string             `json:"name"`
	Phone              string             `json:"phone"`
	Email              pgtype.Text        `json:"email"`
	Address            pgtype.Text        `json:"address"`
	PasswordHash       string             `json:"password_hash"`
	Balance            int64              `json:"balance"`
	DailyPurchaseLimit int32              `json:"daily_purchase_limit"`
	Status             string             `json:"status"`
	LastLogin          pgtype.Timestamptz `json:"last_login"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ResellerTransaction struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	ResellerID    pgtype.UUID        `json:"reseller_id"`
	Type          string             `json:"type"`
	Amount        int64              `json:"amount"`
	BalanceBefore int64              `json:"balance_before"`
	BalanceAfter  int64              `json:"balance_after"`
	ReferenceID   pgtype.UUID        `json:"reference_id"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Domain    pgtype.Text        `json:"domain"`
	Plan      string             `json:"plan"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Name          string             `json:"name"`
	Email         string             `json:"email"`
	Phone         pgtype.Text        `json:"phone"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	Role          string             `json:"role"`
	EmailVerified bool               `json:"email_verified"`
	GoogleID      pgtype.Text        `json:"google_id"`
	Status        string             `json:"status"`
	LastLogin     pgtype.Timestamptz `json:"last_login"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Voucher struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	Code                  string             `json:"code"`
	PackageID             pgtype.UUID        `json:"package_id"`
	ResellerID            pgtype.UUID        `json:"reseller_id"`
	Status                string             `json:"status"`
	SellPriceSnapshot     pgtype.Int8        `json:"sell_price_snapshot"`
	ResellerPriceSnapshot pgtype.Int8        `json:"reseller_price_snapshot"`
	PurchasedAt           pgtype.Timestamptz `json:"purchased_at"`
	ActivatedAt           pgtype.Timestamptz `json:"activated_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	VoidedAt              pgtype.Timestamptz `json:"voided_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type VoucherAuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	VoucherID pgtype.UUID        `json:"voucher_id"`
	Action    string             `json:"action"`
	ActorID   string             `json:"actor_id"`
	ActorName string             `json:"actor_name"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WebhookLog struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	GatewayProvider  string             `json:"gateway_provider"`
	EventType        string             `json:"event_type"`
	ExternalID       string             `json:"external_id"`
	RequestBody      []byte             `json:"request_body"`
	SourceIp         netip.Addr         `json:"source_ip"`
	SignatureValid   pgtype.Bool        `json:"signature_valid"`
	ProcessingStatus string             `json:"processing_status"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
