// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packages.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPackage = `-- name: CreatePackage :one

INSERT INTO packages (
    tenant_id, type, name, description, is_active,
    download_mbps, upload_mbps, bandwidth_type,
    burst_download_mbps, burst_upload_mbps, burst_threshold_mbps, burst_time_seconds,
    quota_type, quota_mb, quota_action, throttle_mbps,
    monthly_price, installation_fee, sell_price, reseller_price,
    duration_value, duration_unit, shared_users,
    mikrotik_profile_name, address_pool, parent_queue, hotspot_profile_name
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15, $16,
    $17, $18, $19, $20,
    $21, $22, $23,
    $24, $25, $26, $27
)
RETURNING id, tenant_id, type, name, description, is_active, download_mbps, upload_mbps, bandwidth_type, burst_download_mbps, burst_upload_mbps, burst_threshold_mbps, burst_time_seconds, quota_type, quota_mb, quota_action, throttle_mbps, monthly_price, installation_fee, sell_price, reseller_price, duration_value, duration_unit, shared_users, mikrotik_profile_name, address_pool, parent_queue, hotspot_profile_name, created_at, updated_at
`

type CreatePackageParams struct {
	TenantID            pgtype.UUID `json:"tenant_id"`
	Type                string      `json:"type"`
	Name                string      `json:"name"`
	Description         pgtype.Text `json:"description"`
	IsActive            bool        `json:"is_active"`
	DownloadMbps        int32       `json:"download_mbps"`
	UploadMbps          int32       `json:"upload_mbps"`
	BandwidthType       pgtype.Text `json:"bandwidth_type"`
	BurstDownloadMbps   pgtype.Int4 `json:"burst_download_mbps"`
	BurstUploadMbps     pgtype.Int4 `json:"burst_upload_mbps"`
	BurstThresholdMbps  pgtype.Int4 `json:"burst_threshold_mbps"`
	BurstTimeSeconds    pgtype.Int4 `json:"burst_time_seconds"`
	QuotaType           string      `json:"quota_type"`
	QuotaMb             pgtype.Int4 `json:"quota_mb"`
	QuotaAction         pgtype.Text `json:"quota_action"`
	ThrottleMbps        pgtype.Int4 `json:"throttle_mbps"`
	MonthlyPrice        pgtype.Int8 `json:"monthly_price"`
	InstallationFee     int64       `json:"installation_fee"`
	SellPrice           pgtype.Int8 `json:"sell_price"`
	ResellerPrice       pgtype.Int8 `json:"reseller_price"`
	DurationValue       pgtype.Int4 `json:"duration_value"`
	DurationUnit        pgtype.Text `json:"duration_unit"`
	SharedUsers         int32       `json:"shared_users"`
	MikrotikProfileName pgtype.Text `json:"mikrotik_profile_name"`
	AddressPool         pgtype.Text `json:"address_pool"`
	ParentQueue         pgtype.Text `json:"parent_queue"`
	HotspotProfileName  pgtype.Text `json:"hotspot_profile_name"`
}

// Query SQL untuk operasi CRUD tabel packages.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel packages dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Membuat paket baru dan mengembalikan semua kolom.
func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error) {
	row := q.db.QueryRow(ctx, createPackage,
		arg.TenantID,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.DownloadMbps,
		arg.UploadMbps,
		arg.BandwidthType,
		arg.BurstDownloadMbps,
		arg.BurstUploadMbps,
		arg.BurstThresholdMbps,
		arg.BurstTimeSeconds,
		arg.QuotaType,
		arg.QuotaMb,
		arg.QuotaAction,
		arg.ThrottleMbps,
		arg.MonthlyPrice,
		arg.InstallationFee,
		arg.SellPrice,
		arg.ResellerPrice,
		arg.DurationValue,
		arg.DurationUnit,
		arg.SharedUsers,
		arg.MikrotikProfileName,
		arg.AddressPool,
		arg.ParentQueue,
		arg.HotspotProfileName,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.DownloadMbps,
		&i.UploadMbps,
		&i.BandwidthType,
		&i.BurstDownloadMbps,
		&i.BurstUploadMbps,
		&i.BurstThresholdMbps,
		&i.BurstTimeSeconds,
		&i.QuotaType,
		&i.QuotaMb,
		&i.QuotaAction,
		&i.ThrottleMbps,
		&i.MonthlyPrice,
		&i.InstallationFee,
		&i.SellPrice,
		&i.ResellerPrice,
		&i.DurationValue,
		&i.DurationUnit,
		&i.SharedUsers,
		&i.MikrotikProfileName,
		&i.AddressPool,
		&i.ParentQueue,
		&i.HotspotProfileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePackage = `-- name: DeletePackage :exec
DELETE FROM packages WHERE id = $1
`

// Menghapus paket secara permanen (hard delete).
func (q *Queries) DeletePackage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePackage, id)
	return err
}

const getPackageByID = `-- name: GetPackageByID :one
SELECT p.id, p.tenant_id, p.type, p.name, p.description, p.is_active, p.download_mbps, p.upload_mbps, p.bandwidth_type, p.burst_download_mbps, p.burst_upload_mbps, p.burst_threshold_mbps, p.burst_time_seconds, p.quota_type, p.quota_mb, p.quota_action, p.throttle_mbps, p.monthly_price, p.installation_fee, p.sell_price, p.reseller_price, p.duration_value, p.duration_unit, p.shared_users, p.mikrotik_profile_name, p.address_pool, p.parent_queue, p.hotspot_profile_name, p.created_at, p.updated_at,
    (SELECT COUNT(*) FROM customers c
     WHERE c.package_id = p.id AND c.deleted_at IS NULL) AS customer_count
FROM packages p
WHERE p.id = $1
`

type GetPackageByIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	Type                string             `json:"type"`
	Name                string             `json:"name"`
	Description         pgtype.Text        `json:"description"`
	IsActive            bool               `json:"is_active"`
	DownloadMbps        int32              `json:"download_mbps"`
	UploadMbps          int32              `json:"upload_mbps"`
	BandwidthType       pgtype.Text        `json:"bandwidth_type"`
	BurstDownloadMbps   pgtype.Int4        `json:"burst_download_mbps"`
	BurstUploadMbps     pgtype.Int4        `json:"burst_upload_mbps"`
	BurstThresholdMbps  pgtype.Int4        `json:"burst_threshold_mbps"`
	BurstTimeSeconds    pgtype.Int4        `json:"burst_time_seconds"`
	QuotaType           string             `json:"quota_type"`
	QuotaMb             pgtype.Int4        `json:"quota_mb"`
	QuotaAction         pgtype.Text        `json:"quota_action"`
	ThrottleMbps        pgtype.Int4        `json:"throttle_mbps"`
	MonthlyPrice        pgtype.Int8        `json:"monthly_price"`
	InstallationFee     int64              `json:"installation_fee"`
	SellPrice           pgtype.Int8        `json:"sell_price"`
	ResellerPrice       pgtype.Int8        `json:"reseller_price"`
	DurationValue       pgtype.Int4        `json:"duration_value"`
	DurationUnit        pgtype.Text        `json:"duration_unit"`
	SharedUsers         int32              `json:"shared_users"`
	MikrotikProfileName pgtype.Text        `json:"mikrotik_profile_name"`
	AddressPool         pgtype.Text        `json:"address_pool"`
	ParentQueue         pgtype.Text        `json:"parent_queue"`
	HotspotProfileName  pgtype.Text        `json:"hotspot_profile_name"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CustomerCount       int64              `json:"customer_count"`
}

// Mengambil paket berdasarkan ID beserta jumlah pelanggan aktif.
func (q *Queries) GetPackageByID(ctx context.Context, id pgtype.UUID) (GetPackageByIDRow, error) {
	row := q.db.QueryRow(ctx, getPackageByID, id)
	var i GetPackageByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.DownloadMbps,
		&i.UploadMbps,
		&i.BandwidthType,
		&i.BurstDownloadMbps,
		&i.BurstUploadMbps,
		&i.BurstThresholdMbps,
		&i.BurstTimeSeconds,
		&i.QuotaType,
		&i.QuotaMb,
		&i.QuotaAction,
		&i.ThrottleMbps,
		&i.MonthlyPrice,
		&i.InstallationFee,
		&i.SellPrice,
		&i.ResellerPrice,
		&i.DurationValue,
		&i.DurationUnit,
		&i.SharedUsers,
		&i.MikrotikProfileName,
		&i.AddressPool,
		&i.ParentQueue,
		&i.HotspotProfileName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerCount,
	)
	return i, err
}

const listPackageNamesByPrefix = `-- name: ListPackageNamesByPrefix :many
SELECT name FROM packages
WHERE tenant_id = $1 AND name LIKE $2
ORDER BY name
`

type ListPackageNamesByPrefixParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
}

// Mengambil daftar nama paket berdasarkan prefix (untuk generate nama duplikat).
func (q *Queries) ListPackageNamesByPrefix(ctx context.Context, arg ListPackageNamesByPrefixParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPackageNamesByPrefix, arg.TenantID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const packageCustomerCount = `-- name: PackageCustomerCount :one
SELECT COUNT(*) FROM customers
WHERE package_id = $1
`

// Menghitung jumlah pelanggan yang masih mereferensikan paket.
func (q *Queries) PackageCustomerCount(ctx context.Context, packageID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, packageCustomerCount, packageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const packageNameExists = `-- name: PackageNameExists :one
SELECT EXISTS(
    SELECT 1 FROM packages
    WHERE tenant_id = $1 AND name = $2 AND id != $3
) AS exists
`

type PackageNameExistsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	ID       pgtype.UUID `json:"id"`
}

// Mengecek apakah nama paket sudah ada di tenant (exclude ID tertentu).
func (q *Queries) PackageNameExists(ctx context.Context, arg PackageNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, packageNameExists, arg.TenantID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePackage = `-- name: UpdatePackage :one
UPDATE packages SET
    name = $2,
    description = $3,
    download_mbps = $4,
    upload_mbps = $5,
    bandwidth_type = $6,
    burst_download_mbps = $7,
    burst_upload_mbps = $8,
    burst_threshold_mbps = $9,
    burst_time_seconds = $10,
    quota_type = $11,
    quota_mb = $12,
    quota_action = $13,
    throttle_mbps = $14,
    monthly_price = $15,
    installation_fee = $16,
    sell_price = $17,
    reseller_price = $18,
    duration_value = $19,
    duration_unit = $20,
    shared_users = $21,
    mikrotik_profile_name = $22,
    address_pool = $23,
    parent_queue = $24,
    hotspot_profile_name = $25,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, type, name, description, is_active, download_mbps, upload_mbps, bandwidth_type, burst_download_mbps, burst_upload_mbps, burst_threshold_mbps, burst_time_seconds, quota_type, quota_mb, quota_action, throttle_mbps, monthly_price, installation_fee, sell_price, reseller_price, duration_value, duration_unit, shared_users, mikrotik_profile_name, address_pool, parent_queue, hotspot_profile_name, created_at, updated_at
`

type UpdatePackageParams struct {
	ID                  pgtype.UUID `json:"id"`
	Name                string      `json:"name"`
	Description         pgtype.Text `json:"description"`
	DownloadMbps        int32       `json:"download_mbps"`
	UploadMbps          int32       `json:"upload_mbps"`
	BandwidthType       pgtype.Text `json:"bandwidth_type"`
	BurstDownloadMbps   pgtype.Int4 `json:"burst_download_mbps"`
	BurstUploadMbps     pgtype.Int4 `json:"burst_upload_mbps"`
	BurstThresholdMbps  pgtype.Int4 `json:"burst_threshold_mbps"`
	BurstTimeSeconds    pgtype.Int4 `json:"burst_time_seconds"`
	QuotaType           string      `json:"quota_type"`
	QuotaMb             pgtype.Int4 `json:"quota_mb"`
	QuotaAction         pgtype.Text `json:"quota_action"`
	ThrottleMbps        pgtype.Int4 `json:"throttle_mbps"`
	MonthlyPrice        pgtype.Int8 `json:"monthly_price"`
	InstallationFee     int64       `json:"installation_fee"`
	SellPrice           pgtype.Int8 `json:"sell_price"`
	ResellerPrice       pgtype.Int8 `json:"reseller_price"`
	DurationValue       pgtype.Int4 `json:"duration_value"`
	DurationUnit        pgtype.Text `json:"duration_unit"`
	SharedUsers         int32       `json:"shared_users"`
	MikrotikProfileName pgtype.Text `json:"mikrotik_profile_name"`
	AddressPool         pgtype.Text `json:"address_pool"`
	ParentQueue         pgtype.Text `json:"parent_queue"`
	HotspotProfileName  pgtype.Text `json:"hotspot_profile_name"`
}

// Memperbarui semua kolom mutable pada paket (kecuali id, tenant_id, type).
func (q *Queries) UpdatePackage(ctx context.Context, arg UpdatePackageParams) (Package, error) {
	row := q.db.QueryRow(ctx, updatePackage,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DownloadMbps,
		arg.UploadMbps,
		arg.BandwidthType,
		arg.BurstDownloadMbps,
		arg.BurstUploadMbps,
		arg.BurstThresholdMbps,
		arg.BurstTimeSeconds,
		arg.QuotaType,
		arg.QuotaMb,
		arg.QuotaAction,
		arg.ThrottleMbps,
		arg.MonthlyPrice,
		arg.InstallationFee,
		arg.SellPrice,
		arg.ResellerPrice,
		arg.DurationValue,
		arg.DurationUnit,
		arg.SharedUsers,
		arg.MikrotikProfileName,
		arg.AddressPool,
		arg.ParentQueue,
		arg.HotspotProfileName,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.DownloadMbps,
		&i.UploadMbps,
		&i.BandwidthType,
		&i.BurstDownloadMbps,
		&i.BurstUploadMbps,
		&i.BurstThresholdMbps,
		&i.BurstTimeSeconds,
		&i.QuotaType,
		&i.QuotaMb,
		&i.QuotaAction,
		&i.ThrottleMbps,
		&i.MonthlyPrice,
		&i.InstallationFee,
		&i.SellPrice,
		&i.ResellerPrice,
		&i.DurationValue,
		&i.DurationUnit,
		&i.SharedUsers,
		&i.MikrotikProfileName,
		&i.AddressPool,
		&i.ParentQueue,
		&i.HotspotProfileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePackageIsActive = `-- name: UpdatePackageIsActive :one
UPDATE packages SET is_active = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, type, name, description, is_active, download_mbps, upload_mbps, bandwidth_type, burst_download_mbps, burst_upload_mbps, burst_threshold_mbps, burst_time_seconds, quota_type, quota_mb, quota_action, throttle_mbps, monthly_price, installation_fee, sell_price, reseller_price, duration_value, duration_unit, shared_users, mikrotik_profile_name, address_pool, parent_queue, hotspot_profile_name, created_at, updated_at
`

type UpdatePackageIsActiveParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

// Memperbarui status aktif paket (aktivasi/deaktivasi).
func (q *Queries) UpdatePackageIsActive(ctx context.Context, arg UpdatePackageIsActiveParams) (Package, error) {
	row := q.db.QueryRow(ctx, updatePackageIsActive, arg.ID, arg.IsActive)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.DownloadMbps,
		&i.UploadMbps,
		&i.BandwidthType,
		&i.BurstDownloadMbps,
		&i.BurstUploadMbps,
		&i.BurstThresholdMbps,
		&i.BurstTimeSeconds,
		&i.QuotaType,
		&i.QuotaMb,
		&i.QuotaAction,
		&i.ThrottleMbps,
		&i.MonthlyPrice,
		&i.InstallationFee,
		&i.SellPrice,
		&i.ResellerPrice,
		&i.DurationValue,
		&i.DurationUnit,
		&i.SharedUsers,
		&i.MikrotikProfileName,
		&i.AddressPool,
		&i.ParentQueue,
		&i.HotspotProfileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
