// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_gateway_configs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGatewayConfig = `-- name: CreateGatewayConfig :one

INSERT INTO payment_gateway_configs (
    tenant_id, gateway_provider, api_key_encrypted,
    webhook_secret_encrypted, enabled_methods, payment_link_expiry_days
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
RETURNING id, tenant_id, gateway_provider, is_active, api_key_encrypted, webhook_secret_encrypted, enabled_methods, payment_link_expiry_days, created_at, updated_at
`

type CreateGatewayConfigParams struct {
	TenantID               pgtype.UUID `json:"tenant_id"`
	GatewayProvider        string      `json:"gateway_provider"`
	ApiKeyEncrypted        string      `json:"api_key_encrypted"`
	WebhookSecretEncrypted string      `json:"webhook_secret_encrypted"`
	EnabledMethods         []byte      `json:"enabled_methods"`
	PaymentLinkExpiryDays  int32       `json:"payment_link_expiry_days"`
}

// Query SQL untuk operasi CRUD tabel payment_gateway_configs.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel payment_gateway_configs dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Setiap tenant bisa memiliki satu konfigurasi per provider (UNIQUE pada tenant_id, gateway_provider).
// Membuat konfigurasi gateway baru dan mengembalikan semua kolom.
func (q *Queries) CreateGatewayConfig(ctx context.Context, arg CreateGatewayConfigParams) (PaymentGatewayConfig, error) {
	row := q.db.QueryRow(ctx, createGatewayConfig,
		arg.TenantID,
		arg.GatewayProvider,
		arg.ApiKeyEncrypted,
		arg.WebhookSecretEncrypted,
		arg.EnabledMethods,
		arg.PaymentLinkExpiryDays,
	)
	var i PaymentGatewayConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GatewayProvider,
		&i.IsActive,
		&i.ApiKeyEncrypted,
		&i.WebhookSecretEncrypted,
		&i.EnabledMethods,
		&i.PaymentLinkExpiryDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateGatewayConfig = `-- name: DeactivateGatewayConfig :exec
UPDATE payment_gateway_configs SET
    is_active = false,
    updated_at = NOW()
WHERE id = $1
`

// Menonaktifkan konfigurasi gateway (soft delete) dengan set is_active=false.
func (q *Queries) DeactivateGatewayConfig(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateGatewayConfig, id)
	return err
}

const existsGatewayConfigByProvider = `-- name: ExistsGatewayConfigByProvider :one
SELECT EXISTS(
    SELECT 1 FROM payment_gateway_configs
    WHERE tenant_id = $1 AND gateway_provider = $2 AND is_active = true
) AS exists
`

type ExistsGatewayConfigByProviderParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	GatewayProvider string      `json:"gateway_provider"`
}

// Mengecek apakah konfigurasi aktif sudah ada untuk provider di tenant.
func (q *Queries) ExistsGatewayConfigByProvider(ctx context.Context, arg ExistsGatewayConfigByProviderParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsGatewayConfigByProvider, arg.TenantID, arg.GatewayProvider)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getActiveGatewayConfigByProvider = `-- name: GetActiveGatewayConfigByProvider :one
SELECT id, tenant_id, gateway_provider, is_active, api_key_encrypted, webhook_secret_encrypted, enabled_methods, payment_link_expiry_days, created_at, updated_at
FROM payment_gateway_configs
WHERE tenant_id = $1 AND gateway_provider = $2 AND is_active = true
`

type GetActiveGatewayConfigByProviderParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	GatewayProvider string      `json:"gateway_provider"`
}

// Mengambil konfigurasi gateway aktif berdasarkan provider untuk tenant.
func (q *Queries) GetActiveGatewayConfigByProvider(ctx context.Context, arg GetActiveGatewayConfigByProviderParams) (PaymentGatewayConfig, error) {
	row := q.db.QueryRow(ctx, getActiveGatewayConfigByProvider, arg.TenantID, arg.GatewayProvider)
	var i PaymentGatewayConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GatewayProvider,
		&i.IsActive,
		&i.ApiKeyEncrypted,
		&i.WebhookSecretEncrypted,
		&i.EnabledMethods,
		&i.PaymentLinkExpiryDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveGatewayConfigsByTenant = `-- name: GetActiveGatewayConfigsByTenant :many
SELECT id, tenant_id, gateway_provider, is_active, api_key_encrypted, webhook_secret_encrypted, enabled_methods, payment_link_expiry_days, created_at, updated_at
FROM payment_gateway_configs
WHERE tenant_id = $1 AND is_active = true
ORDER BY created_at ASC
`

// Mengambil konfigurasi gateway aktif untuk tenant tertentu.
func (q *Queries) GetActiveGatewayConfigsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]PaymentGatewayConfig, error) {
	rows, err := q.db.Query(ctx, getActiveGatewayConfigsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentGatewayConfig{}
	for rows.Next() {
		var i PaymentGatewayConfig
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.GatewayProvider,
			&i.IsActive,
			&i.ApiKeyEncrypted,
			&i.WebhookSecretEncrypted,
			&i.EnabledMethods,
			&i.PaymentLinkExpiryDays,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGatewayConfigByID = `-- name: GetGatewayConfigByID :one
SELECT id, tenant_id, gateway_provider, is_active, api_key_encrypted, webhook_secret_encrypted, enabled_methods, payment_link_expiry_days, created_at, updated_at
FROM payment_gateway_configs
WHERE id = $1
`

// Mengambil konfigurasi gateway berdasarkan ID (tenant-scoped via RLS).
func (q *Queries) GetGatewayConfigByID(ctx context.Context, id pgtype.UUID) (PaymentGatewayConfig, error) {
	row := q.db.QueryRow(ctx, getGatewayConfigByID, id)
	var i PaymentGatewayConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GatewayProvider,
		&i.IsActive,
		&i.ApiKeyEncrypted,
		&i.WebhookSecretEncrypted,
		&i.EnabledMethods,
		&i.PaymentLinkExpiryDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGatewayConfigsByTenant = `-- name: ListGatewayConfigsByTenant :many
SELECT id, tenant_id, gateway_provider, is_active, api_key_encrypted, webhook_secret_encrypted, enabled_methods, payment_link_expiry_days, created_at, updated_at
FROM payment_gateway_configs
WHERE tenant_id = $1
ORDER BY created_at ASC
`

// Mengambil semua konfigurasi gateway untuk tenant tertentu.
func (q *Queries) ListGatewayConfigsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]PaymentGatewayConfig, error) {
	rows, err := q.db.Query(ctx, listGatewayConfigsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentGatewayConfig{}
	for rows.Next() {
		var i PaymentGatewayConfig
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.GatewayProvider,
			&i.IsActive,
			&i.ApiKeyEncrypted,
			&i.WebhookSecretEncrypted,
			&i.EnabledMethods,
			&i.PaymentLinkExpiryDays,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGatewayConfig = `-- name: UpdateGatewayConfig :one
UPDATE payment_gateway_configs SET
    api_key_encrypted = $2,
    webhook_secret_encrypted = $3,
    enabled_methods = $4,
    payment_link_expiry_days = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, gateway_provider, is_active, api_key_encrypted, webhook_secret_encrypted, enabled_methods, payment_link_expiry_days, created_at, updated_at
`

type UpdateGatewayConfigParams struct {
	ID                     pgtype.UUID `json:"id"`
	ApiKeyEncrypted        string      `json:"api_key_encrypted"`
	WebhookSecretEncrypted string      `json:"webhook_secret_encrypted"`
	EnabledMethods         []byte      `json:"enabled_methods"`
	PaymentLinkExpiryDays  int32       `json:"payment_link_expiry_days"`
}

// Memperbarui konfigurasi gateway dan mengembalikan semua kolom.
// Kolom yang diperbarui: api_key_encrypted, webhook_secret_encrypted,
// enabled_methods, payment_link_expiry_days, updated_at.
func (q *Queries) UpdateGatewayConfig(ctx context.Context, arg UpdateGatewayConfigParams) (PaymentGatewayConfig, error) {
	row := q.db.QueryRow(ctx, updateGatewayConfig,
		arg.ID,
		arg.ApiKeyEncrypted,
		arg.WebhookSecretEncrypted,
		arg.EnabledMethods,
		arg.PaymentLinkExpiryDays,
	)
	var i PaymentGatewayConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GatewayProvider,
		&i.IsActive,
		&i.ApiKeyEncrypted,
		&i.WebhookSecretEncrypted,
		&i.EnabledMethods,
		&i.PaymentLinkExpiryDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
