// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: payment_links.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentLink = `-- name: CreatePaymentLink :one

INSERT INTO payment_links (
    tenant_id, customer_id, gateway_provider, gateway_config_id,
    external_id, payment_url, amount, status, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9
)
RETURNING id, tenant_id, customer_id, gateway_provider, gateway_config_id, external_id, payment_url, amount, status, expires_at, paid_at, paid_method, created_at, updated_at
`

type CreatePaymentLinkParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	CustomerID      pgtype.UUID        `json:"customer_id"`
	GatewayProvider string             `json:"gateway_provider"`
	GatewayConfigID pgtype.UUID        `json:"gateway_config_id"`
	ExternalID      string             `json:"external_id"`
	PaymentUrl      string             `json:"payment_url"`
	Amount          int64              `json:"amount"`
	Status          string             `json:"status"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

// Kueri SQL untuk operasi CRUD tabel payment_links dan payment_link_invoices.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel payment_links dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Membuat link pembayaran baru dan mengembalikan semua kolom.
func (q *Queries) CreatePaymentLink(ctx context.Context, arg CreatePaymentLinkParams) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, createPaymentLink,
		arg.TenantID,
		arg.CustomerID,
		arg.GatewayProvider,
		arg.GatewayConfigID,
		arg.ExternalID,
		arg.PaymentUrl,
		arg.Amount,
		arg.Status,
		arg.ExpiresAt,
	)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.GatewayProvider,
		&i.GatewayConfigID,
		&i.ExternalID,
		&i.PaymentUrl,
		&i.Amount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.PaidMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentLinkInvoice = `-- name: CreatePaymentLinkInvoice :exec
INSERT INTO payment_link_invoices (
    payment_link_id, invoice_id
) VALUES (
    $1, $2
)
`

type CreatePaymentLinkInvoiceParams struct {
	PaymentLinkID pgtype.UUID `json:"payment_link_id"`
	InvoiceID     pgtype.UUID `json:"invoice_id"`
}

// Membuat relasi antara link pembayaran dan invoice di junction table.
func (q *Queries) CreatePaymentLinkInvoice(ctx context.Context, arg CreatePaymentLinkInvoiceParams) error {
	_, err := q.db.Exec(ctx, createPaymentLinkInvoice, arg.PaymentLinkID, arg.InvoiceID)
	return err
}

const expirePaymentLinkByID = `-- name: ExpirePaymentLinkByID :exec
UPDATE payment_links SET
    status = 'expired',
    updated_at = NOW()
WHERE id = $1 AND status = 'active'
`

// Mengubah status link pembayaran menjadi 'expired' jika masih aktif.
func (q *Queries) ExpirePaymentLinkByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, expirePaymentLinkByID, id)
	return err
}

const findExpiredPaymentLinks = `-- name: FindExpiredPaymentLinks :many
SELECT id, tenant_id, customer_id, gateway_provider, gateway_config_id, external_id, payment_url, amount, status, expires_at, paid_at, paid_method, created_at, updated_at
FROM payment_links
WHERE status = 'active' AND expires_at < NOW()
LIMIT $1
`

// Mengambil link pembayarans aktif yang sudah melewati waktu expires_at (untuk background job expiry).
func (q *Queries) FindExpiredPaymentLinks(ctx context.Context, limit int32) ([]PaymentLink, error) {
	rows, err := q.db.Query(ctx, findExpiredPaymentLinks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentLink{}
	for rows.Next() {
		var i PaymentLink
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.GatewayProvider,
			&i.GatewayConfigID,
			&i.ExternalID,
			&i.PaymentUrl,
			&i.Amount,
			&i.Status,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.PaidMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivePaymentLinkByCustomer = `-- name: GetActivePaymentLinkByCustomer :one
SELECT id, tenant_id, customer_id, gateway_provider, gateway_config_id, external_id, payment_url, amount, status, expires_at, paid_at, paid_method, created_at, updated_at
FROM payment_links
WHERE customer_id = $1 AND status = 'active'
`

// Mengambil link pembayaran aktif (status='active') untuk customer tertentu.
func (q *Queries) GetActivePaymentLinkByCustomer(ctx context.Context, customerID pgtype.UUID) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, getActivePaymentLinkByCustomer, customerID)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.GatewayProvider,
		&i.GatewayConfigID,
		&i.ExternalID,
		&i.PaymentUrl,
		&i.Amount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.PaidMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceIDsByPaymentLinkID = `-- name: GetInvoiceIDsByPaymentLinkID :many
SELECT invoice_id
FROM payment_link_invoices
WHERE payment_link_id = $1
`

// Mengambil daftar invoice_id yang terkait dengan link pembayaran tertentu.
func (q *Queries) GetInvoiceIDsByPaymentLinkID(ctx context.Context, paymentLinkID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getInvoiceIDsByPaymentLinkID, paymentLinkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var invoice_id pgtype.UUID
		if err := rows.Scan(&invoice_id); err != nil {
			return nil, err
		}
		items = append(items, invoice_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentLinkByExternalID = `-- name: GetPaymentLinkByExternalID :one
SELECT id, tenant_id, customer_id, gateway_provider, gateway_config_id, external_id, payment_url, amount, status, expires_at, paid_at, paid_method, created_at, updated_at
FROM payment_links
WHERE external_id = $1
`

// Mengambil link pembayaran berdasarkan external_id dari gateway.
func (q *Queries) GetPaymentLinkByExternalID(ctx context.Context, externalID string) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, getPaymentLinkByExternalID, externalID)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.GatewayProvider,
		&i.GatewayConfigID,
		&i.ExternalID,
		&i.PaymentUrl,
		&i.Amount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.PaidMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentLinkByID = `-- name: GetPaymentLinkByID :one
SELECT id, tenant_id, customer_id, gateway_provider, gateway_config_id, external_id, payment_url, amount, status, expires_at, paid_at, paid_method, created_at, updated_at
FROM payment_links
WHERE id = $1
`

// Mengambil link pembayaran berdasarkan ID (tenant-scoped via RLS).
func (q *Queries) GetPaymentLinkByID(ctx context.Context, id pgtype.UUID) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, getPaymentLinkByID, id)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.GatewayProvider,
		&i.GatewayConfigID,
		&i.ExternalID,
		&i.PaymentUrl,
		&i.Amount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.PaidMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentLinksByInvoice = `-- name: ListPaymentLinksByInvoice :many
SELECT pl.id, pl.tenant_id, pl.customer_id, pl.gateway_provider, pl.gateway_config_id, pl.external_id, pl.payment_url, pl.amount, pl.status, pl.expires_at, pl.paid_at, pl.paid_method, pl.created_at, pl.updated_at
FROM payment_links pl
JOIN payment_link_invoices pli ON pl.id = pli.payment_link_id
WHERE pli.invoice_id = $1
ORDER BY pl.created_at DESC
`

// Mengambil semua link pembayarans untuk invoice tertentu melalui junction table.
func (q *Queries) ListPaymentLinksByInvoice(ctx context.Context, invoiceID pgtype.UUID) ([]PaymentLink, error) {
	rows, err := q.db.Query(ctx, listPaymentLinksByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentLink{}
	for rows.Next() {
		var i PaymentLink
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.GatewayProvider,
			&i.GatewayConfigID,
			&i.ExternalID,
			&i.PaymentUrl,
			&i.Amount,
			&i.Status,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.PaidMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentLinkPaid = `-- name: UpdatePaymentLinkPaid :exec
UPDATE payment_links SET
    status = 'paid',
    paid_method = $2,
    paid_at = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdatePaymentLinkPaidParams struct {
	ID         pgtype.UUID        `json:"id"`
	PaidMethod pgtype.Text        `json:"paid_method"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
}

// Memperbarui link pembayaran menjadi status 'paid' beserta metode pembayaran dan waktu bayar.
func (q *Queries) UpdatePaymentLinkPaid(ctx context.Context, arg UpdatePaymentLinkPaidParams) error {
	_, err := q.db.Exec(ctx, updatePaymentLinkPaid, arg.ID, arg.PaidMethod, arg.PaidAt)
	return err
}

const updatePaymentLinkStatus = `-- name: UpdatePaymentLinkStatus :exec
UPDATE payment_links SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdatePaymentLinkStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Memperbarui status link pembayaran dan updated_at.
func (q *Queries) UpdatePaymentLinkStatus(ctx context.Context, arg UpdatePaymentLinkStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentLinkStatus, arg.ID, arg.Status)
	return err
}
