// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_syncs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingSyncsByTenantAndStatuses = `-- name: CountPendingSyncsByTenantAndStatuses :one
SELECT COUNT(*)
FROM pending_syncs
WHERE tenant_id = $1
  AND status = ANY($2::varchar[])
`

type CountPendingSyncsByTenantAndStatusesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Statuses []string    `json:"statuses"`
}

// Menghitung jumlah pending syncs berdasarkan tenant dan array status.
func (q *Queries) CountPendingSyncsByTenantAndStatuses(ctx context.Context, arg CountPendingSyncsByTenantAndStatusesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSyncsByTenantAndStatuses, arg.TenantID, arg.Statuses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPendingSync = `-- name: CreatePendingSync :one

INSERT INTO pending_syncs (
    tenant_id, customer_id, operation_type, status,
    retry_count, max_retries, next_retry_at, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, tenant_id, customer_id, operation_type, status, retry_count, max_retries, last_retry_at, next_retry_at, error_message, metadata, created_at, updated_at
`

type CreatePendingSyncParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	OperationType string             `json:"operation_type"`
	Status        string             `json:"status"`
	RetryCount    int32              `json:"retry_count"`
	MaxRetries    int32              `json:"max_retries"`
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
	Metadata      []byte             `json:"metadata"`
}

// Query SQL untuk operasi CRUD tabel pending_syncs.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel pending_syncs dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Digunakan oleh modul isolir untuk melacak operasi sinkronisasi router yang tertunda.
// Membuat pending sync baru dan mengembalikan semua kolom.
func (q *Queries) CreatePendingSync(ctx context.Context, arg CreatePendingSyncParams) (PendingSync, error) {
	row := q.db.QueryRow(ctx, createPendingSync,
		arg.TenantID,
		arg.CustomerID,
		arg.OperationType,
		arg.Status,
		arg.RetryCount,
		arg.MaxRetries,
		arg.NextRetryAt,
		arg.Metadata,
	)
	var i PendingSync
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OperationType,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastRetryAt,
		&i.NextRetryAt,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPendingSyncsByCustomer = `-- name: FindPendingSyncsByCustomer :many
SELECT id, tenant_id, customer_id, operation_type, status, retry_count, max_retries, last_retry_at, next_retry_at, error_message, metadata, created_at, updated_at
FROM pending_syncs
WHERE customer_id = $1
ORDER BY created_at DESC
`

// Mengambil semua pending syncs untuk customer tertentu.
func (q *Queries) FindPendingSyncsByCustomer(ctx context.Context, customerID pgtype.UUID) ([]PendingSync, error) {
	rows, err := q.db.Query(ctx, findPendingSyncsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingSync{}
	for rows.Next() {
		var i PendingSync
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.OperationType,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.LastRetryAt,
			&i.NextRetryAt,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPendingSyncsByTenantAndStatus = `-- name: FindPendingSyncsByTenantAndStatus :many
SELECT ps.id, ps.tenant_id, ps.customer_id, ps.operation_type, ps.status, ps.retry_count, ps.max_retries, ps.last_retry_at, ps.next_retry_at, ps.error_message, ps.metadata, ps.created_at, ps.updated_at,
    c.name AS customer_name,
    c.customer_id_seq AS customer_id_seq
FROM pending_syncs ps
LEFT JOIN customers c ON c.id = ps.customer_id
WHERE ps.tenant_id = $1
  AND ($2::varchar IS NULL OR ps.status = $2::varchar)
ORDER BY ps.created_at DESC
LIMIT $4
OFFSET $3
`

type FindPendingSyncsByTenantAndStatusParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
	Offset   int32       `json:"offset"`
	PageSize int32       `json:"page_size"`
}

type FindPendingSyncsByTenantAndStatusRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	OperationType string             `json:"operation_type"`
	Status        string             `json:"status"`
	RetryCount    int32              `json:"retry_count"`
	MaxRetries    int32              `json:"max_retries"`
	LastRetryAt   pgtype.Timestamptz `json:"last_retry_at"`
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CustomerName  pgtype.Text        `json:"customer_name"`
	CustomerIDSeq pgtype.Text        `json:"customer_id_seq"`
}

// Mengambil pending syncs berdasarkan tenant dan status (opsional) dengan paginasi.
// LEFT JOIN customers untuk mendapatkan customer_name dan customer_id_seq.
func (q *Queries) FindPendingSyncsByTenantAndStatus(ctx context.Context, arg FindPendingSyncsByTenantAndStatusParams) ([]FindPendingSyncsByTenantAndStatusRow, error) {
	rows, err := q.db.Query(ctx, findPendingSyncsByTenantAndStatus,
		arg.TenantID,
		arg.Status,
		arg.Offset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPendingSyncsByTenantAndStatusRow{}
	for rows.Next() {
		var i FindPendingSyncsByTenantAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.OperationType,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.LastRetryAt,
			&i.NextRetryAt,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.CustomerIDSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPendingSyncsForRetry = `-- name: FindPendingSyncsForRetry :many
SELECT id, tenant_id, customer_id, operation_type, status, retry_count, max_retries, last_retry_at, next_retry_at, error_message, metadata, created_at, updated_at
FROM pending_syncs
WHERE status = 'pending'
  AND (next_retry_at IS NULL OR next_retry_at <= NOW())
ORDER BY created_at ASC
LIMIT $1
`

// Mengambil pending syncs yang siap di-retry (status pending, next_retry_at <= now atau NULL).
// Diurutkan berdasarkan created_at ASC, dibatasi batch_size.
func (q *Queries) FindPendingSyncsForRetry(ctx context.Context, batchSize int32) ([]PendingSync, error) {
	rows, err := q.db.Query(ctx, findPendingSyncsForRetry, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingSync{}
	for rows.Next() {
		var i PendingSync
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.OperationType,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.LastRetryAt,
			&i.NextRetryAt,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingSyncByID = `-- name: GetPendingSyncByID :one
SELECT id, tenant_id, customer_id, operation_type, status, retry_count, max_retries, last_retry_at, next_retry_at, error_message, metadata, created_at, updated_at
FROM pending_syncs
WHERE id = $1
`

// Mengambil pending sync berdasarkan ID.
func (q *Queries) GetPendingSyncByID(ctx context.Context, id pgtype.UUID) (PendingSync, error) {
	row := q.db.QueryRow(ctx, getPendingSyncByID, id)
	var i PendingSync
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OperationType,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastRetryAt,
		&i.NextRetryAt,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPendingSyncCompleted = `-- name: MarkPendingSyncCompleted :exec
UPDATE pending_syncs SET
    status = 'completed',
    updated_at = NOW()
WHERE id = $1
`

// Menandai pending sync sebagai completed.
func (q *Queries) MarkPendingSyncCompleted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markPendingSyncCompleted, id)
	return err
}

const markPendingSyncFailed = `-- name: MarkPendingSyncFailed :exec
UPDATE pending_syncs SET
    status = 'failed',
    error_message = $2,
    updated_at = NOW()
WHERE id = $1
`

type MarkPendingSyncFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

// Menandai pending sync sebagai failed dengan error message.
func (q *Queries) MarkPendingSyncFailed(ctx context.Context, arg MarkPendingSyncFailedParams) error {
	_, err := q.db.Exec(ctx, markPendingSyncFailed, arg.ID, arg.ErrorMessage)
	return err
}

const resetRetryAll = `-- name: ResetRetryAll :execrows
UPDATE pending_syncs SET
    retry_count = 0,
    next_retry_at = NOW(),
    status = 'pending',
    updated_at = NOW()
WHERE tenant_id = $1
  AND status IN ('pending', 'failed')
`

// Mereset retry_count ke 0 dan status ke pending untuk semua pending/failed di tenant.
// Mengembalikan jumlah baris yang terpengaruh.
func (q *Queries) ResetRetryAll(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, resetRetryAll, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetRetryForCustomer = `-- name: ResetRetryForCustomer :exec
UPDATE pending_syncs SET
    retry_count = 0,
    next_retry_at = NOW(),
    status = 'pending',
    updated_at = NOW()
WHERE customer_id = $1
  AND status IN ('pending', 'failed')
`

// Mereset retry_count ke 0 dan status ke pending untuk customer tertentu.
// Hanya mereset yang berstatus pending atau failed.
func (q *Queries) ResetRetryForCustomer(ctx context.Context, customerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetRetryForCustomer, customerID)
	return err
}

const updatePendingSyncRetry = `-- name: UpdatePendingSyncRetry :exec
UPDATE pending_syncs SET
    retry_count = $2,
    next_retry_at = $3,
    last_retry_at = $4,
    error_message = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdatePendingSyncRetryParams struct {
	ID           pgtype.UUID        `json:"id"`
	RetryCount   int32              `json:"retry_count"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	LastRetryAt  pgtype.Timestamptz `json:"last_retry_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
}

// Memperbarui retry_count, next_retry_at, last_retry_at, error_message berdasarkan ID.
func (q *Queries) UpdatePendingSyncRetry(ctx context.Context, arg UpdatePendingSyncRetryParams) error {
	_, err := q.db.Exec(ctx, updatePendingSyncRetry,
		arg.ID,
		arg.RetryCount,
		arg.NextRetryAt,
		arg.LastRetryAt,
		arg.ErrorMessage,
	)
	return err
}

const updatePendingSyncStatus = `-- name: UpdatePendingSyncStatus :exec
UPDATE pending_syncs SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdatePendingSyncStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Memperbarui status pending sync berdasarkan ID.
func (q *Queries) UpdatePendingSyncStatus(ctx context.Context, arg UpdatePendingSyncStatusParams) error {
	_, err := q.db.Exec(ctx, updatePendingSyncStatus, arg.ID, arg.Status)
	return err
}
