// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipt_sequences.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const nextReceiptSequence = `-- name: NextReceiptSequence :one

INSERT INTO receipt_sequences (
    tenant_id, year, month, last_seq
) VALUES (
    $1, $2, $3, 1
)
ON CONFLICT (tenant_id, year, month) DO UPDATE SET
    last_seq = receipt_sequences.last_seq + 1,
    updated_at = NOW()
RETURNING last_seq
`

type NextReceiptSequenceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Year     int32       `json:"year"`
	Month    int32       `json:"month"`
}

// Query SQL untuk operasi pada tabel receipt_sequences.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel receipt_sequences dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Sequence digunakan untuk auto-increment nomor kwitansi per tenant per bulan.
// Mengambil dan increment sequence secara atomik menggunakan INSERT ON CONFLICT.
// Jika row belum ada untuk tenant/year/month, buat baru dengan last_seq = 1.
// Jika sudah ada, increment last_seq dan kembalikan nilai baru.
func (q *Queries) NextReceiptSequence(ctx context.Context, arg NextReceiptSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextReceiptSequence, arg.TenantID, arg.Year, arg.Month)
	var last_seq int32
	err := row.Scan(&last_seq)
	return last_seq, err
}
