// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report_aggregation_operational.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminActivity = `-- name: GetAdminActivity :many

SELECT
    al.actor_id AS user_id,
    al.actor_name AS user_name,
    COALESCE(u.role, 'unknown') AS role,
    COUNT(DISTINCT DATE(al.created_at))::int AS login_days,
    COUNT(*)::int AS action_count,
    MAX(al.created_at) AS last_active_at
FROM audit_logs al
LEFT JOIN users u ON u.id = al.actor_id
WHERE al.tenant_id = $1
  AND al.created_at >= $2::timestamptz
  AND al.created_at < $3::timestamptz
GROUP BY al.actor_id, al.actor_name, u.role
ORDER BY action_count DESC
`

type GetAdminActivityParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type GetAdminActivityRow struct {
	UserID       pgtype.UUID `json:"user_id"`
	UserName     string      `json:"user_name"`
	Role         string      `json:"role"`
	LoginDays    int32       `json:"login_days"`
	ActionCount  int32       `json:"action_count"`
	LastActiveAt interface{} `json:"last_active_at"`
}

// Query SQL untuk aggregasi laporan operasional (operational reports).
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Mencakup: aktivitas admin, top actions, dan dashboard data.
// Tabel dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Menghitung aktivitas per user dari audit_logs untuk periode tertentu.
// Mengembalikan user_id, user_name, role, login_days, action_count, dan last_active_at.
// login_days dihitung dari jumlah hari unik user melakukan aksi.
func (q *Queries) GetAdminActivity(ctx context.Context, arg GetAdminActivityParams) ([]GetAdminActivityRow, error) {
	rows, err := q.db.Query(ctx, getAdminActivity, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminActivityRow{}
	for rows.Next() {
		var i GetAdminActivityRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.Role,
			&i.LoginDays,
			&i.ActionCount,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardData = `-- name: GetDashboardData :one
SELECT
    -- Total pelanggan aktif
    COALESCE((
        SELECT COUNT(*)
        FROM customers c
        WHERE c.tenant_id = $1
          AND c.status = 'aktif'
          AND c.deleted_at IS NULL
    ), 0)::int AS total_active_customers,

    -- Trend pelanggan vs bulan lalu (persentase perubahan)
    CASE
        WHEN COALESCE((
            SELECT COUNT(*)
            FROM customers c2
            WHERE c2.tenant_id = $1
              AND c2.status = 'aktif'
              AND c2.deleted_at IS NULL
              AND c2.activation_date <= (DATE_TRUNC('month', CURRENT_DATE) - INTERVAL '1 day')::date
        ), 0) = 0 THEN 0
        ELSE ROUND(
            (
                (SELECT COUNT(*) FROM customers c3
                 WHERE c3.tenant_id = $1 AND c3.status = 'aktif' AND c3.deleted_at IS NULL)::numeric -
                (SELECT COUNT(*) FROM customers c4
                 WHERE c4.tenant_id = $1 AND c4.status = 'aktif' AND c4.deleted_at IS NULL
                   AND c4.activation_date <= (DATE_TRUNC('month', CURRENT_DATE) - INTERVAL '1 day')::date)::numeric
            ) /
            GREATEST((SELECT COUNT(*) FROM customers c5
                      WHERE c5.tenant_id = $1 AND c5.status = 'aktif' AND c5.deleted_at IS NULL
                        AND c5.activation_date <= (DATE_TRUNC('month', CURRENT_DATE) - INTERVAL '1 day')::date), 1)::numeric * 100,
            2
        )
    END::float8 AS customers_trend,

    -- Pendapatan bulan ini
    COALESCE((
        SELECT SUM(ip.amount)
        FROM invoice_payments ip
        WHERE ip.tenant_id = $1
          AND ip.voided = false
          AND ip.payment_date >= DATE_TRUNC('month', CURRENT_DATE)::date
          AND ip.payment_date < (DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month')::date
    ), 0)::bigint AS monthly_revenue,

    -- Total piutang (outstanding)
    COALESCE((
        SELECT SUM(i.total_amount - i.paid_amount)
        FROM invoices i
        WHERE i.tenant_id = $1
          AND i.status IN ('belum_bayar', 'terlambat', 'bayar_sebagian')
          AND (i.total_amount - i.paid_amount) > 0
    ), 0)::bigint AS total_receivables,

    -- Jumlah pelanggan dengan piutang
    COALESCE((
        SELECT COUNT(DISTINCT i.customer_id)
        FROM invoices i
        WHERE i.tenant_id = $1
          AND i.status IN ('belum_bayar', 'terlambat', 'bayar_sebagian')
          AND (i.total_amount - i.paid_amount) > 0
    ), 0)::int AS receivables_count,

    -- Collection rate bulan ini
    CASE
        WHEN COALESCE((
            SELECT COUNT(*)
            FROM invoices i2
            WHERE i2.tenant_id = $1
              AND i2.due_date >= DATE_TRUNC('month', CURRENT_DATE)::date
              AND i2.due_date < (DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month')::date
              AND i2.status != 'batal'
        ), 0) = 0 THEN 0
        ELSE ROUND(
            (SELECT COUNT(*) FROM invoices i3
             WHERE i3.tenant_id = $1
               AND i3.due_date >= DATE_TRUNC('month', CURRENT_DATE)::date
               AND i3.due_date < (DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month')::date
               AND i3.status = 'lunas')::numeric /
            GREATEST((SELECT COUNT(*) FROM invoices i4
                      WHERE i4.tenant_id = $1
                        AND i4.due_date >= DATE_TRUNC('month', CURRENT_DATE)::date
                        AND i4.due_date < (DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month')::date
                        AND i4.status != 'batal'), 1)::numeric * 100,
            2
        )
    END::float8 AS collection_rate,

    -- Churn rate bulan ini
    CASE
        WHEN COALESCE((
            SELECT COUNT(*)
            FROM customers c6
            WHERE c6.tenant_id = $1
              AND c6.activation_date < DATE_TRUNC('month', CURRENT_DATE)::date
              AND (c6.status != 'berhenti' OR c6.updated_at >= DATE_TRUNC('month', CURRENT_DATE))
              AND (c6.deleted_at IS NULL OR c6.deleted_at >= DATE_TRUNC('month', CURRENT_DATE))
        ), 0) = 0 THEN 0
        ELSE ROUND(
            (SELECT COUNT(*) FROM customers c7
             WHERE c7.tenant_id = $1
               AND c7.status = 'berhenti'
               AND c7.updated_at >= DATE_TRUNC('month', CURRENT_DATE)
               AND c7.updated_at < (DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month'))::numeric /
            GREATEST((SELECT COUNT(*) FROM customers c8
                      WHERE c8.tenant_id = $1
                        AND c8.activation_date < DATE_TRUNC('month', CURRENT_DATE)::date
                        AND (c8.status != 'berhenti' OR c8.updated_at >= DATE_TRUNC('month', CURRENT_DATE))
                        AND (c8.deleted_at IS NULL OR c8.deleted_at >= DATE_TRUNC('month', CURRENT_DATE))), 1)::numeric * 100,
            2
        )
    END::float8 AS churn_rate,

    -- ARPU bulan ini
    CASE
        WHEN COALESCE((
            SELECT COUNT(*)
            FROM customers c9
            WHERE c9.tenant_id = $1
              AND c9.status = 'aktif'
              AND c9.deleted_at IS NULL
        ), 0) = 0 THEN 0
        ELSE (
            COALESCE((
                SELECT SUM(ip2.amount)
                FROM invoice_payments ip2
                WHERE ip2.tenant_id = $1
                  AND ip2.voided = false
                  AND ip2.payment_date >= DATE_TRUNC('month', CURRENT_DATE)::date
                  AND ip2.payment_date < (DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month')::date
            ), 0) /
            GREATEST((
                SELECT COUNT(*)
                FROM customers c10
                WHERE c10.tenant_id = $1
                  AND c10.status = 'aktif'
                  AND c10.deleted_at IS NULL
            ), 1)
        )
    END::bigint AS arpu
`

type GetDashboardDataRow struct {
	TotalActiveCustomers int32   `json:"total_active_customers"`
	CustomersTrend       float64 `json:"customers_trend"`
	MonthlyRevenue       int64   `json:"monthly_revenue"`
	TotalReceivables     int64   `json:"total_receivables"`
	ReceivablesCount     int32   `json:"receivables_count"`
	CollectionRate       float64 `json:"collection_rate"`
	ChurnRate            float64 `json:"churn_rate"`
	Arpu                 int64   `json:"arpu"`
}

// Mengambil data ringkasan untuk dashboard widget.
// Aggregasi metrik kunci: pelanggan aktif, trend, pendapatan bulan ini,
// piutang, collection rate, churn rate, dan ARPU.
// Dioptimasi untuk fast loading (target < 500ms).
func (q *Queries) GetDashboardData(ctx context.Context, tenantID pgtype.UUID) (GetDashboardDataRow, error) {
	row := q.db.QueryRow(ctx, getDashboardData, tenantID)
	var i GetDashboardDataRow
	err := row.Scan(
		&i.TotalActiveCustomers,
		&i.CustomersTrend,
		&i.MonthlyRevenue,
		&i.TotalReceivables,
		&i.ReceivablesCount,
		&i.CollectionRate,
		&i.ChurnRate,
		&i.Arpu,
	)
	return i, err
}

const getTopActions = `-- name: GetTopActions :many
SELECT
    al.action AS action_type,
    COUNT(*)::int AS count,
    CASE
        WHEN SUM(COUNT(*)) OVER () = 0 THEN 0
        ELSE ROUND(COUNT(*)::numeric / SUM(COUNT(*)) OVER ()::numeric * 100, 2)
    END::float8 AS percentage
FROM audit_logs al
WHERE al.tenant_id = $1
  AND al.created_at >= $2::timestamptz
  AND al.created_at < $3::timestamptz
GROUP BY al.action
ORDER BY count DESC
LIMIT 20
`

type GetTopActionsParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type GetTopActionsRow struct {
	ActionType string  `json:"action_type"`
	Count      int32   `json:"count"`
	Percentage float64 `json:"percentage"`
}

// Menghitung aksi terbanyak dari audit_logs untuk periode tertentu.
// Mengembalikan action_type, count, dan percentage dari total.
func (q *Queries) GetTopActions(ctx context.Context, arg GetTopActionsParams) ([]GetTopActionsRow, error) {
	rows, err := q.db.Query(ctx, getTopActions, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopActionsRow{}
	for rows.Next() {
		var i GetTopActionsRow
		if err := rows.Scan(&i.ActionType, &i.Count, &i.Percentage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
