// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: report_jobs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldReportJobs = `-- name: CleanupOldReportJobs :exec
DELETE FROM report_jobs
WHERE created_at < $1
`

// Menghapus job export lama yang sudah melewati batas waktu retensi.
// Digunakan oleh background worker untuk membersihkan data lama.
func (q *Queries) CleanupOldReportJobs(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, cleanupOldReportJobs, createdAt)
	return err
}

const createReportJob = `-- name: CreateReportJob :one

INSERT INTO report_jobs (
    tenant_id, report_type, format,
    filters, requested_by
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, tenant_id, report_type, format, filters, status, download_url, error, requested_by, created_at, updated_at
`

type CreateReportJobParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ReportType  string      `json:"report_type"`
	Format      string      `json:"format"`
	Filters     []byte      `json:"filters"`
	RequestedBy pgtype.UUID `json:"requested_by"`
}

// Kueri SQL untuk operasi CRUD tabel report_jobs.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel report_jobs dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Membuat job export laporan baru dan mengembalikan semua kolom.
func (q *Queries) CreateReportJob(ctx context.Context, arg CreateReportJobParams) (ReportJob, error) {
	row := q.db.QueryRow(ctx, createReportJob,
		arg.TenantID,
		arg.ReportType,
		arg.Format,
		arg.Filters,
		arg.RequestedBy,
	)
	var i ReportJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReportType,
		&i.Format,
		&i.Filters,
		&i.Status,
		&i.DownloadUrl,
		&i.Error,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportJobByID = `-- name: GetReportJobByID :one
SELECT id, tenant_id, report_type, format, filters, status, download_url, error, requested_by, created_at, updated_at FROM report_jobs
WHERE id = $1
`

// Mengambil job export laporan berdasarkan ID.
func (q *Queries) GetReportJobByID(ctx context.Context, id pgtype.UUID) (ReportJob, error) {
	row := q.db.QueryRow(ctx, getReportJobByID, id)
	var i ReportJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReportType,
		&i.Format,
		&i.Filters,
		&i.Status,
		&i.DownloadUrl,
		&i.Error,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReportJobStatus = `-- name: UpdateReportJobStatus :exec
UPDATE report_jobs SET
    status = $2,
    download_url = $3,
    error = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdateReportJobStatusParams struct {
	ID          pgtype.UUID `json:"id"`
	Status      string      `json:"status"`
	DownloadUrl pgtype.Text `json:"download_url"`
	Error       pgtype.Text `json:"error"`
}

// Memperbarui status job export (pending -> processing -> completed/failed).
// Juga mengisi download_url dan error jika ada.
func (q *Queries) UpdateReportJobStatus(ctx context.Context, arg UpdateReportJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateReportJobStatus,
		arg.ID,
		arg.Status,
		arg.DownloadUrl,
		arg.Error,
	)
	return err
}
