// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: report_aggregation_forecast.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMonthlyCustomerHistory = `-- name: GetMonthlyCustomerHistory :many
SELECT
    ROW_NUMBER() OVER (ORDER BY month_series ASC)::float8 - 1 AS x,
    COALESCE((
        SELECT COUNT(*)
        FROM customers c
        WHERE c.tenant_id = $2
          AND c.status = 'aktif'
          AND c.deleted_at IS NULL
          AND c.activation_date <= (month_series + INTERVAL '1 month' - INTERVAL '1 day')::date
    ), 0)::float8 AS y
FROM generate_series(
    DATE_TRUNC('month', CURRENT_DATE - (($1::int - 1) || ' months')::interval),
    DATE_TRUNC('month', CURRENT_DATE),
    '1 month'::interval
) AS month_series
ORDER BY month_series ASC
`

type GetMonthlyCustomerHistoryParams struct {
	Column1  int32       `json:"column_1"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetMonthlyCustomerHistoryRow struct {
	X int32   `json:"x"`
	Y float64 `json:"y"`
}

// Mengambil data historis jumlah pelanggan aktif bulanan untuk N bulan terakhir.
// Digunakan sebagai input linear regression untuk proyeksi pertumbuhan pelanggan.
// Mengembalikan month_index (0-based) dan total_active_customers per bulan.
func (q *Queries) GetMonthlyCustomerHistory(ctx context.Context, arg GetMonthlyCustomerHistoryParams) ([]GetMonthlyCustomerHistoryRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyCustomerHistory, arg.Column1, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyCustomerHistoryRow{}
	for rows.Next() {
		var i GetMonthlyCustomerHistoryRow
		if err := rows.Scan(&i.X, &i.Y); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyReceivablesHistory = `-- name: GetMonthlyReceivablesHistory :many
SELECT
    ROW_NUMBER() OVER (ORDER BY month_series ASC)::float8 - 1 AS x,
    COALESCE((
        SELECT SUM(i.total_amount - i.paid_amount)
        FROM invoices i
        WHERE i.tenant_id = $2
          AND i.status IN ('belum_bayar', 'terlambat', 'bayar_sebagian')
          AND i.due_date <= (month_series + INTERVAL '1 month' - INTERVAL '1 day')::date
          AND (i.total_amount - i.paid_amount) > 0
    ), 0)::float8 AS y
FROM generate_series(
    DATE_TRUNC('month', CURRENT_DATE - (($1::int - 1) || ' months')::interval),
    DATE_TRUNC('month', CURRENT_DATE),
    '1 month'::interval
) AS month_series
ORDER BY month_series ASC
`

type GetMonthlyReceivablesHistoryParams struct {
	Column1  int32       `json:"column_1"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetMonthlyReceivablesHistoryRow struct {
	X int32   `json:"x"`
	Y float64 `json:"y"`
}

// Mengambil data historis piutang bulanan untuk N bulan terakhir.
// Digunakan sebagai input linear regression untuk proyeksi piutang.
// Mengembalikan month_index (0-based) dan total_outstanding per bulan.
func (q *Queries) GetMonthlyReceivablesHistory(ctx context.Context, arg GetMonthlyReceivablesHistoryParams) ([]GetMonthlyReceivablesHistoryRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyReceivablesHistory, arg.Column1, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyReceivablesHistoryRow{}
	for rows.Next() {
		var i GetMonthlyReceivablesHistoryRow
		if err := rows.Scan(&i.X, &i.Y); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyRevenueHistory = `-- name: GetMonthlyRevenueHistory :many

SELECT
    ROW_NUMBER() OVER (ORDER BY month_series ASC)::float8 - 1 AS x,
    COALESCE(SUM(ip.amount), 0)::float8 AS y
FROM generate_series(
    DATE_TRUNC('month', CURRENT_DATE - (($1::int - 1) || ' months')::interval),
    DATE_TRUNC('month', CURRENT_DATE),
    '1 month'::interval
) AS month_series
LEFT JOIN invoice_payments ip ON ip.tenant_id = $2
    AND ip.voided = false
    AND ip.payment_date >= month_series::date
    AND ip.payment_date < (month_series + INTERVAL '1 month')::date
GROUP BY month_series
ORDER BY month_series ASC
`

type GetMonthlyRevenueHistoryParams struct {
	Column1  int32       `json:"column_1"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetMonthlyRevenueHistoryRow struct {
	X int32   `json:"x"`
	Y float64 `json:"y"`
}

// Kueri SQL untuk data historis yang digunakan oleh forecasting engine.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Mengambil data 6 bulan terakhir untuk kalkulasi linear regression.
// Tabel dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Mengambil data historis pendapatan bulanan untuk N bulan terakhir.
// Digunakan sebagai input linear regression untuk proyeksi pendapatan.
// Mengembalikan month_index (0-based) dan total_revenue per bulan.
func (q *Queries) GetMonthlyRevenueHistory(ctx context.Context, arg GetMonthlyRevenueHistoryParams) ([]GetMonthlyRevenueHistoryRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyRevenueHistory, arg.Column1, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyRevenueHistoryRow{}
	for rows.Next() {
		var i GetMonthlyRevenueHistoryRow
		if err := rows.Scan(&i.X, &i.Y); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
