// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: report_aggregation.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgingBuckets = `-- name: GetAgingBuckets :many
SELECT
    label,
    COALESCE(SUM(outstanding), 0)::bigint AS total_amount,
    COUNT(DISTINCT customer_id)::int AS customer_count
FROM (
    SELECT
        i.customer_id,
        (i.total_amount - i.paid_amount) AS outstanding,
        CASE
            WHEN (CURRENT_DATE - i.due_date) BETWEEN 1 AND 7 THEN '1-7 hari'
            WHEN (CURRENT_DATE - i.due_date) BETWEEN 8 AND 14 THEN '8-14 hari'
            WHEN (CURRENT_DATE - i.due_date) BETWEEN 15 AND 30 THEN '15-30 hari'
            WHEN (CURRENT_DATE - i.due_date) > 30 THEN '30+ hari'
        END AS label
    FROM invoices i
    JOIN customers c ON c.id = i.customer_id
    WHERE i.tenant_id = $1
      AND i.status IN ('belum_bayar', 'terlambat', 'bayar_sebagian')
      AND i.due_date < CURRENT_DATE
      AND (i.total_amount - i.paid_amount) > 0
      AND ($2::uuid IS NULL OR c.area_id = $2::uuid)
      AND ($3::uuid IS NULL OR c.package_id = $3::uuid)
) sub
WHERE label IS NOT NULL
GROUP BY label
ORDER BY
    CASE label
        WHEN '1-7 hari' THEN 1
        WHEN '8-14 hari' THEN 2
        WHEN '15-30 hari' THEN 3
        WHEN '30+ hari' THEN 4
    END
`

type GetAgingBucketsParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	AreaID    pgtype.UUID `json:"area_id"`
	PackageID pgtype.UUID `json:"package_id"`
}

type GetAgingBucketsRow struct {
	Label         interface{} `json:"label"`
	TotalAmount   int64       `json:"total_amount"`
	CustomerCount int32       `json:"customer_count"`
}

// Mengelompokkan invoice outstanding ke aging buckets berdasarkan umur tunggakan.
// Bucket: 1-7 hari, 8-14 hari, 15-30 hari, 30+ hari.
// Menghitung total_amount dan customer_count per bucket.
func (q *Queries) GetAgingBuckets(ctx context.Context, arg GetAgingBucketsParams) ([]GetAgingBucketsRow, error) {
	rows, err := q.db.Query(ctx, getAgingBuckets, arg.TenantID, arg.AreaID, arg.PackageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAgingBucketsRow{}
	for rows.Next() {
		var i GetAgingBucketsRow
		if err := rows.Scan(&i.Label, &i.TotalAmount, &i.CustomerCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvgDaysToPay = `-- name: GetAvgDaysToPay :one
SELECT
    COALESCE(
        AVG(ip.payment_date - i.due_date),
        0
    )::float8 AS avg_days_to_pay
FROM invoice_payments ip
JOIN invoices i ON i.id = ip.invoice_id
JOIN customers c ON c.id = i.customer_id
WHERE ip.tenant_id = $1
  AND ip.voided = false
  AND ip.payment_date >= $2
  AND ip.payment_date < $3
  AND ($4::uuid IS NULL OR c.area_id = $4::uuid)
  AND ($5::uuid IS NULL OR c.package_id = $5::uuid)
`

type GetAvgDaysToPayParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	PaymentDate   pgtype.Date `json:"payment_date"`
	PaymentDate_2 pgtype.Date `json:"payment_date_2"`
	AreaID        pgtype.UUID `json:"area_id"`
	PackageID     pgtype.UUID `json:"package_id"`
}

// Menghitung rata-rata hari antara due_date dan payment_date untuk invoice yang sudah dibayar.
// Hanya menghitung invoice lunas dalam periode tertentu.
func (q *Queries) GetAvgDaysToPay(ctx context.Context, arg GetAvgDaysToPayParams) (float64, error) {
	row := q.db.QueryRow(ctx, getAvgDaysToPay,
		arg.TenantID,
		arg.PaymentDate,
		arg.PaymentDate_2,
		arg.AreaID,
		arg.PackageID,
	)
	var avg_days_to_pay float64
	err := row.Scan(&avg_days_to_pay)
	return avg_days_to_pay, err
}

const getCollectionRate = `-- name: GetCollectionRate :one
SELECT
    COALESCE(COUNT(*) FILTER (WHERE i.status = 'lunas'), 0)::bigint AS paid_count,
    COALESCE(COUNT(*), 0)::bigint AS total_due_count,
    CASE
        WHEN COUNT(*) = 0 THEN 0
        ELSE ROUND((COUNT(*) FILTER (WHERE i.status = 'lunas'))::numeric / COUNT(*)::numeric * 100, 2)
    END::float8 AS collection_rate
FROM invoices i
JOIN customers c ON c.id = i.customer_id
WHERE i.tenant_id = $1
  AND i.due_date >= $2
  AND i.due_date < $3
  AND i.status != 'batal'
  AND ($4::uuid IS NULL OR c.area_id = $4::uuid)
  AND ($5::uuid IS NULL OR c.package_id = $5::uuid)
`

type GetCollectionRateParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	DueDate   pgtype.Date `json:"due_date"`
	DueDate_2 pgtype.Date `json:"due_date_2"`
	AreaID    pgtype.UUID `json:"area_id"`
	PackageID pgtype.UUID `json:"package_id"`
}

type GetCollectionRateRow struct {
	PaidCount      int64   `json:"paid_count"`
	TotalDueCount  int64   `json:"total_due_count"`
	CollectionRate float64 `json:"collection_rate"`
}

// Menghitung collection rate: persentase invoice terbayar vs total invoice jatuh tempo.
// Collection rate = (jumlah invoice lunas / total invoice jatuh tempo) * 100.
func (q *Queries) GetCollectionRate(ctx context.Context, arg GetCollectionRateParams) (GetCollectionRateRow, error) {
	row := q.db.QueryRow(ctx, getCollectionRate,
		arg.TenantID,
		arg.DueDate,
		arg.DueDate_2,
		arg.AreaID,
		arg.PackageID,
	)
	var i GetCollectionRateRow
	err := row.Scan(&i.PaidCount, &i.TotalDueCount, &i.CollectionRate)
	return i, err
}

const getDailyPayments = `-- name: GetDailyPayments :many
SELECT
    ip.payment_date::text AS date,
    COALESCE(SUM(ip.amount), 0)::bigint AS total_amount,
    COUNT(*)::int AS transaction_count
FROM invoice_payments ip
JOIN invoices i ON i.id = ip.invoice_id
JOIN customers c ON c.id = i.customer_id
WHERE ip.tenant_id = $1
  AND ip.voided = false
  AND ip.payment_date >= $2
  AND ip.payment_date < $3
  AND ($4::uuid IS NULL OR c.area_id = $4::uuid)
  AND ($5::uuid IS NULL OR c.package_id = $5::uuid)
GROUP BY ip.payment_date
ORDER BY ip.payment_date ASC
`

type GetDailyPaymentsParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	PaymentDate   pgtype.Date `json:"payment_date"`
	PaymentDate_2 pgtype.Date `json:"payment_date_2"`
	AreaID        pgtype.UUID `json:"area_id"`
	PackageID     pgtype.UUID `json:"package_id"`
}

type GetDailyPaymentsRow struct {
	Date             string `json:"date"`
	TotalAmount      int64  `json:"total_amount"`
	TransactionCount int32  `json:"transaction_count"`
}

// Menghitung total pembayaran per hari dalam periode tertentu.
// Mengembalikan date, total_amount, dan transaction_count per hari.
func (q *Queries) GetDailyPayments(ctx context.Context, arg GetDailyPaymentsParams) ([]GetDailyPaymentsRow, error) {
	rows, err := q.db.Query(ctx, getDailyPayments,
		arg.TenantID,
		arg.PaymentDate,
		arg.PaymentDate_2,
		arg.AreaID,
		arg.PackageID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyPaymentsRow{}
	for rows.Next() {
		var i GetDailyPaymentsRow
		if err := rows.Scan(&i.Date, &i.TotalAmount, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyRevenueTrend = `-- name: GetMonthlyRevenueTrend :many
SELECT
    TO_CHAR(DATE_TRUNC('month', ip.payment_date), 'YYYY-MM') AS month,
    COALESCE(SUM(ip.amount), 0)::bigint AS total_revenue,
    COALESCE(SUM(CASE WHEN ii.item_type = 'monthly' THEN ip.amount ELSE 0 END), 0)::bigint AS monthly_subscription,
    0::bigint AS voucher_sales,
    COALESCE(SUM(CASE WHEN ii.item_type NOT IN ('monthly') THEN ip.amount ELSE 0 END), 0)::bigint AS other_revenue
FROM invoice_payments ip
JOIN invoices i ON i.id = ip.invoice_id
JOIN invoice_items ii ON ii.invoice_id = i.id
WHERE ip.tenant_id = $1
  AND ip.voided = false
  AND ip.payment_date >= (CURRENT_DATE - INTERVAL '12 months')
GROUP BY DATE_TRUNC('month', ip.payment_date)
ORDER BY DATE_TRUNC('month', ip.payment_date) ASC
`

type GetMonthlyRevenueTrendRow struct {
	Month               string `json:"month"`
	TotalRevenue        int64  `json:"total_revenue"`
	MonthlySubscription int64  `json:"monthly_subscription"`
	VoucherSales        int64  `json:"voucher_sales"`
	OtherRevenue        int64  `json:"other_revenue"`
}

// Menghitung trend pendapatan per bulan untuk 12 bulan terakhir.
// Mengembalikan total_revenue, monthly_subscription, voucher_sales, dan other_revenue per bulan.
func (q *Queries) GetMonthlyRevenueTrend(ctx context.Context, tenantID pgtype.UUID) ([]GetMonthlyRevenueTrendRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyRevenueTrend, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyRevenueTrendRow{}
	for rows.Next() {
		var i GetMonthlyRevenueTrendRow
		if err := rows.Scan(
			&i.Month,
			&i.TotalRevenue,
			&i.MonthlySubscription,
			&i.VoucherSales,
			&i.OtherRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentDistribution = `-- name: GetPaymentDistribution :many
SELECT
    ip.payment_method AS method_name,
    COALESCE(SUM(ip.amount), 0)::bigint AS total_amount,
    COUNT(*)::int AS transaction_count,
    CASE
        WHEN SUM(SUM(ip.amount)) OVER () = 0 THEN 0
        ELSE ROUND(SUM(ip.amount)::numeric / SUM(SUM(ip.amount)) OVER ()::numeric * 100, 2)
    END::float8 AS percentage
FROM invoice_payments ip
JOIN invoices i ON i.id = ip.invoice_id
JOIN customers c ON c.id = i.customer_id
WHERE ip.tenant_id = $1
  AND ip.voided = false
  AND ip.payment_date >= $2
  AND ip.payment_date < $3
  AND ($4::uuid IS NULL OR c.area_id = $4::uuid)
  AND ($5::uuid IS NULL OR c.package_id = $5::uuid)
GROUP BY ip.payment_method
ORDER BY total_amount DESC
`

type GetPaymentDistributionParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	PaymentDate   pgtype.Date `json:"payment_date"`
	PaymentDate_2 pgtype.Date `json:"payment_date_2"`
	AreaID        pgtype.UUID `json:"area_id"`
	PackageID     pgtype.UUID `json:"package_id"`
}

type GetPaymentDistributionRow struct {
	MethodName       string  `json:"method_name"`
	TotalAmount      int64   `json:"total_amount"`
	TransactionCount int32   `json:"transaction_count"`
	Percentage       float64 `json:"percentage"`
}

// Menghitung distribusi pembayaran per metode pembayaran.
// Mengembalikan method_name, total_amount, transaction_count, dan percentage.
func (q *Queries) GetPaymentDistribution(ctx context.Context, arg GetPaymentDistributionParams) ([]GetPaymentDistributionRow, error) {
	rows, err := q.db.Query(ctx, getPaymentDistribution,
		arg.TenantID,
		arg.PaymentDate,
		arg.PaymentDate_2,
		arg.AreaID,
		arg.PackageID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPaymentDistributionRow{}
	for rows.Next() {
		var i GetPaymentDistributionRow
		if err := rows.Scan(
			&i.MethodName,
			&i.TotalAmount,
			&i.TransactionCount,
			&i.Percentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReceivablesTrend = `-- name: GetReceivablesTrend :many
SELECT
    TO_CHAR(month_series, 'YYYY-MM') AS month,
    COALESCE(SUM(i.total_amount - i.paid_amount), 0)::bigint AS total_outstanding
FROM generate_series(
    DATE_TRUNC('month', CURRENT_DATE - INTERVAL '5 months'),
    DATE_TRUNC('month', CURRENT_DATE),
    '1 month'::interval
) AS month_series
LEFT JOIN invoices i ON i.tenant_id = $1
    AND i.status IN ('belum_bayar', 'terlambat', 'bayar_sebagian')
    AND i.due_date <= (month_series + INTERVAL '1 month' - INTERVAL '1 day')::date
    AND (i.total_amount - i.paid_amount) > 0
GROUP BY month_series
ORDER BY month_series ASC
`

type GetReceivablesTrendRow struct {
	Month            string `json:"month"`
	TotalOutstanding int64  `json:"total_outstanding"`
}

// Menghitung trend piutang per bulan untuk 6 bulan terakhir.
// Total outstanding dihitung dari invoice yang belum lunas pada akhir setiap bulan.
func (q *Queries) GetReceivablesTrend(ctx context.Context, tenantID pgtype.UUID) ([]GetReceivablesTrendRow, error) {
	rows, err := q.db.Query(ctx, getReceivablesTrend, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReceivablesTrendRow{}
	for rows.Next() {
		var i GetReceivablesTrendRow
		if err := rows.Scan(&i.Month, &i.TotalOutstanding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueByArea = `-- name: GetRevenueByArea :many
SELECT
    a.id AS area_id,
    a.name AS area_name,
    COUNT(DISTINCT c.id)::int AS customer_count,
    COALESCE(SUM(ip.amount), 0)::bigint AS total_revenue,
    COALESCE((
        SELECT SUM(inv.total_amount - inv.paid_amount)
        FROM invoices inv
        JOIN customers cust ON cust.id = inv.customer_id
        WHERE inv.tenant_id = $1
          AND cust.area_id = a.id
          AND inv.status IN ('belum_bayar', 'terlambat', 'bayar_sebagian')
          AND (inv.total_amount - inv.paid_amount) > 0
    ), 0)::bigint AS total_outstanding,
    CASE
        WHEN COUNT(DISTINCT c.id) = 0 THEN 0
        ELSE (COALESCE(SUM(ip.amount), 0) / COUNT(DISTINCT c.id))
    END::bigint AS arpu
FROM areas a
LEFT JOIN customers c ON c.area_id = a.id AND c.deleted_at IS NULL AND c.status = 'aktif'
LEFT JOIN invoices i ON i.customer_id = c.id
    AND i.status != 'batal'
LEFT JOIN invoice_payments ip ON ip.invoice_id = i.id
    AND ip.voided = false
    AND ip.payment_date >= $2
    AND ip.payment_date < $3
WHERE a.tenant_id = $1
GROUP BY a.id, a.name
ORDER BY total_revenue DESC
`

type GetRevenueByAreaParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	PaymentDate   pgtype.Date `json:"payment_date"`
	PaymentDate_2 pgtype.Date `json:"payment_date_2"`
}

type GetRevenueByAreaRow struct {
	AreaID           pgtype.UUID `json:"area_id"`
	AreaName         string      `json:"area_name"`
	CustomerCount    int32       `json:"customer_count"`
	TotalRevenue     int64       `json:"total_revenue"`
	TotalOutstanding int64       `json:"total_outstanding"`
	Arpu             int64       `json:"arpu"`
}

// Menghitung pendapatan, piutang, dan ARPU per area.
// JOIN areas untuk mendapatkan nama area.
// ARPU = total_revenue / customer_count.
func (q *Queries) GetRevenueByArea(ctx context.Context, arg GetRevenueByAreaParams) ([]GetRevenueByAreaRow, error) {
	rows, err := q.db.Query(ctx, getRevenueByArea, arg.TenantID, arg.PaymentDate, arg.PaymentDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRevenueByAreaRow{}
	for rows.Next() {
		var i GetRevenueByAreaRow
		if err := rows.Scan(
			&i.AreaID,
			&i.AreaName,
			&i.CustomerCount,
			&i.TotalRevenue,
			&i.TotalOutstanding,
			&i.Arpu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueSummary = `-- name: GetRevenueSummary :one

SELECT
    COALESCE(SUM(CASE WHEN ii.item_type = 'monthly' THEN ip.amount ELSE 0 END), 0)::bigint AS monthly_subscription,
    COALESCE((
        SELECT SUM(v.sell_price_snapshot)
        FROM vouchers v
        WHERE v.tenant_id = $1
          AND v.status IN ('terjual', 'aktif', 'selesai')
          AND v.purchased_at >= $2
          AND v.purchased_at < $3
    ), 0)::bigint AS voucher_sales,
    COALESCE(SUM(CASE WHEN ii.item_type = 'installation' THEN ip.amount ELSE 0 END), 0)::bigint AS installation_fees,
    COALESCE(SUM(CASE WHEN ii.item_type = 'penalty' THEN ip.amount ELSE 0 END), 0)::bigint AS late_fees,
    COALESCE(SUM(CASE WHEN ii.item_type NOT IN ('monthly', 'installation', 'penalty') THEN ip.amount ELSE 0 END), 0)::bigint AS other,
    (
        COALESCE(SUM(ip.amount), 0) +
        COALESCE((
            SELECT SUM(v2.sell_price_snapshot)
            FROM vouchers v2
            WHERE v2.tenant_id = $1
              AND v2.status IN ('terjual', 'aktif', 'selesai')
              AND v2.purchased_at >= $2
              AND v2.purchased_at < $3
        ), 0)
    )::bigint AS total
FROM invoice_payments ip
JOIN invoices i ON i.id = ip.invoice_id
JOIN invoice_items ii ON ii.invoice_id = i.id
JOIN customers c ON c.id = i.customer_id
WHERE ip.tenant_id = $1
  AND ip.voided = false
  AND ip.payment_date >= $2
  AND ip.payment_date < $3
  AND ($4::uuid IS NULL OR c.area_id = $4::uuid)
  AND ($5::uuid IS NULL OR c.package_id = $5::uuid)
`

type GetRevenueSummaryParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	PurchasedAt   pgtype.Timestamptz `json:"purchased_at"`
	PurchasedAt_2 pgtype.Timestamptz `json:"purchased_at_2"`
	AreaID        pgtype.UUID        `json:"area_id"`
	PackageID     pgtype.UUID        `json:"package_id"`
}

type GetRevenueSummaryRow struct {
	MonthlySubscription int64 `json:"monthly_subscription"`
	VoucherSales        int64 `json:"voucher_sales"`
	InstallationFees    int64 `json:"installation_fees"`
	LateFees            int64 `json:"late_fees"`
	Other               int64 `json:"other"`
	Total               int64 `json:"total"`
}

// Kueri SQL untuk aggregasi laporan keuangan (financial reports).
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Semua query mendukung filter opsional area_id dan package_id via sqlc.narg.
// Tabel dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Menghitung ringkasan pendapatan per sumber untuk periode tertentu.
// Sumber: bulanan (tagihan bulanan), installation (biaya pasang), denda (denda),
// voucher_sales (penjualan voucher), dan other (sisa item types).
// Filter opsional: area_id dan package_id.
func (q *Queries) GetRevenueSummary(ctx context.Context, arg GetRevenueSummaryParams) (GetRevenueSummaryRow, error) {
	row := q.db.QueryRow(ctx, getRevenueSummary,
		arg.TenantID,
		arg.PurchasedAt,
		arg.PurchasedAt_2,
		arg.AreaID,
		arg.PackageID,
	)
	var i GetRevenueSummaryRow
	err := row.Scan(
		&i.MonthlySubscription,
		&i.VoucherSales,
		&i.InstallationFees,
		&i.LateFees,
		&i.Other,
		&i.Total,
	)
	return i, err
}

const getTopDebtors = `-- name: GetTopDebtors :many
SELECT
    c.id AS customer_id,
    c.name AS customer_name,
    COALESCE(SUM(i.total_amount - i.paid_amount), 0)::bigint AS total_outstanding,
    COALESCE(
        EXTRACT(MONTH FROM AGE(CURRENT_DATE, MIN(i.due_date)))::int +
        EXTRACT(YEAR FROM AGE(CURRENT_DATE, MIN(i.due_date)))::int * 12,
        0
    )::int AS months_overdue
FROM invoices i
JOIN customers c ON c.id = i.customer_id
WHERE i.tenant_id = $1
  AND i.status IN ('belum_bayar', 'terlambat', 'bayar_sebagian')
  AND (i.total_amount - i.paid_amount) > 0
  AND ($2::uuid IS NULL OR c.area_id = $2::uuid)
  AND ($3::uuid IS NULL OR c.package_id = $3::uuid)
GROUP BY c.id, c.name
ORDER BY total_outstanding DESC
LIMIT 10
`

type GetTopDebtorsParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	AreaID    pgtype.UUID `json:"area_id"`
	PackageID pgtype.UUID `json:"package_id"`
}

type GetTopDebtorsRow struct {
	CustomerID       pgtype.UUID `json:"customer_id"`
	CustomerName     string      `json:"customer_name"`
	TotalOutstanding int64       `json:"total_outstanding"`
	MonthsOverdue    int32       `json:"months_overdue"`
}

// Mengambil 10 debitur terbesar berdasarkan total outstanding.
// Menghitung months_overdue dari invoice tertua yang belum lunas.
func (q *Queries) GetTopDebtors(ctx context.Context, arg GetTopDebtorsParams) ([]GetTopDebtorsRow, error) {
	rows, err := q.db.Query(ctx, getTopDebtors, arg.TenantID, arg.AreaID, arg.PackageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopDebtorsRow{}
	for rows.Next() {
		var i GetTopDebtorsRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.CustomerName,
			&i.TotalOutstanding,
			&i.MonthsOverdue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoucherRevenueByPackage = `-- name: GetVoucherRevenueByPackage :many
SELECT
    p.name AS package_name,
    COALESCE(SUM(v.sell_price_snapshot), 0)::bigint AS total_revenue,
    COUNT(*)::int AS voucher_count,
    CASE
        WHEN SUM(SUM(v.sell_price_snapshot)) OVER () = 0 THEN 0
        ELSE ROUND(SUM(v.sell_price_snapshot)::numeric / SUM(SUM(v.sell_price_snapshot)) OVER ()::numeric * 100, 2)
    END::float8 AS percentage
FROM vouchers v
JOIN packages p ON p.id = v.package_id
WHERE v.tenant_id = $1
  AND v.status IN ('terjual', 'aktif', 'selesai')
  AND v.purchased_at >= $2
  AND v.purchased_at < $3
GROUP BY p.name
ORDER BY total_revenue DESC
`

type GetVoucherRevenueByPackageParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	PurchasedAt   pgtype.Timestamptz `json:"purchased_at"`
	PurchasedAt_2 pgtype.Timestamptz `json:"purchased_at_2"`
}

type GetVoucherRevenueByPackageRow struct {
	PackageName  string  `json:"package_name"`
	TotalRevenue int64   `json:"total_revenue"`
	VoucherCount int32   `json:"voucher_count"`
	Percentage   float64 `json:"percentage"`
}

// Menghitung pendapatan voucher per paket.
// Mengembalikan package_name, total_revenue, voucher_count, dan percentage.
func (q *Queries) GetVoucherRevenueByPackage(ctx context.Context, arg GetVoucherRevenueByPackageParams) ([]GetVoucherRevenueByPackageRow, error) {
	rows, err := q.db.Query(ctx, getVoucherRevenueByPackage, arg.TenantID, arg.PurchasedAt, arg.PurchasedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVoucherRevenueByPackageRow{}
	for rows.Next() {
		var i GetVoucherRevenueByPackageRow
		if err := rows.Scan(
			&i.PackageName,
			&i.TotalRevenue,
			&i.VoucherCount,
			&i.Percentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoucherRevenueByReseller = `-- name: GetVoucherRevenueByReseller :many
SELECT
    r.name AS reseller_name,
    COALESCE(SUM(v.sell_price_snapshot), 0)::bigint AS total_revenue,
    COUNT(*)::int AS voucher_count,
    COALESCE(SUM(v.sell_price_snapshot - COALESCE(v.reseller_price_snapshot, 0)), 0)::bigint AS reseller_margin
FROM vouchers v
JOIN resellers r ON r.id = v.reseller_id
WHERE v.tenant_id = $1
  AND v.status IN ('terjual', 'aktif', 'selesai')
  AND v.purchased_at >= $2
  AND v.purchased_at < $3
  AND v.reseller_id IS NOT NULL
GROUP BY r.name
ORDER BY total_revenue DESC
`

type GetVoucherRevenueByResellerParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	PurchasedAt   pgtype.Timestamptz `json:"purchased_at"`
	PurchasedAt_2 pgtype.Timestamptz `json:"purchased_at_2"`
}

type GetVoucherRevenueByResellerRow struct {
	ResellerName   string `json:"reseller_name"`
	TotalRevenue   int64  `json:"total_revenue"`
	VoucherCount   int32  `json:"voucher_count"`
	ResellerMargin int64  `json:"reseller_margin"`
}

// Menghitung pendapatan voucher per reseller.
// Mengembalikan reseller_name, total_revenue, voucher_count, dan reseller_margin.
// Reseller margin = sell_price_snapshot - reseller_price_snapshot.
func (q *Queries) GetVoucherRevenueByReseller(ctx context.Context, arg GetVoucherRevenueByResellerParams) ([]GetVoucherRevenueByResellerRow, error) {
	rows, err := q.db.Query(ctx, getVoucherRevenueByReseller, arg.TenantID, arg.PurchasedAt, arg.PurchasedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVoucherRevenueByResellerRow{}
	for rows.Next() {
		var i GetVoucherRevenueByResellerRow
		if err := rows.Scan(
			&i.ResellerName,
			&i.TotalRevenue,
			&i.VoucherCount,
			&i.ResellerMargin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
