// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: report_schedules.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReportSchedule = `-- name: CreateReportSchedule :one

INSERT INTO report_schedules (
    tenant_id, report_type, schedule_type,
    format, recipients, filters, created_by_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, tenant_id, report_type, schedule_type, format, recipients, filters, is_active, created_by_id, created_at, updated_at
`

type CreateReportScheduleParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ReportType   string      `json:"report_type"`
	ScheduleType string      `json:"schedule_type"`
	Format       string      `json:"format"`
	Recipients   []byte      `json:"recipients"`
	Filters      []byte      `json:"filters"`
	CreatedByID  pgtype.UUID `json:"created_by_id"`
}

// Kueri SQL untuk operasi CRUD tabel report_schedules.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel report_schedules dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Membuat jadwal laporan baru dan mengembalikan semua kolom.
func (q *Queries) CreateReportSchedule(ctx context.Context, arg CreateReportScheduleParams) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, createReportSchedule,
		arg.TenantID,
		arg.ReportType,
		arg.ScheduleType,
		arg.Format,
		arg.Recipients,
		arg.Filters,
		arg.CreatedByID,
	)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReportType,
		&i.ScheduleType,
		&i.Format,
		&i.Recipients,
		&i.Filters,
		&i.IsActive,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateReportSchedule = `-- name: DeactivateReportSchedule :exec
UPDATE report_schedules SET
    is_active = false,
    updated_at = NOW()
WHERE id = $1
`

// Menonaktifkan jadwal laporan (atur is_active = false).
func (q *Queries) DeactivateReportSchedule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateReportSchedule, id)
	return err
}

const getReportScheduleByID = `-- name: GetReportScheduleByID :one
SELECT id, tenant_id, report_type, schedule_type, format, recipients, filters, is_active, created_by_id, created_at, updated_at FROM report_schedules
WHERE id = $1
`

// Mengambil jadwal laporan berdasarkan ID.
func (q *Queries) GetReportScheduleByID(ctx context.Context, id pgtype.UUID) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, getReportScheduleByID, id)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReportType,
		&i.ScheduleType,
		&i.Format,
		&i.Recipients,
		&i.Filters,
		&i.IsActive,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueSchedules = `-- name: ListDueSchedules :many
SELECT id, tenant_id, report_type, schedule_type, format, recipients, filters, is_active, created_by_id, created_at, updated_at FROM report_schedules
WHERE schedule_type = $1 AND is_active = true
`

// Mengambil semua jadwal aktif berdasarkan tipe jadwal (untuk worker scheduler).
// Digunakan oleh background worker untuk menentukan jadwal mana yang perlu dijalankan.
func (q *Queries) ListDueSchedules(ctx context.Context, scheduleType string) ([]ReportSchedule, error) {
	rows, err := q.db.Query(ctx, listDueSchedules, scheduleType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSchedule{}
	for rows.Next() {
		var i ReportSchedule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ReportType,
			&i.ScheduleType,
			&i.Format,
			&i.Recipients,
			&i.Filters,
			&i.IsActive,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportSchedulesByTenant = `-- name: ListReportSchedulesByTenant :many
SELECT id, tenant_id, report_type, schedule_type, format, recipients, filters, is_active, created_by_id, created_at, updated_at FROM report_schedules
WHERE tenant_id = $1 AND is_active = true
ORDER BY created_at DESC
`

// Mengambil semua jadwal laporan aktif untuk tenant, diurutkan berdasarkan created_at.
func (q *Queries) ListReportSchedulesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ReportSchedule, error) {
	rows, err := q.db.Query(ctx, listReportSchedulesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSchedule{}
	for rows.Next() {
		var i ReportSchedule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ReportType,
			&i.ScheduleType,
			&i.Format,
			&i.Recipients,
			&i.Filters,
			&i.IsActive,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportSchedule = `-- name: UpdateReportSchedule :one
UPDATE report_schedules SET
    report_type = $2,
    schedule_type = $3,
    format = $4,
    recipients = $5,
    filters = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, report_type, schedule_type, format, recipients, filters, is_active, created_by_id, created_at, updated_at
`

type UpdateReportScheduleParams struct {
	ID           pgtype.UUID `json:"id"`
	ReportType   string      `json:"report_type"`
	ScheduleType string      `json:"schedule_type"`
	Format       string      `json:"format"`
	Recipients   []byte      `json:"recipients"`
	Filters      []byte      `json:"filters"`
}

// Memperbarui jadwal laporan (tipe, format, penerima, filter).
func (q *Queries) UpdateReportSchedule(ctx context.Context, arg UpdateReportScheduleParams) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, updateReportSchedule,
		arg.ID,
		arg.ReportType,
		arg.ScheduleType,
		arg.Format,
		arg.Recipients,
		arg.Filters,
	)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReportType,
		&i.ScheduleType,
		&i.Format,
		&i.Recipients,
		&i.Filters,
		&i.IsActive,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
