// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report_aggregation_customer.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getARPU = `-- name: GetARPU :one
SELECT
    CASE
        WHEN COALESCE((
            SELECT COUNT(*)
            FROM customers c2
            WHERE c2.tenant_id = $1
              AND c2.status = 'aktif'
              AND c2.deleted_at IS NULL
        ), 0) = 0 THEN 0
        ELSE (
            COALESCE((
                SELECT SUM(ip.amount)
                FROM invoice_payments ip
                WHERE ip.tenant_id = $1
                  AND ip.voided = false
                  AND ip.payment_date >= $2::date
                  AND ip.payment_date < $3::date
            ), 0) /
            GREATEST((
                SELECT COUNT(*)
                FROM customers c3
                WHERE c3.tenant_id = $1
                  AND c3.status = 'aktif'
                  AND c3.deleted_at IS NULL
            ), 1)
        )
    END::bigint AS arpu
`

type GetARPUParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

// Menghitung Average Revenue Per User (ARPU) untuk periode tertentu.
// ARPU = total revenue / jumlah pelanggan aktif rata-rata.
func (q *Queries) GetARPU(ctx context.Context, arg GetARPUParams) (int64, error) {
	row := q.db.QueryRow(ctx, getARPU, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	var arpu int64
	err := row.Scan(&arpu)
	return arpu, err
}

const getAvgCustomerLifetime = `-- name: GetAvgCustomerLifetime :one
SELECT
    COALESCE(
        AVG(
            EXTRACT(EPOCH FROM (c.updated_at - c.activation_date::timestamptz)) / (30.44 * 86400)
        ),
        0
    )::float8 AS avg_lifetime_months
FROM customers c
WHERE c.tenant_id = $1
  AND c.status = 'berhenti'
  AND c.updated_at >= $2::timestamptz
  AND c.updated_at < $3::timestamptz
`

type GetAvgCustomerLifetimeParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

// Menghitung rata-rata masa berlangganan pelanggan yang berhenti (dalam bulan).
// Lifetime = selisih antara activation_date dan updated_at (saat berhenti).
func (q *Queries) GetAvgCustomerLifetime(ctx context.Context, arg GetAvgCustomerLifetimeParams) (float64, error) {
	row := q.db.QueryRow(ctx, getAvgCustomerLifetime, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	var avg_lifetime_months float64
	err := row.Scan(&avg_lifetime_months)
	return avg_lifetime_months, err
}

const getCLV = `-- name: GetCLV :one
SELECT
    CASE
        WHEN COALESCE((
            SELECT COUNT(*)
            FROM customers c2
            WHERE c2.tenant_id = $1
              AND c2.status = 'aktif'
              AND c2.deleted_at IS NULL
        ), 0) = 0 THEN 0
        ELSE (
            -- ARPU
            COALESCE((
                SELECT SUM(ip.amount)
                FROM invoice_payments ip
                WHERE ip.tenant_id = $1
                  AND ip.voided = false
                  AND ip.payment_date >= $2::date
                  AND ip.payment_date < $3::date
            ), 0) /
            GREATEST((
                SELECT COUNT(*)
                FROM customers c3
                WHERE c3.tenant_id = $1
                  AND c3.status = 'aktif'
                  AND c3.deleted_at IS NULL
            ), 1)
        ) *
        -- Rata-rata lifetime (bulan), minimal 1 bulan
        GREATEST(
            COALESCE((
                SELECT AVG(
                    EXTRACT(EPOCH FROM (c4.updated_at - c4.activation_date::timestamptz)) / (30.44 * 86400)
                )
                FROM customers c4
                WHERE c4.tenant_id = $1
                  AND c4.status = 'berhenti'
            ), 12)::bigint,
            1
        )
    END::bigint AS clv
`

type GetCLVParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

// Menghitung Customer Lifetime Value (CLV) untuk periode tertentu.
// CLV = ARPU * rata-rata lifetime pelanggan (dalam bulan).
// Menggunakan semua pelanggan yang pernah berhenti untuk menghitung avg lifetime.
func (q *Queries) GetCLV(ctx context.Context, arg GetCLVParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCLV, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	var clv int64
	err := row.Scan(&clv)
	return clv, err
}

const getChurnAnalysis = `-- name: GetChurnAnalysis :one
SELECT
    COALESCE(COUNT(*) FILTER (
        WHERE c.status = 'berhenti'
          AND c.updated_at >= $2::timestamptz
          AND c.updated_at < $3::timestamptz
    ), 0)::int AS churned_count,
    CASE
        WHEN COUNT(*) FILTER (
            WHERE c.status != 'berhenti'
              AND c.deleted_at IS NULL
              AND c.activation_date < $2::date
        ) = 0 THEN 0
        ELSE ROUND(
            COUNT(*) FILTER (
                WHERE c.status = 'berhenti'
                  AND c.updated_at >= $2::timestamptz
                  AND c.updated_at < $3::timestamptz
            )::numeric /
            GREATEST(COUNT(*) FILTER (
                WHERE c.activation_date < $2::date
                  AND (c.status != 'berhenti' OR c.updated_at >= $2::timestamptz)
                  AND (c.deleted_at IS NULL OR c.deleted_at >= $2::timestamptz)
            ), 1)::numeric * 100,
            2
        )
    END::float8 AS churn_rate
FROM customers c
WHERE c.tenant_id = $1
`

type GetChurnAnalysisParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type GetChurnAnalysisRow struct {
	ChurnedCount int32   `json:"churned_count"`
	ChurnRate    float64 `json:"churn_rate"`
}

// Menghitung jumlah pelanggan churn dan churn rate untuk periode tertentu.
// Churn rate = churned / total_active_at_start * 100.
func (q *Queries) GetChurnAnalysis(ctx context.Context, arg GetChurnAnalysisParams) (GetChurnAnalysisRow, error) {
	row := q.db.QueryRow(ctx, getChurnAnalysis, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	var i GetChurnAnalysisRow
	err := row.Scan(&i.ChurnedCount, &i.ChurnRate)
	return i, err
}

const getChurnByArea = `-- name: GetChurnByArea :many
SELECT
    COALESCE(a.name, 'Tanpa Area') AS name,
    COUNT(c.id)::int AS count,
    CASE
        WHEN SUM(COUNT(c.id)) OVER () = 0 THEN 0
        ELSE ROUND(COUNT(c.id)::numeric / SUM(COUNT(c.id)) OVER ()::numeric * 100, 2)
    END::float8 AS percentage
FROM customers c
LEFT JOIN areas a ON a.id = c.area_id
WHERE c.tenant_id = $1
  AND c.status = 'berhenti'
  AND c.updated_at >= $2::timestamptz
  AND c.updated_at < $3::timestamptz
GROUP BY a.name
ORDER BY count DESC
`

type GetChurnByAreaParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type GetChurnByAreaRow struct {
	Name       string  `json:"name"`
	Count      int32   `json:"count"`
	Percentage float64 `json:"percentage"`
}

// Menghitung churn per area.
// Mengembalikan area_name, churned_count, dan percentage.
func (q *Queries) GetChurnByArea(ctx context.Context, arg GetChurnByAreaParams) ([]GetChurnByAreaRow, error) {
	rows, err := q.db.Query(ctx, getChurnByArea, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChurnByAreaRow{}
	for rows.Next() {
		var i GetChurnByAreaRow
		if err := rows.Scan(&i.Name, &i.Count, &i.Percentage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChurnByPackage = `-- name: GetChurnByPackage :many
SELECT
    p.name AS name,
    COUNT(c.id)::int AS count,
    CASE
        WHEN SUM(COUNT(c.id)) OVER () = 0 THEN 0
        ELSE ROUND(COUNT(c.id)::numeric / SUM(COUNT(c.id)) OVER ()::numeric * 100, 2)
    END::float8 AS percentage
FROM customers c
JOIN packages p ON p.id = c.package_id
WHERE c.tenant_id = $1
  AND c.status = 'berhenti'
  AND c.updated_at >= $2::timestamptz
  AND c.updated_at < $3::timestamptz
GROUP BY p.name
ORDER BY count DESC
`

type GetChurnByPackageParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type GetChurnByPackageRow struct {
	Name       string  `json:"name"`
	Count      int32   `json:"count"`
	Percentage float64 `json:"percentage"`
}

// Menghitung churn per paket.
// Mengembalikan package_name, churned_count, dan percentage.
func (q *Queries) GetChurnByPackage(ctx context.Context, arg GetChurnByPackageParams) ([]GetChurnByPackageRow, error) {
	rows, err := q.db.Query(ctx, getChurnByPackage, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChurnByPackageRow{}
	for rows.Next() {
		var i GetChurnByPackageRow
		if err := rows.Scan(&i.Name, &i.Count, &i.Percentage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChurnByReason = `-- name: GetChurnByReason :many
SELECT
    COALESCE(NULLIF(TRIM(c.notes), ''), 'Tidak diketahui') AS reason,
    COUNT(*)::int AS count,
    CASE
        WHEN SUM(COUNT(*)) OVER () = 0 THEN 0
        ELSE ROUND(COUNT(*)::numeric / SUM(COUNT(*)) OVER ()::numeric * 100, 2)
    END::float8 AS percentage
FROM customers c
WHERE c.tenant_id = $1
  AND c.status = 'berhenti'
  AND c.updated_at >= $2::timestamptz
  AND c.updated_at < $3::timestamptz
GROUP BY COALESCE(NULLIF(TRIM(c.notes), ''), 'Tidak diketahui')
ORDER BY count DESC
`

type GetChurnByReasonParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type GetChurnByReasonRow struct {
	Reason     interface{} `json:"reason"`
	Count      int32       `json:"count"`
	Percentage float64     `json:"percentage"`
}

// Menghitung churn per alasan berhenti.
// Alasan diambil dari field notes pelanggan yang berhenti.
// Jika notes kosong, alasan = 'Tidak diketahui'.
func (q *Queries) GetChurnByReason(ctx context.Context, arg GetChurnByReasonParams) ([]GetChurnByReasonRow, error) {
	rows, err := q.db.Query(ctx, getChurnByReason, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChurnByReasonRow{}
	for rows.Next() {
		var i GetChurnByReasonRow
		if err := rows.Scan(&i.Reason, &i.Count, &i.Percentage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerDistributionByArea = `-- name: GetCustomerDistributionByArea :many
SELECT
    a.id::text AS id,
    a.name AS name,
    COUNT(c.id)::int AS count,
    CASE
        WHEN SUM(COUNT(c.id)) OVER () = 0 THEN 0
        ELSE ROUND(COUNT(c.id)::numeric / SUM(COUNT(c.id)) OVER ()::numeric * 100, 2)
    END::float8 AS percentage
FROM areas a
LEFT JOIN customers c ON c.area_id = a.id
    AND c.status = 'aktif'
    AND c.deleted_at IS NULL
WHERE a.tenant_id = $1
GROUP BY a.id, a.name
ORDER BY count DESC
`

type GetCustomerDistributionByAreaRow struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Count      int32   `json:"count"`
	Percentage float64 `json:"percentage"`
}

// Menghitung distribusi pelanggan aktif per area.
// Mengembalikan area_id, area_name, customer_count, dan percentage.
func (q *Queries) GetCustomerDistributionByArea(ctx context.Context, tenantID pgtype.UUID) ([]GetCustomerDistributionByAreaRow, error) {
	rows, err := q.db.Query(ctx, getCustomerDistributionByArea, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCustomerDistributionByAreaRow{}
	for rows.Next() {
		var i GetCustomerDistributionByAreaRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Count,
			&i.Percentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerDistributionByConnectionMethod = `-- name: GetCustomerDistributionByConnectionMethod :many
SELECT
    c.connection_method AS name,
    COUNT(*)::int AS count,
    CASE
        WHEN SUM(COUNT(*)) OVER () = 0 THEN 0
        ELSE ROUND(COUNT(*)::numeric / SUM(COUNT(*)) OVER ()::numeric * 100, 2)
    END::float8 AS percentage
FROM customers c
WHERE c.tenant_id = $1
  AND c.status = 'aktif'
  AND c.deleted_at IS NULL
GROUP BY c.connection_method
ORDER BY count DESC
`

type GetCustomerDistributionByConnectionMethodRow struct {
	Name       string  `json:"name"`
	Count      int32   `json:"count"`
	Percentage float64 `json:"percentage"`
}

// Menghitung distribusi pelanggan aktif per metode koneksi.
// Metode: pppoe, hotspot, dhcp_binding, static.
func (q *Queries) GetCustomerDistributionByConnectionMethod(ctx context.Context, tenantID pgtype.UUID) ([]GetCustomerDistributionByConnectionMethodRow, error) {
	rows, err := q.db.Query(ctx, getCustomerDistributionByConnectionMethod, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCustomerDistributionByConnectionMethodRow{}
	for rows.Next() {
		var i GetCustomerDistributionByConnectionMethodRow
		if err := rows.Scan(&i.Name, &i.Count, &i.Percentage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerDistributionByPackage = `-- name: GetCustomerDistributionByPackage :many
SELECT
    p.id::text AS id,
    p.name AS name,
    COUNT(c.id)::int AS count,
    CASE
        WHEN SUM(COUNT(c.id)) OVER () = 0 THEN 0
        ELSE ROUND(COUNT(c.id)::numeric / SUM(COUNT(c.id)) OVER ()::numeric * 100, 2)
    END::float8 AS percentage
FROM packages p
LEFT JOIN customers c ON c.package_id = p.id
    AND c.status = 'aktif'
    AND c.deleted_at IS NULL
WHERE p.tenant_id = $1
GROUP BY p.id, p.name
ORDER BY count DESC
`

type GetCustomerDistributionByPackageRow struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Count      int32   `json:"count"`
	Percentage float64 `json:"percentage"`
}

// Menghitung distribusi pelanggan aktif per paket.
// Mengembalikan package_id, package_name, customer_count, dan percentage.
func (q *Queries) GetCustomerDistributionByPackage(ctx context.Context, tenantID pgtype.UUID) ([]GetCustomerDistributionByPackageRow, error) {
	rows, err := q.db.Query(ctx, getCustomerDistributionByPackage, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCustomerDistributionByPackageRow{}
	for rows.Next() {
		var i GetCustomerDistributionByPackageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Count,
			&i.Percentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerDistributionByStatus = `-- name: GetCustomerDistributionByStatus :many
SELECT
    c.status AS name,
    COUNT(*)::int AS count,
    CASE
        WHEN SUM(COUNT(*)) OVER () = 0 THEN 0
        ELSE ROUND(COUNT(*)::numeric / SUM(COUNT(*)) OVER ()::numeric * 100, 2)
    END::float8 AS percentage
FROM customers c
WHERE c.tenant_id = $1
  AND c.deleted_at IS NULL
GROUP BY c.status
ORDER BY count DESC
`

type GetCustomerDistributionByStatusRow struct {
	Name       string  `json:"name"`
	Count      int32   `json:"count"`
	Percentage float64 `json:"percentage"`
}

// Menghitung distribusi pelanggan per status.
// Mengembalikan status name dan customer_count.
func (q *Queries) GetCustomerDistributionByStatus(ctx context.Context, tenantID pgtype.UUID) ([]GetCustomerDistributionByStatusRow, error) {
	rows, err := q.db.Query(ctx, getCustomerDistributionByStatus, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCustomerDistributionByStatusRow{}
	for rows.Next() {
		var i GetCustomerDistributionByStatusRow
		if err := rows.Scan(&i.Name, &i.Count, &i.Percentage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerGrowthData = `-- name: GetCustomerGrowthData :one

SELECT
    COALESCE(COUNT(*) FILTER (WHERE c.status = 'aktif' AND c.deleted_at IS NULL), 0)::int AS total_active,
    COALESCE(COUNT(*) FILTER (
        WHERE c.activation_date >= $2::date
          AND c.activation_date < $3::date
          AND c.deleted_at IS NULL
    ), 0)::int AS new_customers,
    COALESCE(COUNT(*) FILTER (
        WHERE c.status = 'berhenti'
          AND c.updated_at >= $2::timestamptz
          AND c.updated_at < $3::timestamptz
    ), 0)::int AS churned_customers,
    (
        COALESCE(COUNT(*) FILTER (
            WHERE c.activation_date >= $2::date
              AND c.activation_date < $3::date
              AND c.deleted_at IS NULL
        ), 0) -
        COALESCE(COUNT(*) FILTER (
            WHERE c.status = 'berhenti'
              AND c.updated_at >= $2::timestamptz
              AND c.updated_at < $3::timestamptz
        ), 0)
    )::int AS net_growth
FROM customers c
WHERE c.tenant_id = $1
`

type GetCustomerGrowthDataParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

type GetCustomerGrowthDataRow struct {
	TotalActive      int32 `json:"total_active"`
	NewCustomers     int32 `json:"new_customers"`
	ChurnedCustomers int32 `json:"churned_customers"`
	NetGrowth        int32 `json:"net_growth"`
}

// Query SQL untuk aggregasi laporan pelanggan (customer reports).
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Mencakup: pertumbuhan pelanggan, distribusi, churn analysis, ARPU, CLV.
// Tabel dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Menghitung data pertumbuhan pelanggan untuk periode tertentu.
// total_active: pelanggan aktif saat ini (status = 'aktif').
// new_customers: pelanggan baru dalam periode (activation_date dalam range).
// churned_customers: pelanggan berhenti dalam periode (status = 'berhenti', updated_at dalam range).
// net_growth: new_customers - churned_customers.
func (q *Queries) GetCustomerGrowthData(ctx context.Context, arg GetCustomerGrowthDataParams) (GetCustomerGrowthDataRow, error) {
	row := q.db.QueryRow(ctx, getCustomerGrowthData, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	var i GetCustomerGrowthDataRow
	err := row.Scan(
		&i.TotalActive,
		&i.NewCustomers,
		&i.ChurnedCustomers,
		&i.NetGrowth,
	)
	return i, err
}

const getMonthlyGrowthTrend = `-- name: GetMonthlyGrowthTrend :many
SELECT
    TO_CHAR(month_series, 'YYYY-MM') AS month,
    COALESCE((
        SELECT COUNT(*)
        FROM customers c2
        WHERE c2.tenant_id = $1
          AND c2.status = 'aktif'
          AND c2.deleted_at IS NULL
          AND c2.activation_date <= (month_series + INTERVAL '1 month' - INTERVAL '1 day')::date
    ), 0)::int AS total_active,
    COALESCE((
        SELECT COUNT(*)
        FROM customers c3
        WHERE c3.tenant_id = $1
          AND c3.deleted_at IS NULL
          AND c3.activation_date >= month_series::date
          AND c3.activation_date < (month_series + INTERVAL '1 month')::date
    ), 0)::int AS new_customers,
    COALESCE((
        SELECT COUNT(*)
        FROM customers c4
        WHERE c4.tenant_id = $1
          AND c4.status = 'berhenti'
          AND c4.updated_at >= month_series
          AND c4.updated_at < (month_series + INTERVAL '1 month')
    ), 0)::int AS churned_customers
FROM generate_series(
    DATE_TRUNC('month', CURRENT_DATE - INTERVAL '11 months'),
    DATE_TRUNC('month', CURRENT_DATE),
    '1 month'::interval
) AS month_series
ORDER BY month_series ASC
`

type GetMonthlyGrowthTrendRow struct {
	Month            string `json:"month"`
	TotalActive      int32  `json:"total_active"`
	NewCustomers     int32  `json:"new_customers"`
	ChurnedCustomers int32  `json:"churned_customers"`
}

// Menghitung trend pertumbuhan pelanggan per bulan untuk 12 bulan terakhir.
// Mengembalikan total_active, new_customers, dan churned_customers per bulan.
func (q *Queries) GetMonthlyGrowthTrend(ctx context.Context, tenantID pgtype.UUID) ([]GetMonthlyGrowthTrendRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyGrowthTrend, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyGrowthTrendRow{}
	for rows.Next() {
		var i GetMonthlyGrowthTrendRow
		if err := rows.Scan(
			&i.Month,
			&i.TotalActive,
			&i.NewCustomers,
			&i.ChurnedCustomers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
