// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: resellers.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReseller = `-- name: CreateReseller :one

INSERT INTO resellers (
    tenant_id, name, phone, email, address,
    password_hash, balance, daily_purchase_limit, status
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
RETURNING id, tenant_id, name, phone, email, address, password_hash, balance, daily_purchase_limit, status, last_login, created_at, updated_at
`

type CreateResellerParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	Name               string      `json:"name"`
	Phone              string      `json:"phone"`
	Email              pgtype.Text `json:"email"`
	Address            pgtype.Text `json:"address"`
	PasswordHash       string      `json:"password_hash"`
	Balance            int64       `json:"balance"`
	DailyPurchaseLimit int32       `json:"daily_purchase_limit"`
	Status             string      `json:"status"`
}

// Kueri SQL untuk operasi CRUD tabel resellers.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel resellers dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Membuat reseller baru dan mengembalikan semua kolom.
func (q *Queries) CreateReseller(ctx context.Context, arg CreateResellerParams) (Reseller, error) {
	row := q.db.QueryRow(ctx, createReseller,
		arg.TenantID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.PasswordHash,
		arg.Balance,
		arg.DailyPurchaseLimit,
		arg.Status,
	)
	var i Reseller
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.PasswordHash,
		&i.Balance,
		&i.DailyPurchaseLimit,
		&i.Status,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResellerByID = `-- name: GetResellerByID :one
SELECT r.id, r.tenant_id, r.name, r.phone, r.email, r.address, r.password_hash, r.balance, r.daily_purchase_limit, r.status, r.last_login, r.created_at, r.updated_at,
    (SELECT COUNT(*) FROM vouchers v
     WHERE v.reseller_id = r.id
       AND v.status NOT IN ('tersedia', 'void')) AS total_vouchers_sold
FROM resellers r
WHERE r.id = $1
`

type GetResellerByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	Name               string             `json:"name"`
	Phone              string             `json:"phone"`
	Email              pgtype.Text        `json:"email"`
	Address            pgtype.Text        `json:"address"`
	PasswordHash       string             `json:"password_hash"`
	Balance            int64              `json:"balance"`
	DailyPurchaseLimit int32              `json:"daily_purchase_limit"`
	Status             string             `json:"status"`
	LastLogin          pgtype.Timestamptz `json:"last_login"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	TotalVouchersSold  int64              `json:"total_vouchers_sold"`
}

// Mengambil reseller berdasarkan ID beserta jumlah voucher terjual (computed field).
// total_vouchers_sold menghitung voucher yang statusnya bukan 'tersedia' dan bukan 'void'.
func (q *Queries) GetResellerByID(ctx context.Context, id pgtype.UUID) (GetResellerByIDRow, error) {
	row := q.db.QueryRow(ctx, getResellerByID, id)
	var i GetResellerByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.PasswordHash,
		&i.Balance,
		&i.DailyPurchaseLimit,
		&i.Status,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalVouchersSold,
	)
	return i, err
}

const getResellerByPhone = `-- name: GetResellerByPhone :one
SELECT id, tenant_id, name, phone, email, address, password_hash, balance, daily_purchase_limit, status, last_login, created_at, updated_at
FROM resellers
WHERE tenant_id = $1 AND phone = $2
`

type GetResellerByPhoneParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Phone    string      `json:"phone"`
}

// Mengambil reseller berdasarkan tenant_id dan phone (untuk login).
func (q *Queries) GetResellerByPhone(ctx context.Context, arg GetResellerByPhoneParams) (Reseller, error) {
	row := q.db.QueryRow(ctx, getResellerByPhone, arg.TenantID, arg.Phone)
	var i Reseller
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.PasswordHash,
		&i.Balance,
		&i.DailyPurchaseLimit,
		&i.Status,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResellerByPhoneGlobal = `-- name: GetResellerByPhoneGlobal :one
SELECT id, tenant_id, name, phone, email, address, password_hash, balance, daily_purchase_limit, status, last_login, created_at, updated_at FROM resellers WHERE phone = $1
`

// Mengambil reseller berdasarkan phone saja (lintas tenant, untuk login).
func (q *Queries) GetResellerByPhoneGlobal(ctx context.Context, phone string) (Reseller, error) {
	row := q.db.QueryRow(ctx, getResellerByPhoneGlobal, phone)
	var i Reseller
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.PasswordHash,
		&i.Balance,
		&i.DailyPurchaseLimit,
		&i.Status,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResellerForUpdate = `-- name: GetResellerForUpdate :one
SELECT id, tenant_id, name, phone, email, address, password_hash, balance, daily_purchase_limit, status, last_login, created_at, updated_at
FROM resellers
WHERE id = $1
FOR UPDATE
`

// Mengambil reseller dengan row lock (SELECT ... FOR UPDATE).
// Digunakan dalam transaksi untuk operasi balance atomik.
func (q *Queries) GetResellerForUpdate(ctx context.Context, id pgtype.UUID) (Reseller, error) {
	row := q.db.QueryRow(ctx, getResellerForUpdate, id)
	var i Reseller
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.PasswordHash,
		&i.Balance,
		&i.DailyPurchaseLimit,
		&i.Status,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resellerPhoneExists = `-- name: ResellerPhoneExists :one
SELECT EXISTS(
    SELECT 1 FROM resellers
    WHERE tenant_id = $1 AND phone = $2 AND id != $3
) AS exists
`

type ResellerPhoneExistsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Phone    string      `json:"phone"`
	ID       pgtype.UUID `json:"id"`
}

// Mengecek apakah nomor telepon sudah ada di tenant (exclude ID tertentu).
func (q *Queries) ResellerPhoneExists(ctx context.Context, arg ResellerPhoneExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, resellerPhoneExists, arg.TenantID, arg.Phone, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateReseller = `-- name: UpdateReseller :one
UPDATE resellers SET
    name = $2,
    phone = $3,
    email = $4,
    address = $5,
    daily_purchase_limit = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, name, phone, email, address, password_hash, balance, daily_purchase_limit, status, last_login, created_at, updated_at
`

type UpdateResellerParams struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	Phone              string      `json:"phone"`
	Email              pgtype.Text `json:"email"`
	Address            pgtype.Text `json:"address"`
	DailyPurchaseLimit int32       `json:"daily_purchase_limit"`
}

// Memperbarui data reseller (name, phone, email, address, daily_purchase_limit).
func (q *Queries) UpdateReseller(ctx context.Context, arg UpdateResellerParams) (Reseller, error) {
	row := q.db.QueryRow(ctx, updateReseller,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.DailyPurchaseLimit,
	)
	var i Reseller
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.PasswordHash,
		&i.Balance,
		&i.DailyPurchaseLimit,
		&i.Status,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateResellerBalance = `-- name: UpdateResellerBalance :exec
UPDATE resellers SET
    balance = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateResellerBalanceParams struct {
	ID      pgtype.UUID `json:"id"`
	Balance int64       `json:"balance"`
}

// Memperbarui saldo reseller (digunakan dalam transaksi atomik).
func (q *Queries) UpdateResellerBalance(ctx context.Context, arg UpdateResellerBalanceParams) error {
	_, err := q.db.Exec(ctx, updateResellerBalance, arg.ID, arg.Balance)
	return err
}

const updateResellerLastLogin = `-- name: UpdateResellerLastLogin :exec
UPDATE resellers SET
    last_login = NOW()
WHERE id = $1
`

// Memperbarui timestamp last_login reseller ke waktu sekarang.
func (q *Queries) UpdateResellerLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateResellerLastLogin, id)
	return err
}

const updateResellerPasswordHash = `-- name: UpdateResellerPasswordHash :exec
UPDATE resellers SET
    password_hash = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateResellerPasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

// Memperbarui password hash reseller (untuk reset password).
func (q *Queries) UpdateResellerPasswordHash(ctx context.Context, arg UpdateResellerPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateResellerPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateResellerStatus = `-- name: UpdateResellerStatus :one
UPDATE resellers SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, name, phone, email, address, password_hash, balance, daily_purchase_limit, status, last_login, created_at, updated_at
`

type UpdateResellerStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Memperbarui status reseller (aktif/suspended/nonaktif).
func (q *Queries) UpdateResellerStatus(ctx context.Context, arg UpdateResellerStatusParams) (Reseller, error) {
	row := q.db.QueryRow(ctx, updateResellerStatus, arg.ID, arg.Status)
	var i Reseller
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.PasswordHash,
		&i.Balance,
		&i.DailyPurchaseLimit,
		&i.Status,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
