// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: reseller_transactions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countResellerDeposits = `-- name: CountResellerDeposits :one
SELECT COUNT(*)
FROM reseller_transactions
WHERE tenant_id = $1 AND reseller_id = $2 AND type = 'deposit'
`

type CountResellerDepositsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ResellerID pgtype.UUID `json:"reseller_id"`
}

// Menghitung total transaksi deposit reseller (untuk paginasi metadata).
func (q *Queries) CountResellerDeposits(ctx context.Context, arg CountResellerDepositsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResellerDeposits, arg.TenantID, arg.ResellerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResellerTransactions = `-- name: CountResellerTransactions :one
SELECT COUNT(*)
FROM reseller_transactions
WHERE tenant_id = $1 AND reseller_id = $2
`

type CountResellerTransactionsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ResellerID pgtype.UUID `json:"reseller_id"`
}

// Menghitung total transaksi reseller (untuk paginasi metadata).
func (q *Queries) CountResellerTransactions(ctx context.Context, arg CountResellerTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResellerTransactions, arg.TenantID, arg.ResellerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResellerTransaction = `-- name: CreateResellerTransaction :one

INSERT INTO reseller_transactions (
    tenant_id, reseller_id, type, amount, balance_before, balance_after, reference_id, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, tenant_id, reseller_id, type, amount, balance_before, balance_after, reference_id, notes, created_at
`

type CreateResellerTransactionParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	ResellerID    pgtype.UUID `json:"reseller_id"`
	Type          string      `json:"type"`
	Amount        int64       `json:"amount"`
	BalanceBefore int64       `json:"balance_before"`
	BalanceAfter  int64       `json:"balance_after"`
	ReferenceID   pgtype.UUID `json:"reference_id"`
	Notes         pgtype.Text `json:"notes"`
}

// Kueri SQL untuk operasi tabel reseller_transactions.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel reseller_transactions mencatat semua transaksi keuangan reseller (deposit, purchase, refund, withdraw).
// Tabel dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Membuat catatan transaksi reseller baru dan mengembalikan semua kolom.
func (q *Queries) CreateResellerTransaction(ctx context.Context, arg CreateResellerTransactionParams) (ResellerTransaction, error) {
	row := q.db.QueryRow(ctx, createResellerTransaction,
		arg.TenantID,
		arg.ResellerID,
		arg.Type,
		arg.Amount,
		arg.BalanceBefore,
		arg.BalanceAfter,
		arg.ReferenceID,
		arg.Notes,
	)
	var i ResellerTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ResellerID,
		&i.Type,
		&i.Amount,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.ReferenceID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listResellerDeposits = `-- name: ListResellerDeposits :many
SELECT id, tenant_id, reseller_id, type, amount, balance_before, balance_after, reference_id, notes, created_at
FROM reseller_transactions
WHERE tenant_id = $1 AND reseller_id = $2 AND type = 'deposit'
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListResellerDepositsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ResellerID pgtype.UUID `json:"reseller_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

// Mengambil daftar transaksi deposit reseller dengan paginasi, diurutkan berdasarkan waktu terbaru.
func (q *Queries) ListResellerDeposits(ctx context.Context, arg ListResellerDepositsParams) ([]ResellerTransaction, error) {
	rows, err := q.db.Query(ctx, listResellerDeposits,
		arg.TenantID,
		arg.ResellerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResellerTransaction{}
	for rows.Next() {
		var i ResellerTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ResellerID,
			&i.Type,
			&i.Amount,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.ReferenceID,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResellerTransactions = `-- name: ListResellerTransactions :many
SELECT id, tenant_id, reseller_id, type, amount, balance_before, balance_after, reference_id, notes, created_at
FROM reseller_transactions
WHERE tenant_id = $1 AND reseller_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListResellerTransactionsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ResellerID pgtype.UUID `json:"reseller_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

// Mengambil daftar transaksi reseller dengan paginasi, diurutkan berdasarkan waktu terbaru.
func (q *Queries) ListResellerTransactions(ctx context.Context, arg ListResellerTransactionsParams) ([]ResellerTransaction, error) {
	rows, err := q.db.Query(ctx, listResellerTransactions,
		arg.TenantID,
		arg.ResellerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResellerTransaction{}
	for rows.Next() {
		var i ResellerTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ResellerID,
			&i.Type,
			&i.Amount,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.ReferenceID,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
