// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (tenant_id, name, email, phone, password_hash, role, email_verified, google_id, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, name, email, phone, password_hash, role, email_verified, google_id, status, last_login, created_at, updated_at
`

type CreateUserParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	Name          string      `json:"name"`
	Email         string      `json:"email"`
	Phone         pgtype.Text `json:"phone"`
	PasswordHash  pgtype.Text `json:"password_hash"`
	Role          string      `json:"role"`
	EmailVerified bool        `json:"email_verified"`
	GoogleID      pgtype.Text `json:"google_id"`
	Status        string      `json:"status"`
}

// Kueri SQL untuk operasi CRUD tabel users.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel users dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Role,
		arg.EmailVerified,
		arg.GoogleID,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.GoogleID,
		&i.Status,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const emailExistsGlobal = `-- name: EmailExistsGlobal :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1) AS exists
`

func (q *Queries) EmailExistsGlobal(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExistsGlobal, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, name, email, phone, password_hash, role, email_verified, google_id, status, last_login, created_at, updated_at
FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.GoogleID,
		&i.Status,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, tenant_id, name, email, phone, password_hash, role, email_verified, google_id, status, last_login, created_at, updated_at
FROM users WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.GoogleID,
		&i.Status,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, name, email, phone, password_hash, role, email_verified, google_id, status, last_login, created_at, updated_at
FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.GoogleID,
		&i.Status,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByTenantAndEmail = `-- name: GetUserByTenantAndEmail :one
SELECT id, tenant_id, name, email, phone, password_hash, role, email_verified, google_id, status, last_login, created_at, updated_at
FROM users WHERE tenant_id = $1 AND email = $2
`

type GetUserByTenantAndEmailParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

func (q *Queries) GetUserByTenantAndEmail(ctx context.Context, arg GetUserByTenantAndEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTenantAndEmail, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.GoogleID,
		&i.Status,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkGoogleID = `-- name: LinkGoogleID :exec
UPDATE users SET google_id = $2, updated_at = NOW() WHERE id = $1
`

type LinkGoogleIDParams struct {
	ID       pgtype.UUID `json:"id"`
	GoogleID pgtype.Text `json:"google_id"`
}

func (q *Queries) LinkGoogleID(ctx context.Context, arg LinkGoogleIDParams) error {
	_, err := q.db.Exec(ctx, linkGoogleID, arg.ID, arg.GoogleID)
	return err
}

const listUsersByTenant = `-- name: ListUsersByTenant :many
SELECT id, tenant_id, name, email, phone, password_hash, role, email_verified, google_id, status, last_login, created_at, updated_at
FROM users WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUsersByTenant(ctx context.Context, tenantID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.Role,
			&i.EmailVerified,
			&i.GoogleID,
			&i.Status,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified = true, updated_at = NOW() WHERE id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET name = $2, phone = $3, role = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, name, email, phone, password_hash, role, email_verified, google_id, status, last_login, created_at, updated_at
`

type UpdateUserParams struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Phone pgtype.Text `json:"phone"`
	Role  string      `json:"role"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.GoogleID,
		&i.Status,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}
