// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: vouchers.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminAssignVoucher = `-- name: AdminAssignVoucher :one
UPDATE vouchers SET
    reseller_id = $2,
    status = 'terjual',
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, code, package_id, reseller_id, status, sell_price_snapshot, reseller_price_snapshot, purchased_at, activated_at, expires_at, voided_at, created_at, updated_at
`

type AdminAssignVoucherParams struct {
	ID         pgtype.UUID `json:"id"`
	ResellerID pgtype.UUID `json:"reseller_id"`
}

// Meng-assign voucher ke reseller oleh admin (tanpa snapshot harga).
func (q *Queries) AdminAssignVoucher(ctx context.Context, arg AdminAssignVoucherParams) (Voucher, error) {
	row := q.db.QueryRow(ctx, adminAssignVoucher, arg.ID, arg.ResellerID)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.PackageID,
		&i.ResellerID,
		&i.Status,
		&i.SellPriceSnapshot,
		&i.ResellerPriceSnapshot,
		&i.PurchasedAt,
		&i.ActivatedAt,
		&i.ExpiresAt,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const assignVoucherToReseller = `-- name: AssignVoucherToReseller :one
UPDATE vouchers SET
    reseller_id = $2,
    status = 'terjual',
    sell_price_snapshot = $3,
    reseller_price_snapshot = $4,
    purchased_at = $5,
    expires_at = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, code, package_id, reseller_id, status, sell_price_snapshot, reseller_price_snapshot, purchased_at, activated_at, expires_at, voided_at, created_at, updated_at
`

type AssignVoucherToResellerParams struct {
	ID                    pgtype.UUID        `json:"id"`
	ResellerID            pgtype.UUID        `json:"reseller_id"`
	SellPriceSnapshot     pgtype.Int8        `json:"sell_price_snapshot"`
	ResellerPriceSnapshot pgtype.Int8        `json:"reseller_price_snapshot"`
	PurchasedAt           pgtype.Timestamptz `json:"purchased_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
}

// Meng-assign voucher ke reseller saat pembelian (atur snapshot, purchased_at, expires_at).
func (q *Queries) AssignVoucherToReseller(ctx context.Context, arg AssignVoucherToResellerParams) (Voucher, error) {
	row := q.db.QueryRow(ctx, assignVoucherToReseller,
		arg.ID,
		arg.ResellerID,
		arg.SellPriceSnapshot,
		arg.ResellerPriceSnapshot,
		arg.PurchasedAt,
		arg.ExpiresAt,
	)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.PackageID,
		&i.ResellerID,
		&i.Status,
		&i.SellPriceSnapshot,
		&i.ResellerPriceSnapshot,
		&i.PurchasedAt,
		&i.ActivatedAt,
		&i.ExpiresAt,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type BulkCreateVouchersParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	Code      string      `json:"code"`
	PackageID pgtype.UUID `json:"package_id"`
	Status    string      `json:"status"`
}

const countVouchersByResellerAndStatus = `-- name: CountVouchersByResellerAndStatus :one
SELECT COUNT(*)
FROM vouchers
WHERE reseller_id = $1 AND status = ANY($2::varchar[])
`

type CountVouchersByResellerAndStatusParams struct {
	ResellerID pgtype.UUID `json:"reseller_id"`
	Status     []string    `json:"status"`
}

// Menghitung jumlah voucher per reseller dan array status.
func (q *Queries) CountVouchersByResellerAndStatus(ctx context.Context, arg CountVouchersByResellerAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVouchersByResellerAndStatus, arg.ResellerID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVouchersSoldToday = `-- name: CountVouchersSoldToday :one
SELECT COUNT(*)
FROM vouchers
WHERE reseller_id = $1
  AND purchased_at >= CURRENT_DATE
  AND purchased_at < CURRENT_DATE + INTERVAL '1 day'
`

// Menghitung jumlah voucher yang dibeli reseller hari ini (berdasarkan purchased_at).
func (q *Queries) CountVouchersSoldToday(ctx context.Context, resellerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVouchersSoldToday, resellerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getExpiredVouchers = `-- name: GetExpiredVouchers :many
SELECT id, tenant_id, code, package_id, reseller_id, status, sell_price_snapshot, reseller_price_snapshot, purchased_at, activated_at, expires_at, voided_at, created_at, updated_at
FROM vouchers
WHERE status = 'terjual' AND expires_at < NOW()
LIMIT $1
`

// Mengambil voucher terjual yang sudah melewati expires_at (untuk cron expiry).
func (q *Queries) GetExpiredVouchers(ctx context.Context, limit int32) ([]Voucher, error) {
	rows, err := q.db.Query(ctx, getExpiredVouchers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Voucher{}
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.PackageID,
			&i.ResellerID,
			&i.Status,
			&i.SellPriceSnapshot,
			&i.ResellerPriceSnapshot,
			&i.PurchasedAt,
			&i.ActivatedAt,
			&i.ExpiresAt,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoucherByCode = `-- name: GetVoucherByCode :one
SELECT id, tenant_id, code, package_id, reseller_id, status, sell_price_snapshot, reseller_price_snapshot, purchased_at, activated_at, expires_at, voided_at, created_at, updated_at
FROM vouchers
WHERE tenant_id = $1 AND code = $2
`

type GetVoucherByCodeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
}

// Mengambil voucher berdasarkan tenant_id dan code (untuk aktivasi/lookup).
func (q *Queries) GetVoucherByCode(ctx context.Context, arg GetVoucherByCodeParams) (Voucher, error) {
	row := q.db.QueryRow(ctx, getVoucherByCode, arg.TenantID, arg.Code)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.PackageID,
		&i.ResellerID,
		&i.Status,
		&i.SellPriceSnapshot,
		&i.ResellerPriceSnapshot,
		&i.PurchasedAt,
		&i.ActivatedAt,
		&i.ExpiresAt,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoucherByID = `-- name: GetVoucherByID :one
SELECT v.id, v.tenant_id, v.code, v.package_id, v.reseller_id, v.status, v.sell_price_snapshot, v.reseller_price_snapshot, v.purchased_at, v.activated_at, v.expires_at, v.voided_at, v.created_at, v.updated_at,
    p.name AS package_name,
    r.name AS reseller_name
FROM vouchers v
JOIN packages p ON p.id = v.package_id
LEFT JOIN resellers r ON r.id = v.reseller_id
WHERE v.id = $1
`

type GetVoucherByIDRow struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	Code                  string             `json:"code"`
	PackageID             pgtype.UUID        `json:"package_id"`
	ResellerID            pgtype.UUID        `json:"reseller_id"`
	Status                string             `json:"status"`
	SellPriceSnapshot     pgtype.Int8        `json:"sell_price_snapshot"`
	ResellerPriceSnapshot pgtype.Int8        `json:"reseller_price_snapshot"`
	PurchasedAt           pgtype.Timestamptz `json:"purchased_at"`
	ActivatedAt           pgtype.Timestamptz `json:"activated_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	VoidedAt              pgtype.Timestamptz `json:"voided_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	PackageName           string             `json:"package_name"`
	ResellerName          pgtype.Text        `json:"reseller_name"`
}

// Mengambil voucher berdasarkan ID beserta nama paket dan nama reseller (joined).
// LEFT JOIN pada resellers karena reseller_id bisa NULL (voucher belum terjual).
func (q *Queries) GetVoucherByID(ctx context.Context, id pgtype.UUID) (GetVoucherByIDRow, error) {
	row := q.db.QueryRow(ctx, getVoucherByID, id)
	var i GetVoucherByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.PackageID,
		&i.ResellerID,
		&i.Status,
		&i.SellPriceSnapshot,
		&i.ResellerPriceSnapshot,
		&i.PurchasedAt,
		&i.ActivatedAt,
		&i.ExpiresAt,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PackageName,
		&i.ResellerName,
	)
	return i, err
}

const getVouchersByIDs = `-- name: GetVouchersByIDs :many
SELECT id, tenant_id, code, package_id, reseller_id, status, sell_price_snapshot, reseller_price_snapshot, purchased_at, activated_at, expires_at, voided_at, created_at, updated_at
FROM vouchers
WHERE id = ANY($1::uuid[])
`

// Mengambil beberapa voucher berdasarkan array of IDs.
func (q *Queries) GetVouchersByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Voucher, error) {
	rows, err := q.db.Query(ctx, getVouchersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Voucher{}
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.PackageID,
			&i.ResellerID,
			&i.Status,
			&i.SellPriceSnapshot,
			&i.ResellerPriceSnapshot,
			&i.PurchasedAt,
			&i.ActivatedAt,
			&i.ExpiresAt,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVoucherExpired = `-- name: UpdateVoucherExpired :one
UPDATE vouchers SET
    status = 'expired',
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, code, package_id, reseller_id, status, sell_price_snapshot, reseller_price_snapshot, purchased_at, activated_at, expires_at, voided_at, created_at, updated_at
`

// Memperbarui voucher menjadi expired: atur status dan updated_at.
func (q *Queries) UpdateVoucherExpired(ctx context.Context, id pgtype.UUID) (Voucher, error) {
	row := q.db.QueryRow(ctx, updateVoucherExpired, id)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.PackageID,
		&i.ResellerID,
		&i.Status,
		&i.SellPriceSnapshot,
		&i.ResellerPriceSnapshot,
		&i.PurchasedAt,
		&i.ActivatedAt,
		&i.ExpiresAt,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVoucherStatus = `-- name: UpdateVoucherStatus :one
UPDATE vouchers SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, code, package_id, reseller_id, status, sell_price_snapshot, reseller_price_snapshot, purchased_at, activated_at, expires_at, voided_at, created_at, updated_at
`

type UpdateVoucherStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Memperbarui status voucher dan updated_at.
func (q *Queries) UpdateVoucherStatus(ctx context.Context, arg UpdateVoucherStatusParams) (Voucher, error) {
	row := q.db.QueryRow(ctx, updateVoucherStatus, arg.ID, arg.Status)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.PackageID,
		&i.ResellerID,
		&i.Status,
		&i.SellPriceSnapshot,
		&i.ResellerPriceSnapshot,
		&i.PurchasedAt,
		&i.ActivatedAt,
		&i.ExpiresAt,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVoucherVoid = `-- name: UpdateVoucherVoid :one
UPDATE vouchers SET
    status = 'void',
    voided_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, code, package_id, reseller_id, status, sell_price_snapshot, reseller_price_snapshot, purchased_at, activated_at, expires_at, voided_at, created_at, updated_at
`

// Memperbarui voucher menjadi void: atur status, voided_at, dan updated_at.
func (q *Queries) UpdateVoucherVoid(ctx context.Context, id pgtype.UUID) (Voucher, error) {
	row := q.db.QueryRow(ctx, updateVoucherVoid, id)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.PackageID,
		&i.ResellerID,
		&i.Status,
		&i.SellPriceSnapshot,
		&i.ResellerPriceSnapshot,
		&i.PurchasedAt,
		&i.ActivatedAt,
		&i.ExpiresAt,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const voucherCodeExists = `-- name: VoucherCodeExists :one
SELECT EXISTS(
    SELECT 1 FROM vouchers
    WHERE tenant_id = $1 AND code = $2
) AS exists
`

type VoucherCodeExistsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
}

// Mengecek apakah kode voucher sudah ada di tenant (untuk collision cek).
func (q *Queries) VoucherCodeExists(ctx context.Context, arg VoucherCodeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, voucherCodeExists, arg.TenantID, arg.Code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
