// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: voucher_audit_logs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVoucherAuditLog = `-- name: CreateVoucherAuditLog :one

INSERT INTO voucher_audit_logs (
    tenant_id, voucher_id, action, actor_id, actor_name, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, tenant_id, voucher_id, action, actor_id, actor_name, metadata, created_at
`

type CreateVoucherAuditLogParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	VoucherID pgtype.UUID `json:"voucher_id"`
	Action    string      `json:"action"`
	ActorID   string      `json:"actor_id"`
	ActorName string      `json:"actor_name"`
	Metadata  []byte      `json:"metadata"`
}

// Kueri SQL untuk operasi tabel voucher_audit_logs.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel voucher_audit_logs bersifat append-only - hanya INSERT dan SELECT yang diizinkan.
// Tabel dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Membuat catatan audit log voucher baru dan mengembalikan semua kolom.
func (q *Queries) CreateVoucherAuditLog(ctx context.Context, arg CreateVoucherAuditLogParams) (VoucherAuditLog, error) {
	row := q.db.QueryRow(ctx, createVoucherAuditLog,
		arg.TenantID,
		arg.VoucherID,
		arg.Action,
		arg.ActorID,
		arg.ActorName,
		arg.Metadata,
	)
	var i VoucherAuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VoucherID,
		&i.Action,
		&i.ActorID,
		&i.ActorName,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listVoucherAuditLogsByVoucher = `-- name: ListVoucherAuditLogsByVoucher :many
SELECT id, tenant_id, voucher_id, action, actor_id, actor_name, metadata, created_at
FROM voucher_audit_logs
WHERE voucher_id = $1
ORDER BY created_at ASC
`

// Mengambil semua audit log untuk voucher tertentu, diurutkan berdasarkan waktu pembuatan (ASC).
func (q *Queries) ListVoucherAuditLogsByVoucher(ctx context.Context, voucherID pgtype.UUID) ([]VoucherAuditLog, error) {
	rows, err := q.db.Query(ctx, listVoucherAuditLogsByVoucher, voucherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoucherAuditLog{}
	for rows.Next() {
		var i VoucherAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.VoucherID,
			&i.Action,
			&i.ActorID,
			&i.ActorName,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
