// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: webhook_logs.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookLog = `-- name: CreateWebhookLog :one

INSERT INTO webhook_logs (
    tenant_id, gateway_provider, event_type,
    external_id, request_body, source_ip,
    signature_valid, processing_status, error_message
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
RETURNING id, tenant_id, gateway_provider, event_type, external_id, request_body, source_ip, signature_valid, processing_status, error_message, created_at
`

type CreateWebhookLogParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	GatewayProvider  string      `json:"gateway_provider"`
	EventType        string      `json:"event_type"`
	ExternalID       string      `json:"external_id"`
	RequestBody      []byte      `json:"request_body"`
	SourceIp         netip.Addr  `json:"source_ip"`
	SignatureValid   pgtype.Bool `json:"signature_valid"`
	ProcessingStatus string      `json:"processing_status"`
	ErrorMessage     pgtype.Text `json:"error_message"`
}

// Kueri SQL untuk operasi CRUD tabel webhook_logs.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel webhook_logs TIDAK menggunakan RLS karena webhook diterima sebelum identifikasi tenant.
// Bersifat append-only, menyimpan seluruh permintaan termasuk yang gagal verifikasi.
// Membuat log webhook baru dan mengembalikan semua kolom.
func (q *Queries) CreateWebhookLog(ctx context.Context, arg CreateWebhookLogParams) (WebhookLog, error) {
	row := q.db.QueryRow(ctx, createWebhookLog,
		arg.TenantID,
		arg.GatewayProvider,
		arg.EventType,
		arg.ExternalID,
		arg.RequestBody,
		arg.SourceIp,
		arg.SignatureValid,
		arg.ProcessingStatus,
		arg.ErrorMessage,
	)
	var i WebhookLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GatewayProvider,
		&i.EventType,
		&i.ExternalID,
		&i.RequestBody,
		&i.SourceIp,
		&i.SignatureValid,
		&i.ProcessingStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhookLogsOlderThan = `-- name: DeleteWebhookLogsOlderThan :execrows
DELETE FROM webhook_logs
WHERE created_at < $1
  AND processing_status != 'failed'
  AND (signature_valid IS NULL OR signature_valid = true)
`

// Menghapus webhook logs yang lebih tua dari waktu yang ditentukan.
// Tidak menghapus logs dengan status 'failed' atau signature_valid = false (log keamanan dipertahankan).
// Mengembalikan jumlah baris yang dihapus.
func (q *Queries) DeleteWebhookLogsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookLogsOlderThan, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWebhookLogByID = `-- name: GetWebhookLogByID :one
SELECT id, tenant_id, gateway_provider, event_type, external_id, request_body, source_ip, signature_valid, processing_status, error_message, created_at
FROM webhook_logs
WHERE id = $1
`

// Mengambil webhook log berdasarkan ID.
func (q *Queries) GetWebhookLogByID(ctx context.Context, id pgtype.UUID) (WebhookLog, error) {
	row := q.db.QueryRow(ctx, getWebhookLogByID, id)
	var i WebhookLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GatewayProvider,
		&i.EventType,
		&i.ExternalID,
		&i.RequestBody,
		&i.SourceIp,
		&i.SignatureValid,
		&i.ProcessingStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const isWebhookAlreadyProcessed = `-- name: IsWebhookAlreadyProcessed :one
SELECT EXISTS(
    SELECT 1 FROM webhook_logs
    WHERE external_id = $1 AND event_type = $2 AND processing_status = 'processed'
) AS exists
`

type IsWebhookAlreadyProcessedParams struct {
	ExternalID string `json:"external_id"`
	EventType  string `json:"event_type"`
}

// Mengecek apakah webhook dengan external_id dan event_type sudah berhasil diproses.
// Digunakan untuk idempotency cek sebelum memproses webhook.
func (q *Queries) IsWebhookAlreadyProcessed(ctx context.Context, arg IsWebhookAlreadyProcessedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isWebhookAlreadyProcessed, arg.ExternalID, arg.EventType)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listWebhookLogsByExternalID = `-- name: ListWebhookLogsByExternalID :many
SELECT id, tenant_id, gateway_provider, event_type, external_id, request_body, source_ip, signature_valid, processing_status, error_message, created_at
FROM webhook_logs
WHERE external_id = $1
ORDER BY created_at DESC
`

// Mengambil semua webhook logs berdasarkan external_id dengan urutan terbaru.
// Digunakan untuk melihat riwayat webhook terkait link pembayaran tertentu.
func (q *Queries) ListWebhookLogsByExternalID(ctx context.Context, externalID string) ([]WebhookLog, error) {
	rows, err := q.db.Query(ctx, listWebhookLogsByExternalID, externalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookLog{}
	for rows.Next() {
		var i WebhookLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.GatewayProvider,
			&i.EventType,
			&i.ExternalID,
			&i.RequestBody,
			&i.SourceIp,
			&i.SignatureValid,
			&i.ProcessingStatus,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookLogSignatureValid = `-- name: UpdateWebhookLogSignatureValid :exec
UPDATE webhook_logs SET
    signature_valid = $2
WHERE id = $1
`

type UpdateWebhookLogSignatureValidParams struct {
	ID             pgtype.UUID `json:"id"`
	SignatureValid pgtype.Bool `json:"signature_valid"`
}

// Memperbarui flag signature_valid pada webhook log.
func (q *Queries) UpdateWebhookLogSignatureValid(ctx context.Context, arg UpdateWebhookLogSignatureValidParams) error {
	_, err := q.db.Exec(ctx, updateWebhookLogSignatureValid, arg.ID, arg.SignatureValid)
	return err
}

const updateWebhookLogStatus = `-- name: UpdateWebhookLogStatus :exec
UPDATE webhook_logs SET
    processing_status = $2,
    error_message = $3
WHERE id = $1
`

type UpdateWebhookLogStatusParams struct {
	ID               pgtype.UUID `json:"id"`
	ProcessingStatus string      `json:"processing_status"`
	ErrorMessage     pgtype.Text `json:"error_message"`
}

// Memperbarui status pemrosesan dan pesan error pada webhook log.
func (q *Queries) UpdateWebhookLogStatus(ctx context.Context, arg UpdateWebhookLogStatusParams) error {
	_, err := q.db.Exec(ctx, updateWebhookLogStatus, arg.ID, arg.ProcessingStatus, arg.ErrorMessage)
	return err
}
