// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_data.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomerByID = `-- name: GetCustomerByID :one

SELECT id, tenant_id, customer_id_seq, name, phone, email, package_id
FROM customers
WHERE id = $1 AND deleted_at IS NULL
`

type GetCustomerByIDRow struct {
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	CustomerIDSeq pgtype.Text `json:"customer_id_seq"`
	Name          string      `json:"name"`
	Phone         string      `json:"phone"`
	Email         pgtype.Text `json:"email"`
	PackageID     pgtype.UUID `json:"package_id"`
}

// Query SQL untuk mengambil data pelanggan dan tenant dari tabel shared (milik billing-api).
// Digunakan oleh delivery pipeline untuk resolusi variabel template notifikasi.
// Tabel customers dan tenants berada di database yang sama, dibuat oleh migrasi billing-api.
// Mengambil data pelanggan berdasarkan ID untuk keperluan substitusi variabel template.
// Hanya mengambil kolom yang dibutuhkan oleh notification service.
// Pelanggan yang sudah dihapus (soft delete) tidak dikembalikan.
func (q *Queries) GetCustomerByID(ctx context.Context, id pgtype.UUID) (GetCustomerByIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i GetCustomerByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerIDSeq,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PackageID,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name
FROM tenants
WHERE id = $1
`

type GetTenantByIDRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

// Mengambil data tenant berdasarkan ID untuk keperluan substitusi variabel template.
// Hanya mengambil kolom yang dibutuhkan oleh notification service (nama ISP).
func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (GetTenantByIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i GetTenantByIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
