// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	CustomerIDSeq pgtype.Text        `json:"customer_id_seq"`
	Name          string             `json:"name"`
	Phone         string             `json:"phone"`
	Email         pgtype.Text        `json:"email"`
	PackageID     pgtype.UUID        `json:"package_id"`
	Status        string             `json:"status"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type NotificationConfig struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Channel     string             `json:"channel"`
	Provider    string             `json:"provider"`
	Credentials []byte             `json:"credentials"`
	IsEnabled   bool               `json:"is_enabled"`
	Priority    int32              `json:"priority"`
	Settings    []byte             `json:"settings"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type NotificationLog struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	TemplateID   pgtype.UUID        `json:"template_id"`
	Channel      string             `json:"channel"`
	Provider     string             `json:"provider"`
	Recipient    string             `json:"recipient"`
	Subject      pgtype.Text        `json:"subject"`
	Body         string             `json:"body"`
	Status       string             `json:"status"`
	RetryCount   int32              `json:"retry_count"`
	MaxRetries   int32              `json:"max_retries"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	DedupKey     pgtype.Text        `json:"dedup_key"`
	Metadata     []byte             `json:"metadata"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type NotificationTemplate struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Category         string             `json:"category"`
	EventType        pgtype.Text        `json:"event_type"`
	Channels         []byte             `json:"channels"`
	BodyWhatsapp     pgtype.Text        `json:"body_whatsapp"`
	BodySms          pgtype.Text        `json:"body_sms"`
	BodyEmailSubject pgtype.Text        `json:"body_email_subject"`
	BodyEmailHtml    pgtype.Text        `json:"body_email_html"`
	Variables        []byte             `json:"variables"`
	IsActive         bool               `json:"is_active"`
	IsDefault        bool               `json:"is_default"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Domain    pgtype.Text        `json:"domain"`
	Plan      string             `json:"plan"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
