// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_logs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLogs = `-- name: CountLogs :one
SELECT COUNT(*)
FROM notification_logs
WHERE tenant_id = $1
  AND ($2::varchar IS NULL OR channel = $2)
  AND ($3::varchar IS NULL OR status = $3)
  AND ($4::uuid IS NULL OR customer_id = $4)
  AND ($5::uuid IS NULL OR template_id = $5)
  AND ($6::timestamptz IS NULL OR created_at >= $6)
  AND ($7::timestamptz IS NULL OR created_at <= $7)
`

type CountLogsParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Channel    pgtype.Text        `json:"channel"`
	Status     pgtype.Text        `json:"status"`
	CustomerID pgtype.UUID        `json:"customer_id"`
	TemplateID pgtype.UUID        `json:"template_id"`
	DateFrom   pgtype.Timestamptz `json:"date_from"`
	DateTo     pgtype.Timestamptz `json:"date_to"`
}

// Menghitung jumlah total log notifikasi dengan filter yang sama seperti ListLogs.
// Digunakan untuk metadata pagination (total dan total_pages).
func (q *Queries) CountLogs(ctx context.Context, arg CountLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLogs,
		arg.TenantID,
		arg.Channel,
		arg.Status,
		arg.CustomerID,
		arg.TemplateID,
		arg.DateFrom,
		arg.DateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodayByCustomer = `-- name: CountTodayByCustomer :one
SELECT COUNT(*)
FROM notification_logs
WHERE tenant_id = $1
  AND customer_id = $2
  AND status IN ('sent', 'delivered')
  AND created_at >= (NOW() AT TIME ZONE $3)::date AT TIME ZONE $3
`

type CountTodayByCustomerParams struct {
	TenantID   pgtype.UUID     `json:"tenant_id"`
	CustomerID pgtype.UUID     `json:"customer_id"`
	Timezone   pgtype.Interval `json:"timezone"`
}

// Menghitung jumlah notifikasi yang berhasil dikirim ke pelanggan hari ini.
// Menggunakan timezone tenant untuk menentukan batas hari (awal hari lokal).
// Hanya menghitung status 'sent' dan 'delivered' sesuai requirement throttle.
func (q *Queries) CountTodayByCustomer(ctx context.Context, arg CountTodayByCustomerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTodayByCustomer, arg.TenantID, arg.CustomerID, arg.Timezone)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLog = `-- name: CreateLog :one

INSERT INTO notification_logs (
    tenant_id, customer_id, template_id, channel, provider, recipient,
    subject, body, status, retry_count, max_retries, error_message,
    dedup_key, metadata, sent_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15
)
RETURNING id, tenant_id, customer_id, template_id, channel, provider, recipient, subject, body, status, retry_count, max_retries, error_message, dedup_key, metadata, sent_at, created_at, updated_at
`

type CreateLogParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	TemplateID   pgtype.UUID        `json:"template_id"`
	Channel      string             `json:"channel"`
	Provider     string             `json:"provider"`
	Recipient    string             `json:"recipient"`
	Subject      pgtype.Text        `json:"subject"`
	Body         string             `json:"body"`
	Status       string             `json:"status"`
	RetryCount   int32              `json:"retry_count"`
	MaxRetries   int32              `json:"max_retries"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	DedupKey     pgtype.Text        `json:"dedup_key"`
	Metadata     []byte             `json:"metadata"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
}

// Query SQL untuk operasi CRUD tabel notification_logs.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel notification_logs dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Digunakan untuk audit trail, retry tracking, deduplication, throttle, dan cooldown.
// Membuat catatan log notifikasi baru dan mengembalikan log yang dibuat.
func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, createLog,
		arg.TenantID,
		arg.CustomerID,
		arg.TemplateID,
		arg.Channel,
		arg.Provider,
		arg.Recipient,
		arg.Subject,
		arg.Body,
		arg.Status,
		arg.RetryCount,
		arg.MaxRetries,
		arg.ErrorMessage,
		arg.DedupKey,
		arg.Metadata,
		arg.SentAt,
	)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.TemplateID,
		&i.Channel,
		&i.Provider,
		&i.Recipient,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.DedupKey,
		&i.Metadata,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByDedupKey = `-- name: FindByDedupKey :one
SELECT id, tenant_id, customer_id, template_id, channel, provider, recipient, subject, body, status, retry_count, max_retries, error_message, dedup_key, metadata, sent_at, created_at, updated_at
FROM notification_logs
WHERE dedup_key = $1
  AND status NOT IN ('skipped', 'failed')
  AND created_at > NOW() - ($2 || ' hours')::interval
LIMIT 1
`

type FindByDedupKeyParams struct {
	DedupKey pgtype.Text `json:"dedup_key"`
	Column2  pgtype.Text `json:"column_2"`
}

// Mencari log notifikasi berdasarkan dedup_key dalam jendela waktu tertentu.
// Digunakan untuk pengecekan duplikasi sebelum pengiriman.
// Hanya log dengan status aktif (bukan 'skipped' atau 'failed') yang dianggap duplikat.
func (q *Queries) FindByDedupKey(ctx context.Context, arg FindByDedupKeyParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, findByDedupKey, arg.DedupKey, arg.Column2)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.TemplateID,
		&i.Channel,
		&i.Provider,
		&i.Recipient,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.DedupKey,
		&i.Metadata,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLogByID = `-- name: GetLogByID :one
SELECT id, tenant_id, customer_id, template_id, channel, provider, recipient, subject, body, status, retry_count, max_retries, error_message, dedup_key, metadata, sent_at, created_at, updated_at
FROM notification_logs
WHERE id = $1
`

// Mengambil catatan log notifikasi berdasarkan ID.
func (q *Queries) GetLogByID(ctx context.Context, id pgtype.UUID) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, getLogByID, id)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.TemplateID,
		&i.Channel,
		&i.Provider,
		&i.Recipient,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.DedupKey,
		&i.Metadata,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lastSentToCustomer = `-- name: LastSentToCustomer :one
SELECT sent_at
FROM notification_logs
WHERE tenant_id = $1
  AND customer_id = $2
  AND status IN ('sent', 'delivered')
ORDER BY sent_at DESC
LIMIT 1
`

type LastSentToCustomerParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	CustomerID pgtype.UUID `json:"customer_id"`
}

// Mengambil waktu pengiriman terakhir ke pelanggan tertentu.
// Digunakan untuk pengecekan cooldown antar pesan (default 30 menit).
// Hanya mempertimbangkan notifikasi yang berhasil dikirim.
func (q *Queries) LastSentToCustomer(ctx context.Context, arg LastSentToCustomerParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, lastSentToCustomer, arg.TenantID, arg.CustomerID)
	var sent_at pgtype.Timestamptz
	err := row.Scan(&sent_at)
	return sent_at, err
}

const listLogs = `-- name: ListLogs :many
SELECT id, tenant_id, customer_id, template_id, channel, provider, recipient, subject, body, status, retry_count, max_retries, error_message, dedup_key, metadata, sent_at, created_at, updated_at
FROM notification_logs
WHERE tenant_id = $1
  AND ($4::varchar IS NULL OR channel = $4)
  AND ($5::varchar IS NULL OR status = $5)
  AND ($6::uuid IS NULL OR customer_id = $6)
  AND ($7::uuid IS NULL OR template_id = $7)
  AND ($8::timestamptz IS NULL OR created_at >= $8)
  AND ($9::timestamptz IS NULL OR created_at <= $9)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLogsParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Limit      int32              `json:"limit"`
	Offset     int32              `json:"offset"`
	Channel    pgtype.Text        `json:"channel"`
	Status     pgtype.Text        `json:"status"`
	CustomerID pgtype.UUID        `json:"customer_id"`
	TemplateID pgtype.UUID        `json:"template_id"`
	DateFrom   pgtype.Timestamptz `json:"date_from"`
	DateTo     pgtype.Timestamptz `json:"date_to"`
}

// Mengambil daftar log notifikasi dengan filter opsional dan pagination.
// Filter: tenant_id (wajib), channel, status, customer_id, template_id, date_from, date_to.
// Diurutkan berdasarkan created_at DESC (terbaru di atas).
func (q *Queries) ListLogs(ctx context.Context, arg ListLogsParams) ([]NotificationLog, error) {
	rows, err := q.db.Query(ctx, listLogs,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Channel,
		arg.Status,
		arg.CustomerID,
		arg.TemplateID,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.TemplateID,
			&i.Channel,
			&i.Provider,
			&i.Recipient,
			&i.Subject,
			&i.Body,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ErrorMessage,
			&i.DedupKey,
			&i.Metadata,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLog = `-- name: UpdateLog :exec
UPDATE notification_logs
SET
    status = $2,
    retry_count = $3,
    error_message = $4,
    sent_at = $5,
    metadata = $6,
    updated_at = NOW()
WHERE id = $1
`

type UpdateLogParams struct {
	ID           pgtype.UUID        `json:"id"`
	Status       string             `json:"status"`
	RetryCount   int32              `json:"retry_count"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	Metadata     []byte             `json:"metadata"`
}

// Memperbarui status, retry_count, error_message, sent_at, dan metadata log notifikasi.
func (q *Queries) UpdateLog(ctx context.Context, arg UpdateLogParams) error {
	_, err := q.db.Exec(ctx, updateLog,
		arg.ID,
		arg.Status,
		arg.RetryCount,
		arg.ErrorMessage,
		arg.SentAt,
		arg.Metadata,
	)
	return err
}
