// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// sumber: notification_configs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConfigByTenantAndChannel = `-- name: GetConfigByTenantAndChannel :one
SELECT id, tenant_id, channel, provider, credentials, is_enabled, priority, settings, created_at, updated_at
FROM notification_configs
WHERE tenant_id = $1 AND channel = $2
`

type GetConfigByTenantAndChannelParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Channel  string      `json:"channel"`
}

// Mengambil konfigurasi notifikasi berdasarkan tenant dan channel.
func (q *Queries) GetConfigByTenantAndChannel(ctx context.Context, arg GetConfigByTenantAndChannelParams) (NotificationConfig, error) {
	row := q.db.QueryRow(ctx, getConfigByTenantAndChannel, arg.TenantID, arg.Channel)
	var i NotificationConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Channel,
		&i.Provider,
		&i.Credentials,
		&i.IsEnabled,
		&i.Priority,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfigsByTenant = `-- name: GetConfigsByTenant :many

SELECT id, tenant_id, channel, provider, credentials, is_enabled, priority, settings, created_at, updated_at
FROM notification_configs
WHERE tenant_id = $1
ORDER BY priority ASC
`

// Kueri SQL untuk operasi CRUD tabel notification_configs.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel notification_configs dilindungi RLS, kueri hanya mengembalikan baris milik tenant aktif.
// Setiap tenant bisa memiliki satu konfigurasi per channel (UNIQUE pada tenant_id, channel).
// Mengambil semua konfigurasi notifikasi untuk tenant tertentu.
func (q *Queries) GetConfigsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]NotificationConfig, error) {
	rows, err := q.db.Query(ctx, getConfigsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationConfig{}
	for rows.Next() {
		var i NotificationConfig
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Channel,
			&i.Provider,
			&i.Credentials,
			&i.IsEnabled,
			&i.Priority,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSettingsByTenant = `-- name: GetSettingsByTenant :one
SELECT settings
FROM notification_configs
WHERE tenant_id = $1
LIMIT 1
`

// Mengambil pengaturan umum notifikasi untuk tenant tertentu.
// Mengambil settings dari baris pertama config milik tenant.
func (q *Queries) GetSettingsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSettingsByTenant, tenantID)
	var settings []byte
	err := row.Scan(&settings)
	return settings, err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE notification_configs
SET settings = $2, updated_at = NOW()
WHERE tenant_id = $1
`

type UpdateSettingsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Settings []byte      `json:"settings"`
}

// Memperbarui pengaturan umum notifikasi untuk semua config milik tenant.
func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.Exec(ctx, updateSettings, arg.TenantID, arg.Settings)
	return err
}

const upsertConfig = `-- name: UpsertConfig :one
INSERT INTO notification_configs (
    tenant_id, channel, provider, credentials, is_enabled, priority, settings
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (tenant_id, channel) DO UPDATE SET
    provider = EXCLUDED.provider,
    credentials = EXCLUDED.credentials,
    is_enabled = EXCLUDED.is_enabled,
    priority = EXCLUDED.priority,
    updated_at = NOW()
RETURNING id, tenant_id, channel, provider, credentials, is_enabled, priority, settings, created_at, updated_at
`

type UpsertConfigParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Channel     string      `json:"channel"`
	Provider    string      `json:"provider"`
	Credentials []byte      `json:"credentials"`
	IsEnabled   bool        `json:"is_enabled"`
	Priority    int32       `json:"priority"`
	Settings    []byte      `json:"settings"`
}

// Membuat atau memperbarui konfigurasi notifikasi per tenant per channel.
// Menggunakan INSERT ON CONFLICT untuk upsert berdasarkan (tenant_id, channel).
func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) (NotificationConfig, error) {
	row := q.db.QueryRow(ctx, upsertConfig,
		arg.TenantID,
		arg.Channel,
		arg.Provider,
		arg.Credentials,
		arg.IsEnabled,
		arg.Priority,
		arg.Settings,
	)
	var i NotificationConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Channel,
		&i.Provider,
		&i.Credentials,
		&i.IsEnabled,
		&i.Priority,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
