// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_templates.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkCreateTemplates = `-- name: BulkCreateTemplates :one
INSERT INTO notification_templates (
    tenant_id, slug, name, category, event_type, channels,
    body_whatsapp, body_sms, body_email_subject, body_email_html,
    variables, is_active, is_default
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13
)
RETURNING id, tenant_id, slug, name, category, event_type, channels, body_whatsapp, body_sms, body_email_subject, body_email_html, variables, is_active, is_default, created_at, updated_at
`

type BulkCreateTemplatesParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	Slug             string      `json:"slug"`
	Name             string      `json:"name"`
	Category         string      `json:"category"`
	EventType        pgtype.Text `json:"event_type"`
	Channels         []byte      `json:"channels"`
	BodyWhatsapp     pgtype.Text `json:"body_whatsapp"`
	BodySms          pgtype.Text `json:"body_sms"`
	BodyEmailSubject pgtype.Text `json:"body_email_subject"`
	BodyEmailHtml    pgtype.Text `json:"body_email_html"`
	Variables        []byte      `json:"variables"`
	IsActive         bool        `json:"is_active"`
	IsDefault        bool        `json:"is_default"`
}

// Membuat satu template notifikasi (dipanggil dalam loop oleh repository untuk bulk insert).
func (q *Queries) BulkCreateTemplates(ctx context.Context, arg BulkCreateTemplatesParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, bulkCreateTemplates,
		arg.TenantID,
		arg.Slug,
		arg.Name,
		arg.Category,
		arg.EventType,
		arg.Channels,
		arg.BodyWhatsapp,
		arg.BodySms,
		arg.BodyEmailSubject,
		arg.BodyEmailHtml,
		arg.Variables,
		arg.IsActive,
		arg.IsDefault,
	)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Category,
		&i.EventType,
		&i.Channels,
		&i.BodyWhatsapp,
		&i.BodySms,
		&i.BodyEmailSubject,
		&i.BodyEmailHtml,
		&i.Variables,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplate = `-- name: CreateTemplate :one

INSERT INTO notification_templates (
    tenant_id, slug, name, category, event_type, channels,
    body_whatsapp, body_sms, body_email_subject, body_email_html,
    variables, is_active, is_default
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13
)
RETURNING id, tenant_id, slug, name, category, event_type, channels, body_whatsapp, body_sms, body_email_subject, body_email_html, variables, is_active, is_default, created_at, updated_at
`

type CreateTemplateParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	Slug             string      `json:"slug"`
	Name             string      `json:"name"`
	Category         string      `json:"category"`
	EventType        pgtype.Text `json:"event_type"`
	Channels         []byte      `json:"channels"`
	BodyWhatsapp     pgtype.Text `json:"body_whatsapp"`
	BodySms          pgtype.Text `json:"body_sms"`
	BodyEmailSubject pgtype.Text `json:"body_email_subject"`
	BodyEmailHtml    pgtype.Text `json:"body_email_html"`
	Variables        []byte      `json:"variables"`
	IsActive         bool        `json:"is_active"`
	IsDefault        bool        `json:"is_default"`
}

// Query SQL untuk operasi CRUD tabel notification_templates.
// Digunakan oleh sqlc untuk menghasilkan kode Go yang type-safe.
// Tabel notification_templates dilindungi RLS, query hanya mengembalikan baris milik tenant aktif.
// Setiap tenant memiliki slug unik per template (UNIQUE pada tenant_id, slug).
// Membuat template notifikasi baru dan mengembalikan template yang dibuat.
func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.TenantID,
		arg.Slug,
		arg.Name,
		arg.Category,
		arg.EventType,
		arg.Channels,
		arg.BodyWhatsapp,
		arg.BodySms,
		arg.BodyEmailSubject,
		arg.BodyEmailHtml,
		arg.Variables,
		arg.IsActive,
		arg.IsDefault,
	)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Category,
		&i.EventType,
		&i.Channels,
		&i.BodyWhatsapp,
		&i.BodySms,
		&i.BodyEmailSubject,
		&i.BodyEmailHtml,
		&i.Variables,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByEventType = `-- name: GetTemplateByEventType :one
SELECT id, tenant_id, slug, name, category, event_type, channels, body_whatsapp, body_sms, body_email_subject, body_email_html, variables, is_active, is_default, created_at, updated_at
FROM notification_templates
WHERE tenant_id = $1 AND event_type = $2 AND is_active = true
`

type GetTemplateByEventTypeParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	EventType pgtype.Text `json:"event_type"`
}

// Mengambil template notifikasi berdasarkan tenant_id dan event_type yang masih aktif.
// Digunakan oleh delivery pipeline untuk resolusi template dari event.
func (q *Queries) GetTemplateByEventType(ctx context.Context, arg GetTemplateByEventTypeParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplateByEventType, arg.TenantID, arg.EventType)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Category,
		&i.EventType,
		&i.Channels,
		&i.BodyWhatsapp,
		&i.BodySms,
		&i.BodyEmailSubject,
		&i.BodyEmailHtml,
		&i.Variables,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, tenant_id, slug, name, category, event_type, channels, body_whatsapp, body_sms, body_email_subject, body_email_html, variables, is_active, is_default, created_at, updated_at
FROM notification_templates
WHERE id = $1
`

// Mengambil template notifikasi berdasarkan ID.
func (q *Queries) GetTemplateByID(ctx context.Context, id pgtype.UUID) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, id)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Category,
		&i.EventType,
		&i.Channels,
		&i.BodyWhatsapp,
		&i.BodySms,
		&i.BodyEmailSubject,
		&i.BodyEmailHtml,
		&i.Variables,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateBySlug = `-- name: GetTemplateBySlug :one
SELECT id, tenant_id, slug, name, category, event_type, channels, body_whatsapp, body_sms, body_email_subject, body_email_html, variables, is_active, is_default, created_at, updated_at
FROM notification_templates
WHERE tenant_id = $1 AND slug = $2 AND is_active = true
`

type GetTemplateBySlugParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Slug     string      `json:"slug"`
}

// Mengambil template notifikasi berdasarkan tenant_id dan slug yang masih aktif.
func (q *Queries) GetTemplateBySlug(ctx context.Context, arg GetTemplateBySlugParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplateBySlug, arg.TenantID, arg.Slug)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Category,
		&i.EventType,
		&i.Channels,
		&i.BodyWhatsapp,
		&i.BodySms,
		&i.BodyEmailSubject,
		&i.BodyEmailHtml,
		&i.Variables,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplatesByTenant = `-- name: ListTemplatesByTenant :many
SELECT id, tenant_id, slug, name, category, event_type, channels, body_whatsapp, body_sms, body_email_subject, body_email_html, variables, is_active, is_default, created_at, updated_at
FROM notification_templates
WHERE tenant_id = $1
ORDER BY created_at ASC
`

// Mengambil semua template notifikasi untuk tenant tertentu, diurutkan berdasarkan waktu pembuatan.
func (q *Queries) ListTemplatesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]NotificationTemplate, error) {
	rows, err := q.db.Query(ctx, listTemplatesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationTemplate{}
	for rows.Next() {
		var i NotificationTemplate
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Category,
			&i.EventType,
			&i.Channels,
			&i.BodyWhatsapp,
			&i.BodySms,
			&i.BodyEmailSubject,
			&i.BodyEmailHtml,
			&i.Variables,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS(
    SELECT 1
    FROM notification_templates
    WHERE tenant_id = $1 AND slug = $2 AND id != $3 AND is_active = true
)
`

type SlugExistsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Slug     string      `json:"slug"`
	ID       pgtype.UUID `json:"id"`
}

// Mengecek apakah slug sudah ada di tenant tertentu (exclude ID tertentu untuk keperluan update).
// Mengembalikan true jika slug sudah dipakai oleh template lain yang masih aktif.
func (q *Queries) SlugExists(ctx context.Context, arg SlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, arg.TenantID, arg.Slug, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteTemplate = `-- name: SoftDeleteTemplate :exec
UPDATE notification_templates
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

// Menonaktifkan template dengan mengatur is_active menjadi false.
// Hanya template custom (is_default=false) yang boleh dihapus (validasi di layer repository).
func (q *Queries) SoftDeleteTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTemplate, id)
	return err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE notification_templates
SET
    name = $2,
    channels = $3,
    body_whatsapp = $4,
    body_sms = $5,
    body_email_subject = $6,
    body_email_html = $7,
    is_active = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, slug, name, category, event_type, channels, body_whatsapp, body_sms, body_email_subject, body_email_html, variables, is_active, is_default, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Channels         []byte      `json:"channels"`
	BodyWhatsapp     pgtype.Text `json:"body_whatsapp"`
	BodySms          pgtype.Text `json:"body_sms"`
	BodyEmailSubject pgtype.Text `json:"body_email_subject"`
	BodyEmailHtml    pgtype.Text `json:"body_email_html"`
	IsActive         bool        `json:"is_active"`
}

// Memperbarui template notifikasi dan mengembalikan template yang diperbarui.
func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.Name,
		arg.Channels,
		arg.BodyWhatsapp,
		arg.BodySms,
		arg.BodyEmailSubject,
		arg.BodyEmailHtml,
		arg.IsActive,
	)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Category,
		&i.EventType,
		&i.Channels,
		&i.BodyWhatsapp,
		&i.BodySms,
		&i.BodyEmailSubject,
		&i.BodyEmailHtml,
		&i.Variables,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
